### ISSUE TITLE
Classification bundle 2.3 does not exists anymore

### ISSUE THREAD

**Issue by mpoiriert** [sonata-project/SonataMediaBundle#1003]
The sonata media bundle refer to the classification bundle version 2.3 that does not exists anymore (it was a dev alias that has bump to 3.0 without a release of the version 2.3)

**Comment by core23** [comment]
We removed the 2.3 version, which never was a stable release. You have to use 3.0 which is nearly the same as 2.3@dev

Please have a look at https://github.com/sonata-project/SonataAdminBundle/issues/3731
