### ISSUE TITLE
Create a provider resolver

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataMediaBundle#1028]
I'm trying to add a mass media import command and was wondering if it is possible to detect which `Provider` supports a given file type. This can be done by create a new `ProviderResolver` which will detect the provider based on the mime type.

**Comment by OskarStark** [comment]
Refs https://github.com/sonata-project/SonataMediaBundle/pull/1105

**Comment by jordisala1991** [comment]
Im closing it for now. I don't thing this belongs to this bundle. You can implement that resolver youself. If it helps a feature of the bundle it could make sense, but just for having it so others can use it on their code to me its not worth it. 

If you think this should remain open, please reopen.
