### ISSUE TITLE
Mixed content error when loading Pixlr iframe

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/SonataMediaBundle#1051]
| Question       | Answer
|----------------|-------------------------------
| Bundle version | dev-master
| Symfony version| 2.8
| php version    | 5.6.20

# Steps to reproduce

Try to edit an image with pixlr if your admin section is under **https**.

# Expected results

I should be able to edit the image

# Actual results

I can't, because the browser obviously refuses to load content served under http in a page under https.

**Comment by OskarStark** [comment]
@ju1ius is this working for you without http?

**Comment by ju1ius** [comment]
@OskarStark Yes, the editor loads.
