### ISSUE TITLE
medias are not filtered by category

### ISSUE THREAD

**Issue by huziatwork** [sonata-project/SonataMediaBundle#1054]
Medias are not filtered by category

| Question | Answer |
| --- | --- |
| Bundle version | 3.x |
| Symfony version | 2.8 |
| php version | 5.5 |
# Steps to reproduce

create medias and assign different categories
# Expected results

Only medias of the current category are visible
# Actual results

All medias are visible

**Comment by jordisala1991** [comment]
Fixed on latest release of MediaBundle 3.4.0
