### ISSUE TITLE
3.0 version does not work with FOSRestBundle 2.0

### ISSUE THREAD

**Issue by desmax** [sonata-project/SonataMediaBundle#1056]
| Question | Answer |
| --- | --- |
| Bundle version | 3.0.0 |
| Symfony version | v2.8.7 |
| php version | PHP 7.0.7-1~dotdeb+8.1 (cli) ( NTS ) |
# Error message

[Doctrine\Common\Annotations\AnnotationException]
  [Creation Error] The annotation @QueryParam declared on method Sonata\MediaBundle\Controller\Api\GalleryController::getGalleriesAction() does not have a property named "array". Available properties: requirements, map, allowBlank, name, key, default, description, strict, nullable, incompatibles
# Steps to reproduce

Install friendsofsymfony/rest-bundle(~2.0@dev) via composer
# Expected results

Installation finishes successfully 
# Actual results

Get previously mentioned error, on step Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

**Comment by Soullivaneuh** [comment]
Your bug report does not follow the format required by the template.

Please update it before proceed.

**Comment by desmax** [comment]
updated

**Comment by desmax** [comment]
https://github.com/desmax/SonataMediaBundle/commit/9e4d16396d90405bb1696b5e2ba42bc602dded0a

**Comment by Bluestart83** [comment]
Same problem!

**Comment by Soullivaneuh** [comment]
@desmax Could you please propose a PR for discussion?

**Comment by Bluestart83** [comment]
Yes desmax@9e4d163.
Thanks @desmax

**Comment by Soullivaneuh** [comment]
@Bluestart83 It's a commit. I was asking about a PR. :wink:

**Comment by Bluestart83** [comment]
Sorry it was my first one ^^*
https://github.com/sonata-project/SonataMediaBundle/pull/1077

**Comment by Soullivaneuh** [comment]
Please don't just open PR without reading contributing guide en template.

For this case, let @desmax doing this. The modification can't be accepted as is.
