### ISSUE TITLE
Question: Do you support symfony 3?

### ISSUE THREAD

**Issue by malavsky** [sonata-project/SonataMediaBundle#1061]
I am trying to use SonataMEdiaBundle with Symfony3 and I got a lot of errors.

**Comment by greg0ire** [comment]
We do

**Comment by aivus** [comment]
@greg0ire it seems media 3.x (also as a master) version are using `request` service, `$this->getRequest()` and another things, which were removed in 3.0.

E.g. incompatible validator syntax:
https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Resources/config/validation.xml#L5

So, do MediaBundle really supports symfony 3?

**Comment by Soullivaneuh** [comment]
@aivus Let's clarify: We autorizhed Symfony 3 and did more possible to fix BC break compatibility.

If you find some issues, please open a dedicated issue.

We will be happy to see also a PR to fix this. :+1:

**Comment by aivus** [comment]
@Soullivaneuh could you clarify, which version will supports only symfony 3 branch and which will supports ^2.3 and ^3.0?

Because, using workarounds for >2.3 and 3.0 complicates code

**Comment by Soullivaneuh** [comment]
Just see the `composer.json` of the current branch: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/composer.json

See also: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/CONTRIBUTING.md#the-base-branch

**Comment by Soullivaneuh** [comment]
> Because, using workarounds for >2.3 and 3.0 complicates code

Maybe, but until the 3.x support SF 2.3, we have to do this.

All PR that can be BC have to be done on the current branch.
