### ISSUE TITLE
admin filter should not be visible for context and providers

### ISSUE THREAD

**Issue by matteosister** [sonata-project/SonataMediaBundle#108]
The filter over the list is always visible, because there is always a context filtered. This should not happen, because on top we have pills to choose the context and the provider.

There are two ways to do so. Implement a custom solution in the MediaAdmin list template (see https://github.com/matteosister/SonataMediaBundle/blob/master/Resources/views/MediaAdmin/list.html.twig at line 47....really ugly I know).

Or add an array parameter to hasActiveFilters() that defaults to an empty array, to exclude filters by name.

What do you think?

**Comment by core23** [comment]
Fixed now
