### ISSUE TITLE
Page overload on admin show view

### ISSUE THREAD

**Issue by bartosz-malec** [sonata-project/SonataMediaBundle#1102]
I have this issue on few application which are currently updated to latest version of SonataMediaBundle: 3.1.0.

Problem is connected with overloading page view on editAction in Sonata media admin.

I diagnosed that is related with deprecated functionality of SonataMediaBundle. Problem is in: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Resources/views/MediaAdmin/edit.html.twig#L75

After change in this line:
`{{ sonata_media.pool.downloadSecurity(object).description|raw }}`
to:
`{{ sonata_media.pool.downloadStrategy(object).description|raw }}`
issue disapear.

**Comment by greg0ire** [comment]
IIRC this was renamed lately, maybe this rename was forgotten? If yes, can you provide a PR?

**Comment by bartosz-malec** [comment]
I see that you fixed it on version 3.2.
