### ISSUE TITLE
MediaBundle & ClassificationBundle dependency

### ISSUE THREAD

**Issue by meandus** [sonata-project/SonataMediaBundle#1117]
Is it possible to remove completly ClassificationBundle ?

Category already exists in my schema and there are a lot of mistakes with Classification.
Category is now mandatory to upload a Media on version 3.X
I don't want to use Classification ... just have a good MediaBundle / GalleryBundle ...

**Comment by idchlife** [comment]
This is so true!

Right now I cannot overcome all the errors and issues in ClassificationBundle, so I ought to remove this dependency, but I presume it cannot be done at the moment

**Comment by core23** [comment]
The dependency will be removed with the next major version: https://github.com/sonata-project/SonataMediaBundle/pull/1086
