### ISSUE TITLE
Ajax : add new image on a ManyToOne relationship, actions on popup don't trigger anything

### ISSUE THREAD

**Issue by btribouillet** [sonata-project/SonataMediaBundle#1127]
Hi, here an issue i'm facing since i updated to the latest stable versions of Sonata bundles.
### Environment

php 7.0
sf3
#### Sonata packages

"sonata-project/core-bundle": "^3.0",
"sonata-project/easy-extends-bundle": "2.1.10",
"sonata-project/admin-bundle": "^3.1",
"sonata-project/doctrine-orm-admin-bundle": "3.1.0",
"sonata-project/datagrid-bundle": "2.2",
"sonata-project/classification-bundle": "3.1.0",
"sonata-project/intl-bundle": "^2.2",
"sonata-project/media-bundle": "dev-fixes",
"sonata-project/block-bundle": "3.2.0",
"sonata-project/formatter-bundle": "3.0.1",
"sonata-project/notification-bundle": "3.0.0",

``` bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.8.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0             Symfony SonataBlockBundle
sonata-project/cache                     1.0.7             Cache library
sonata-project/classification-bundle     3.1.0             Symfony SonataClassificationBundle
sonata-project/core-bundle               3.1.1             Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2               Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2             Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.0             Symfony Sonata / Integrate Doctrine ORM into the SonataA...
sonata-project/easy-extends-bundle       2.1.10            Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0             Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1             Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.2.4             Symfony SonataIntlBundle
sonata-project/media-bundle              dev-fixes 1639d1a Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0             Symfony SonataNotificationBundle

#### Symfony packages

$ composer show symfony/*
symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/intl               v3.0.6  A PHP replacement layer for the C intl extension that includes additional data f...
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.1.5  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v3.0.9  The Symfony PHP framework

#### PHP version

$ php -v
PHP 7.0.9 (cli) (built: Jul 21 2016 14:50:47) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```
## Subject

I updated all my sonata bundles to be able to upgrade my symfony version (2.7) to 3.\* (Already fixed the sf structures and deprecated warnings). I use a fork of SonataMediaBundle where i applied a fixe from a PR #1115 . (The bug i'm talking about is as well with version 3.3.0).

**Nothing is triggered when i select a media provider from the popup. I can access the route but of course the media would not be added to the entity.** 

Here the message from the console :

> [Sonata.Admin] [s57f5651e4250f_avatar|field_dialog_form_action] action catch, http://myapp.dev/admin/sonata/media/media/create?context=default&category=1&hide_context=0&provider=sonata.media.provider.image
> 
> Admin.js:136[Sonata.Admin] [s57f5651e4250f_avatar|field_dialog_form_action] execute ajax call
> 
> jquery.js:8630 XHR finished loading: GET "http://myapp.dev/admin/sonata/media/media/create?context=default&category=1&hide_context=0&provider=sonata.media.provider.image&_xml_http_request=true".

**Nothing is triggered when i select an image from the popup (list). (No messages in console)**

By the way, this was perfectly working with the previous bundles
## Steps to reproduce
- Click on add new

<img width="477" alt="screen shot 2016-10-06 at 09 07 25" src="https://cloud.githubusercontent.com/assets/7518508/19144266/d8646082-8ba8-11e6-806c-40da648dec94.png">
- Click on image (media provider)

<img width="407" alt="screen shot 2016-10-05 at 22 13 37" src="https://cloud.githubusercontent.com/assets/7518508/19144316/147829fa-8ba9-11e6-8ae9-218577860e3c.png">

OR
- Click on list

<img width="477" alt="screen shot 2016-10-06 at 09 07 25" src="https://cloud.githubusercontent.com/assets/7518508/19144334/2f64a676-8ba9-11e6-8aae-c5cbe8b5890a.png">
- Select an image

<img width="631" alt="screen shot 2016-10-05 at 22 13 54" src="https://cloud.githubusercontent.com/assets/7518508/19144342/38af56d6-8ba9-11e6-8fa7-e0b8f101bef0.png">

No errors in logs.

**Comment by btribouillet** [comment]
Could someone without this issue using Sonata media bundle version 3.* show is composer.json so i could compare with mine? Thank you in advance.

**Comment by btribouillet** [comment]
I'm still experiencing this issue, therefore i'm not able yet to switch from sf 2.8 to sf3. What could i do to fix it? I'm willing to fix if it is a common issue.

**Comment by greg0ire** [comment]
Do you know how to do step-by-step debugging ? I know that in firefox, you can see the what jQuery event is bound to a given html element, maybe check that on a working install, see what is supposed to be called, then upgrade, and see if it is still bound, still called, and if yet, why it doesn't do anything.

**Comment by btribouillet** [comment]
I'm not really familiar with it. I just did but unfortunately it straight throw an exception in jquery.js

`jQuery.parseJSON = function( data ) {
	return JSON.parse( data + "" );
};`

> Pause on exception: 'SyntaxError: Unexpected token < in JSON at position 26'.

Here just an excerpt of what contains data (which seem to be correct).


            
            <div class="row">
        
        <div class="col-md-6">
                                

    
            <form
                            role="form"
              action="/admin/sonata/media/media/create?context=default&amp;category=1&amp;hide_context=0&amp;uniqid=s5838419942b60"
               enctype="multipart/form-data"              method="POST"
                                          >`

**Comment by greg0ire** [comment]
Uuuh I don't see the data here, but maybe you can try json linting it if you have access to it.

**Comment by btribouillet** [comment]
Okay so i checked the responses from the XHR requests.

The response is pure HTML and not a json. This is probably why i have an exception when it try to parse it. It takes sense.

Now what i don't understand is : does sonata expect a json response or pure html?

**Comment by greg0ire** [comment]
> does sonata expect a json response or pure html?

Well you'd have to find the corresponding code to answer that. When you get the exception, do you have a stack trace? If yes, try to find the ancestor functions

**Comment by btribouillet** [comment]
Okay thank you. I guess i'll fork the project with a clean sf3 installation. That is gonna be easier. I will check for a stack trace.

I'll let you know how it goes.

**Comment by greg0ire** [comment]
Great! Good luck.

**Comment by btribouillet** [comment]
Hmm i can't duplicate the issue with a fresh installation. I'll compare what i have on my application and come back with an answer (and hopefully close this issue).

**Comment by btribouillet** [comment]
Response header when calling **/admin/sonata/media/media/create?context=default&category=1&hide_context=0&provider=sonata.media.provider.image&_xml_http_request=true** 

My current project :

    Response header : 
        Content-Type:application/json

With the working fresh installation : 

    Response header : 
        Content-Type:text/html; charset=UTF-8

So it does expect a response in html. So this is why on my current project it tries to parse it while it should not. What is weird is that the popup has indeed Content-Type:text/html; charset=UTF-8 set, only the provider selection is set with Content-Type:application/json.

I've been comparing everything, and i have all the same versions and same config. Do you think it could be a conflict with another bundle?

**Comment by greg0ire** [comment]
It might be, I really don't know. You could try setting a breakpoint in the response class at the lines where headers can be changed.

**Comment by btribouillet** [comment]
Okay, so there was a conflict with FOS Rest Bundle.

**fos_rest config :** 

BEFORE : (json as priority with a json fallback format)

    format_listener:
         rules:
             - { path: '^/', priorities: ['json','html','xml'], fallback_format: json, prefer_extension: true }

AFTER : 

    format_listener: true

I let the app require the needed format.

I still can't explain why it was only happening with this route. My guess is that the required format was not specified therefore it would return a json.

**Comment by greg0ire** [comment]
Oh, right, I've had myself problems with fos rest and param converters. Version 2 should be less invasive. Thanks for sharing your solution!
