### ISSUE TITLE
Problem BaseMediaAdmin line 109

### ISSUE THREAD

**Issue by paoloCastroPullmedia** [sonata-project/SonataMediaBundle#1143]
Hello,
With the master version line 109 is
                $media->setProviderName($this->getRequest()->get(sprintf('%s[providerName]', $this->getUniqid()), null, true));
but it create an error, i don't want to use classificationBundle maybe it's because of that.

But i fix it by changing this by that :
                $media->setProviderName($this->getRequest()->get(sprintf('%s', $this->getUniqid()), null, true)['providerName']);

the error what i got with the current version of master is 

Impossible to access a key ("default") on a boolean variable ("") in SonataAdminBundle:CRUD:base_edit_form.html.twig at line 55.

Do there is another solution?
Thank you

**Comment by greg0ire** [comment]
Don't use the master version. Ever.

**Comment by paoloCastroPullmedia** [comment]
So how i can I remove classificationBundle from Media?

**Comment by greg0ire** [comment]
Use the stable version of all the bundles you use?
