### ISSUE TITLE
helper

### ISSUE THREAD

**Issue by ahbaqdadi** [sonata-project/SonataMediaBundle#1154]
### Environment
mac os
#### Sonata packages

sonata-project/admin-bundle 3.10.2
sonata-project/block-bundle 3.2.0
sonata-project/cache 1.0.7
sonata-project/classification-bundle 3.x-dev
sonata-project/core-bundle 3.1.2
sonata-project/datagrid-bundle 2.2
sonata-project/doctrine-extensions 1.0.2
sonata-project/doctrine-orm-admin-bundle 3.1.2
sonata-project/easy-extends-bundle 2.1.10
sonata-project/exporter 1.7.0
sonata-project/formatter-bundle 3.1.0
sonata-project/google-authenticator 1.0.2
sonata-project/intl-bundle 2.2.4
sonata-project/media-bundle 3.3.0
sonata-project/news-bundle 3.0.0
sonata-project/notification-bundle 3.0.0
sonata-project/user-bundle 3.2.0

#### Symfony packages

symfony/monolog-bundle 2.11.3
symfony/phpunit-bridge v2.8.15
symfony/polyfill-apcu v1.3.0
symfony/polyfill-intl-icu v1.3.0
symfony/polyfill-mbstring v1.3.0
symfony/polyfill-php54 v1.3.0
symfony/polyfill-php55 v1.3.0
symfony/polyfill-php56 v1.3.0
symfony/polyfill-php70 v1.3.0
symfony/polyfill-util v1.3.0
symfony/security-acl v3.0.0
symfony/swiftmailer-bundle v2.4.2
symfony/symfony v2.8.15

#### PHP version

PHP 5.6.10

## Subject

sonata media bundle 3

I've uploaded image

but when i want to use this ( {% path image.image, 'small' %} ) helper i got nothing ,

try to change permission with chmod 777 -R in web/uploads , but still not working ,

it just can handle this helper {% path image.image, 'reference' %} , because already exist on upload directory , but can't generate

**Comment by oidnus** [comment]
show config sonata_media:

**Comment by ahbaqdadi** [comment]
`sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
#            path: /uploads/media # http://media.sonata-project.org/
             path: /abzar_jarahi/web/uploads/media

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false
    providers:
        image:
            resizer: sonata.media.resizer.square
`

**Comment by ahbaqdadi** [comment]
sonata_media:
    db_driver: doctrine_orm 
    default_context: default 
    contexts:
        default:  
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
             path: /abzar_jarahi/web/uploads/media

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false
    providers:
        image:
            resizer: sonata.media.resizer.square

**Comment by jordisala1991** [comment]
Did you fix your issue? Seems more a problem with configuration than a problem on SonataMediaBundle. If you are still facing this issue, please ping me to reopen.

Closing
