### ISSUE TITLE
Add sonata.media.provider.mp4

### ISSUE THREAD

**Issue by binhle410** [sonata-project/SonataMediaBundle#1161]
It would be nice if we could have an mp4 provider which can use FFMPEG to generate thumbnails for the video and have better metadata for the mp4 format. It can extend the file provider and add some more functionality.

**Comment by core23** [comment]
Feel free to start and provide a PR

**Comment by OskarStark** [comment]
I close this PR, due to no action...

Because of the FFMPEG dependency, I would recommend to create this via a separate bundle/lib
