### ISSUE TITLE
Add a arbitrary image format/extension in format config

### ISSUE THREAD

**Issue by Erfans** [sonata-project/SonataMediaBundle#1168]
Sometimes for design purposes it is good to have a predefined image format (e.g. jpg) so a specific thumbnail would never have any transparency. 
As mentioned in #106 and [548e3b5](https://github.com/sonata-project/SonataMediaBundle/commit/548e3b5136b3241c943626a5c6f5d9ab9a146c5d) the current approach is that the thumbnail format is same as reference image to transfer its features to thumbnails such as transparency (unless doing some tricks in entity file which affect all thumbnails). 
But sometimes the exact opposed is necessary, I suggest to add an optional parameter to format, if it is defined then thumbnail will generated according to the defined format, and if it is not defined thumbnail will generated based on reference format.

```
 formats:
         slide: { width: 320,  format: jpg}  # makes sure that thumbnail is jpg
         small: { width: 185 } # thumbnail format same as reference image to preserve its features 
````

**Comment by greg0ire** [comment]
> so a specific thumbnail would never have any transparency.

When would you need that? When the background color of the thumbnail is not the same as that of the file?

**Comment by Erfans** [comment]
Yes, specially when images are over top of each other in some animations. And also when using images in canvas.
Also I think it is a good feature in sense of efficiency to decrease size of images by changing their formats.

**Comment by greg0ire** [comment]
Not everything that compresses well in PNG compresses well in JPEG and vice versa. Why not just drop the alpha channel instead? Seems cleaner to me.

**Comment by greg0ire** [comment]
To clarify, jpegs are best suited for photos of real things, while PNG is better for logos or other things where you have the very same color on many adjacent pixels.

**Comment by Erfans** [comment]
I dont know exactly how to drop alpha channel? However I think it is possible, I also thought of some css tricks and in case of canvas do something with js, but I think the best practice would be the type format. Also later on if this bundle supports gif format then by changing type it generates the non-motion thumbnails.

**Comment by greg0ire** [comment]
> the type format

What do you mean by that?

**Comment by greg0ire** [comment]
> I dont know exactly how to drop alpha channel?

I don't know how to do that either. I see we are using Imagine, so maybe there is a filter for that (resetting the alpha value of every pixel in the image to 255 or whatever).

**Comment by greg0ire** [comment]
I think I found something : https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Filter/Advanced/OnPixelBased.php#L20

This filter can let you apply any callable on each pixel. So just write a callable that makes every pixel 100% opaque, and problem solved!

**Comment by Erfans** [comment]
> What do you mean by that?
I meant the configuration to choose a image type (png, jpg, etc.)

**Comment by greg0ire** [comment]
Yeah so you mean change something that was compressed as jpg in png for instance? That's really not a good practice.

**Comment by Erfans** [comment]
> This filter can let you apply any callable on each pixel. So just write a callable that makes every pixel 100% opaque, and problem solved!
Thanks for this solution. I will give it a try.
Still I think it is a useful option to add a configuration for choosing the image format. I took a look to the code and it doesn't seem very complected. Perhaps I will provide a PR.

**Comment by greg0ire** [comment]
Might be easy, but… should be discouraged IMO. Or it means you don't trust users to pick the right image format for their avatar. And you can only loose information when converting from one format to another, which means that the result can only be uglier.

**Comment by Erfans** [comment]
I see your point, and I agree there is some loss in it, but this loss will reduce the traffic (specially for large images). I just checked facebook, it converts png to jpg.

**Comment by greg0ire** [comment]
Not sure SonataMediaBundle users have the same traffic issues than fb does, but why not?

**Comment by greg0ire** [comment]
I just had a small chat with @romainneutron about this issue, and he says your solution might be good after all, so let's try it, and see the end results. Would you be willing to provide a PR, but also screenshots of the end result?

**Comment by Erfans** [comment]
Yes, I can do a PR but it perhaps takes some times to be done. By screenshot you mean to compare a transformed image to its original format?

**Comment by greg0ire** [comment]
> Yes, I can do a PR but it perhaps takes some times to be done. By screenshot you mean to compare a transformed image to its original format?

Yes

**Comment by Erfans** [comment]
it is still relevant. still a nice feature but unfortunately i dont have enough time to implement it.
