### ISSUE TITLE
BUG: Filter media by category in Sonata Sandbox

### ISSUE THREAD

**Issue by TheCelavi** [sonata-project/SonataMediaBundle#1176]
It is impossible to filter media by category in Sonata Sandbox (ORM as storage).

Bugfix is trivial, category field should be specified as 'doctrine_orm_choice'.

I am so confused in which branch to do a PR, master or 3.x or both?

Here is the fix, btw: https://github.com/RunOpenCode/SonataMediaBundle/commit/23575ad0a4a0c314bd5a524926561c66ee8ca9d9

Thanks.

**Comment by greg0ire** [comment]
If it is backwards-compatible, do it on 3.x only, it will be merged in master automatically.
