### ISSUE TITLE
FormatterMediaExtension issue

### ISSUE THREAD

**Issue by Adraesh** [sonata-project/SonataMediaBundle#1215]
Hello,

Just updated to media 3.4 using composer and it seems there is an issue. Bellow the output:

> PHP Fatal error:  Class Sonata\MediaBundle\Twig\Extension\FormatterMediaExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_ExtensionInterface::getName) in /var/www/vendor/sonata-project/media-bundle/Twig/Extension/FormatterMediaExtension.php on line 19

**Comment by greg0ire** [comment]
Can someone bisect that down to a particular commit?

**Comment by JonathanBaudoin** [comment]
The remaining method is `getName()` from `\Twig_ExtensionInterface`.

**Comment by jordisala1991** [comment]
could be this PR: https://github.com/sonata-project/SonataMediaBundle/pull/1184/files

I am looking for the class extended

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/SonataFormatterBundle/pull/231

This one is merged, should fix the issue, but there is no release of SonataFormatter that contains this fix

**Comment by greg0ire** [comment]
It's not good enough, we have to be compatible with both versions of Twig.

**Comment by jordisala1991** [comment]
Ok, I am opening a PR

**Comment by jordisala1991** [comment]
@Adraesh @JonathanBaudoin Can you check if this is still an issue if you use `SonataFormatterBundle: "3.x-dev"`?

**Comment by Adraesh** [comment]
First of all, thanks for you reactivity !

Then I believe I missed something ?

> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating sonata-project/media-bundle (3.3.1 => 3.4.0) Downloading: 100%         
Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Class Sonata\MediaBundle\Twig\Extension\FormatterMediaExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_ExtensionInterface::getName) in /Users/thomas/projects/indigo/www/vendor/sonata-project/media-bundle/Twig/Extension/FormatterMediaExtension.php on line 20
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

                                                                                                             
  [RuntimeException]                                                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                  
  PHP Fatal error:  Class Sonata\MediaBundle\Twig\Extension\FormatterMediaExtension contains 1 abstract met  
  hod and must therefore be declared abstract or implement the remaining methods (Twig_ExtensionInterface::  
  getName) in /Users/thomas/projects/indigo/www/vendor/sonata-project/media-bundle/Twig/Extension/Formatter  
  MediaExtension.php on line 20

**Comment by jordisala1991** [comment]
You need to update also formatter-bundle to 3.x-dev

**Comment by Adraesh** [comment]
All good! Thank you very much!

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Removing sonata-project/formatter-bundle (3.1.0)
  - Installing sonata-project/formatter-bundle (3.x-dev ea0781e) Cloning ea0781e789 from cache
Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug true                                                          

                                                                                                                        
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.                                            
                                                                                                                        

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- ------------------------- ------------------ 
      Bundle                    Method / Error    
 --- ------------------------- ------------------ 
  ✔   FrameworkBundle           relative symlink  
  ✔   SonataCoreBundle          relative symlink  
  ✔   SonataFormatterBundle     relative symlink  
  ✔   IvoryCKEditorBundle       relative symlink  
  ✔   SonataAdminBundle         relative symlink  
  ✔   SonataUserBundle          relative symlink  
  ✔   SonataTranslationBundle   relative symlink  
  ✔   SonataMediaBundle         relative symlink  
  ✔   SonataPageBundle          relative symlink  
  ✔   NelmioApiDocBundle        relative symlink  
 --- ------------------------- ------------------ 

                                                                                                                        
 [OK] All assets were successfully installed.                                                                           
                                                                                                                        

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
```

**Comment by jordisala1991** [comment]
Let's get a new release of SonataFormatterBundle then @greg0ire and then add a conflict section for SonataFormatter less than 3.1.0 on SonataMedia?

**Comment by greg0ire** [comment]
Good plan! :+1:

**Comment by gremo** [comment]
Same issue here... please fix :)

**Comment by Adraesh** [comment]
@gremo Did you update FormatterBundle to 3.x-dev to get the hotfix ?

As they said they will push a new release in SonataFormatterBundle "normal" (3.x) branch later.

**Comment by gremo** [comment]
@Adraesh Yes I did, an it works. Thanks. Don't like the `-dev` anyways, I'll way for the next release.

**Comment by gremo** [comment]
`"sonata-project/formatter-bundle": "^3.2"` fixes the issues. Thanks.

**Comment by jordisala1991** [comment]
Closing this, SonataFormatterBundle 3.2.0, fixes the issue.

**Comment by core23** [comment]
Shouldn't we update the composer.json file for this issue?

**Comment by greg0ire** [comment]
Yes we should, can someone contribute a PR?

**Comment by Adraesh** [comment]
I confirm all good with "sonata-project/formatter-bundle": "^3.2"

> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating symfony/swiftmailer-bundle (v2.5.0 => v2.5.1) Downloading: 100%         
  - Updating sonata-project/formatter-bundle (3.x-dev 6abcbbe => 3.2.0) Checking out 6abcbbe76a
Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug true                                                          

                                                                                                                        
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.                                            
                                                                                                                        

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- ------------------------- ------------------ 
      Bundle                    Method / Error    
 --- ------------------------- ------------------ 
  ✔   FrameworkBundle           relative symlink  
  ✔   SonataCoreBundle          relative symlink  
  ✔   SonataFormatterBundle     relative symlink  
  ✔   IvoryCKEditorBundle       relative symlink  
  ✔   SonataAdminBundle         relative symlink  
  ✔   SonataUserBundle          relative symlink  
  ✔   SonataTranslationBundle   relative symlink  
  ✔   SonataMediaBundle         relative symlink  
  ✔   SonataPageBundle          relative symlink  
  ✔   NelmioApiDocBundle        relative symlink  
 --- ------------------------- ------------------ 

                                                                                                                        
 [OK] All assets were successfully installed.                                                                           
                                                                                                                        

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget

Thanks for your involvement and dedication.
