### ISSUE TITLE
INVALID MODE when create a new Gallery

### ISSUE THREAD

**Issue by ibasaw** [sonata-project/SonataMediaBundle#1233]
#### Sonata packages

sonata-project/admin-bundle              3.14.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.1  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.2.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/media-bundle              3.5.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0  Symfony SonataNotificationBundle

#### Symfony packages

symfony/assetic-bundle     v2.8.1            Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1           Symfony MonologBundle
symfony/phpunit-bridge     v2.8.18           Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0            Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-iconv     v1.3.0            Symfony polyfill for the Iconv extension
symfony/polyfill-intl-icu  v1.3.0            Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0            Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0            Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0            Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0            Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0            Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0            Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.3            Symfony SwiftmailerBundle
symfony/symfony            2.8.x-dev 6b4cfd6 The Symfony PHP framework

#### PHP version

PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

## Subject

INVALID MODE : s58cbe25ba4c4a_galleryHasMedias - type : sonata_type_collection - mapping :

## Steps to reproduce

NO admin class, just fresh install + Sonata Admin + Sonata Media: add 2 medias, then add a gallery

here the content of the block in the dashboard

Gallery
Media 
INVALID MODE : s58cbe25ba4c4a_galleryHasMedias - type : sonata_type_collection - mapping :

## Expected results

a button who launch the list media choice

## Actual results

INVALID MODE : s58cbe25ba4c4a_galleryHasMedias - type : sonata_type_collection - mapping :

**Comment by core23** [comment]
Please provide a stack trace

**Comment by ibasaw** [comment]
no error on page, no error in the debug toolbar, how to provide the stack trace if no error occur ?

**Comment by core23** [comment]
How should we help you without any hint?

Please have a look at the log files.

**Comment by greg0ire** [comment]
You can also grep the code for INVALID MODE and throw an exception there, it will give you a stack trace.

**Comment by ibasaw** [comment]
grep result said the error occur because of this file: vendor/sonata-project/doctrine-orm-admin-bundle/Resources/views/Form/form_admin_fields.html.twig

I had no error at all in all my log files

**Comment by greg0ire** [comment]
Can you make this a link?

**Comment by ibasaw** [comment]
my sonata_admin.field_description.mappingtype is null, dumped it in the override twig file

**Comment by ibasaw** [comment]
work with

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/sidz/SonataMediaBundle.git"
        }
    ]

        "sonata-project/admin-bundle": "^2.3.9",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3.4",
        "sonata-project/media-bundle": "2.3.x-dev",
        "sonata-project/core-bundle": "^2.3.9",
        "sonata-project/intl-bundle": "^2.3.0"

don't with:

        "sonata-project/admin-bundle": "^3.14",
        "sonata-project/doctrine-orm-admin-bundle": "^3.1",
        "sonata-project/media-bundle": "^3.5",
        "sonata-project/core-bundle": "^3.2"

**Comment by OskarStark** [comment]
still a problem or can we close this issue?

**Comment by loclamor** [comment]
Hi, I'm having he same error, on a fresh SoantaAdmin + SonataMedia installation (I have followed pont by point the documentation at https://sonata-project.org/bundles/media/3-x/doc ) and I cannot add any media to a gallery.
Is there any way to make it work in sonataMedia 3.X ?

**Comment by OskarStark** [comment]
cc @silasjoisten can you help?

**Comment by silasjoisten** [comment]
@loclamor did you override the GalleryAdmin?
if you did try this in your GalleryAdmin:

```php
            ->add('galleryHasMedias', CollectionType::class, ['by_reference' => false],
                    [
                        'edit' => 'inline',
                        'inline' => 'table',
                        'sortable' => 'position',
                        'link_parameters' => ['context' => $context],
                        'admin_code' => 'sonata.media.admin.gallery_has_media',
                    ])
```

**Comment by loclamor** [comment]
badly it didn't do the trick, as this part of code is already in the base GalleryAdmin

**Comment by ibasaw** [comment]
got same today on

```
        "sonata-project/admin-bundle": "^3.43",
        "sonata-project/block-bundle": "^3.13",
        "sonata-project/doctrine-orm-admin-bundle": "^3.7",
        "sonata-project/media-bundle": "^3.16",
```

```
Médias 
INVALID MODE : sbb21f6c7fa_galleryHasMedias - type : sonata_type_collection - mapping :
```

**Comment by ibasaw** [comment]
ok, i resolved it but i don't understand why....

i had re-generated my en entity with the sonataeasyextend...all files where identical, my editor didn't see any changes. why not.

i had clear composer cache, delete my vendors folder, install again... already did it many times before with no results. 

and i finnaly re-force the doctrine schema update and it works !????!!!

**Comment by OskarStark** [comment]
Weird...
Maybe doctrine caches?

**Comment by loclamor** [comment]
Seems to finally work for me this morning !
Yesterday I just have install sonata UserBundle, and do a few composer update. Perhaps a dependency have been upgraded and fixes the problem ?
