### ISSUE TITLE
Media Image update error

### ISSUE THREAD

**Issue by Globax** [sonata-project/SonataMediaBundle#1234]
Hi,

In Pool class (https://github.com/sonata-project/SonataMediaBundle/blob/2.x/Provider/Pool.php) and in another places you are using AdminBundle Validation
`use Sonata\AdminBundle\Validator\ErrorElement;`

But in validation.xml (https://github.com/sonata-project/SonataMediaBundle/blob/2.x/Resources/config/validation.xml) you are using CoreBundle Validation
```
<constraint name="Sonata\CoreBundle\Validator\Constraints\InlineConstraint" >
   <option name="service">sonata.media.pool</option>
   <option name="method">validate</option>
</constraint>
```
And then i got error http://prntscr.com/el8bb2

So, please replace `CoreBundle` to `AdminBundle`.

**Comment by greg0ire** [comment]
Hello. Version 2 of the bundle is no longer supported, no change will be made. Please upgrade.
