### ISSUE TITLE
Upgrading from 3.3.1 to 3.5.0: Admin media list is empty

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataMediaBundle#1235]
### Environment
php-fpm, nginx, mariadb docker images. everything worked before update
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.14.0  The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.1   Symfony SonataBlockBundle
sonata-project/cache                     1.0.7   Cache library
sonata-project/cache-bundle              2.3.1   This bundle provides caching services
sonata-project/classification-bundle     3.3.0   Symfony SonataClassificationBundle
sonata-project/core-bundle               3.2.0   Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1   Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2   Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.3   Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1   Lightweight Exporter library
sonata-project/formatter-bundle          3.2.0   Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2   Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.0   Symfony SonataIntlBundle
sonata-project/media-bundle              3.5.0   Symfony SonataMediaBundle
sonata-project/news-bundle               3.1.1   Symfony SonataNewsBundle
sonata-project/notification-bundle       3.1.0   Symfony SonataNotificationBundle
sonata-project/page-bundle               3.4.0   This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.1.0   Symfony SonataSeoBundle
sonata-project/timeline-bundle           3.1.0   Integrates SpyTimelineBundle into Sonata
sonata-project/user-bundle               3.2.2   Symfony SonataUserBundle

```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle                   v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle                   v2.12.1 Symfony MonologBundle
symfony/polyfill-apcu                    v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu                v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring                v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54                   v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55                   v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56                   v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70                   v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                    v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl                     v2.8.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle               v2.5.3  Symfony SwiftmailerBundle
symfony/symfony                          v2.8.17 The Symfony PHP framework

```

#### PHP version

```bash
$ php -v
PHP 5.6.30 (cli) (built: Mar  3 2017 22:45:17)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

## Subject

After upgrading from 3.3.1 to 3.5.0 all medias vanished from the media admin list.
/admin/sonata/media/media/list

## Steps to reproduce
1. upload medias in 3.3.1
2. upgrade to 3.5.0
## Expected results
media list shows medias
## Actual results
media list vanished. reseting filters does not help.
All other media routes work properly. I tested admin edit route and files are loaded properly in frontend.

**Comment by jordisala1991** [comment]
Are you extending some code or changing some templates?

Is there any error message on the page (debug toolbar)?

What is the `context` property of the images?

Would be nice to have some stack trace or images to ilustrate the problem

**Comment by haivala** [comment]
There isn't any error messages. Apparently the list doesn't find any matching madias from the database anymore. Haven't touched in the templates.
More info coming when I have time

**Comment by haivala** [comment]
Here's doctrine queries with route `/admin/sonata/media/media/list?category=1&context=People&filters=reset&hide_context=0`
With 3.3.1:
`
11:49:52
doctrine	SELECT t0.name AS name_1, t0.enabled AS enabled_2, t0.created_at AS created_at_3, t0.updated_at AS updated_at_4, t0.id AS id_5 FROM classification__context t0 WHERE t0.id = ?
Context: ["People"]
11:49:52
doctrine	SELECT c0_.name AS name_0, c0_.enabled AS enabled_1, c0_.slug AS slug_2, c0_.description AS description_3, c0_.position AS position_4, c0_.created_at AS created_at_5, c0_.updated_at AS updated_at_6, c0_.id AS id_7, c0_.parent_id AS parent_id_8, c0_.context AS context_9, c0_.media_id AS media_id_10 FROM classification__category c0_ WHERE c0_.context = ? ORDER BY c0_.parent_id ASC
Context: ["People"]
11:49:52
doctrine	SELECT t0.name AS name_1, t0.enabled AS enabled_2, t0.slug AS slug_3, t0.description AS description_4, t0.position AS position_5, t0.created_at AS created_at_6, t0.updated_at AS updated_at_7, t0.id AS id_8, t0.parent_id AS parent_id_9, t0.context AS context_10, t0.media_id AS media_id_11 FROM classification__category t0 WHERE t0.id = ? AND t0.context = ? LIMIT 1
Context: [1,"People"]
11:49:52
doctrine	SELECT count(DISTINCT m0_.id) AS sclr_0 FROM media__media m0_ WHERE m0_.context LIKE ?
Context: ["%People%"]
11:49:52
doctrine	SELECT c0_.name AS name_0, c0_.enabled AS enabled_1, c0_.slug AS slug_2, c0_.description AS description_3, c0_.position AS position_4, c0_.created_at AS created_at_5, c0_.updated_at AS updated_at_6, c0_.id AS id_7, c0_.parent_id AS parent_id_8, c0_.context AS context_9, c0_.media_id AS media_id_10 FROM classification__category c0_
11:49:52
doctrine	SELECT DISTINCT m0_.id AS id_0, m0_.id AS id_1 FROM media__media m0_ WHERE m0_.context LIKE ? ORDER BY m0_.id ASC LIMIT 32 OFFSET 0
Context: ["%People%"]
11:49:52
doctrine	SELECT m0_.name AS name_0, m0_.description AS description_1, m0_.enabled AS enabled_2, m0_.provider_name AS provider_name_3, m0_.provider_status AS provider_status_4, m0_.provider_reference AS provider_reference_5, m0_.provider_metadata AS provider_metadata_6, m0_.width AS width_7, m0_.height AS height_8, m0_.length AS length_9, m0_.content_type AS content_type_10, m0_.content_size AS content_size_11, m0_.copyright AS copyright_12, m0_.author_name AS author_name_13, m0_.context AS context_14, m0_.cdn_is_flushable AS cdn_is_flushable_15, m0_.cdn_flush_identifier AS cdn_flush_identifier_16, m0_.cdn_flush_at AS cdn_flush_at_17, m0_.cdn_status AS cdn_status_18, m0_.updated_at AS updated_at_19, m0_.created_at AS created_at_20, m0_.id AS id_21, m0_.category_id AS category_id_22 FROM media__media m0_ WHERE m0_.context LIKE ? AND m0_.id IN (?) ORDER BY m0_.id ASC
Context: ["%People%",[2,3,18,19,20,55,56,58,59,60,61,62,64,65,66,67,68,69,70,71,72,73,79,80,81,82,83,84,85,86,87,88]]
`
with 3.5.0:
`
13:10:34
doctrine	SELECT t0.name AS name_1, t0.enabled AS enabled_2, t0.created_at AS created_at_3, t0.updated_at AS updated_at_4, t0.id AS id_5 FROM classification__context t0 WHERE t0.id = ?
Context: ["People"]
13:10:34
doctrine	SELECT c0_.name AS name_0, c0_.enabled AS enabled_1, c0_.slug AS slug_2, c0_.description AS description_3, c0_.position AS position_4, c0_.created_at AS created_at_5, c0_.updated_at AS updated_at_6, c0_.id AS id_7, c0_.parent_id AS parent_id_8, c0_.context AS context_9, c0_.media_id AS media_id_10 FROM classification__category c0_ WHERE c0_.context = ? ORDER BY c0_.parent_id ASC
Context: ["People"]
13:10:34
doctrine	SELECT t0.name AS name_1, t0.enabled AS enabled_2, t0.slug AS slug_3, t0.description AS description_4, t0.position AS position_5, t0.created_at AS created_at_6, t0.updated_at AS updated_at_7, t0.id AS id_8, t0.parent_id AS parent_id_9, t0.context AS context_10, t0.media_id AS media_id_11 FROM classification__category t0 WHERE t0.id = ? AND t0.context = ? LIMIT 1
Context: [1,"People"]
13:10:34
doctrine	SELECT c0_.name AS name_0, c0_.enabled AS enabled_1, c0_.slug AS slug_2, c0_.description AS description_3, c0_.position AS position_4, c0_.created_at AS created_at_5, c0_.updated_at AS updated_at_6, c0_.id AS id_7, c0_.parent_id AS parent_id_8, c0_.context AS context_9, c0_.media_id AS media_id_10 FROM classification__category c0_ WHERE c0_.id IN (?)
Context: [["7"]]
13:10:34
doctrine	SELECT count(DISTINCT m0_.id) AS sclr_0 FROM media__media m0_ LEFT JOIN classification__category c1_ ON m0_.category_id = c1_.id WHERE m0_.context LIKE ? AND c1_.id IN (?)
Context: ["%People%",[7]]
13:10:34
doctrine	SELECT c0_.name AS name_0, c0_.enabled AS enabled_1, c0_.slug AS slug_2, c0_.description AS description_3, c0_.position AS position_4, c0_.created_at AS created_at_5, c0_.updated_at AS updated_at_6, c0_.id AS id_7, c0_.parent_id AS parent_id_8, c0_.context AS context_9, c0_.media_id AS media_id_10 FROM classification__category c0_
13:10:34
doctrine	SELECT DISTINCT m0_.id AS id_0, m0_.id AS id_1 FROM media__media m0_ LEFT JOIN classification__category c1_ ON m0_.category_id = c1_.id WHERE m0_.context LIKE ? AND c1_.id IN (?) ORDER BY m0_.id ASC
Context: ["%People%",[7]]
13:10:34
doctrine	SELECT m0_.name AS name_0, m0_.description AS description_1, m0_.enabled AS enabled_2, m0_.provider_name AS provider_name_3, m0_.provider_status AS provider_status_4, m0_.provider_reference AS provider_reference_5, m0_.provider_metadata AS provider_metadata_6, m0_.width AS width_7, m0_.height AS height_8, m0_.length AS length_9, m0_.content_type AS content_type_10, m0_.content_size AS content_size_11, m0_.copyright AS copyright_12, m0_.author_name AS author_name_13, m0_.context AS context_14, m0_.cdn_is_flushable AS cdn_is_flushable_15, m0_.cdn_flush_identifier AS cdn_flush_identifier_16, m0_.cdn_flush_at AS cdn_flush_at_17, m0_.cdn_status AS cdn_status_18, m0_.updated_at AS updated_at_19, m0_.created_at AS created_at_20, m0_.id AS id_21, m0_.category_id AS category_id_22 FROM media__media m0_ LEFT JOIN classification__category c1_ ON m0_.category_id = c1_.id WHERE m0_.context LIKE ? AND c1_.id IN (?) ORDER BY m0_.id ASC
Context: ["%People%",[7]]
13:10:34
doctrine	SELECT DISTINCT m0_.id AS id_0, m0_.id AS id_1 FROM media__media m0_ LEFT JOIN classification__category c1_ ON m0_.category_id = c1_.id WHERE m0_.context LIKE ? AND c1_.id IN (?) ORDER BY m0_.id ASC
Context: ["%People%",[7]]
13:10:34
doctrine	SELECT m0_.name AS name_0, m0_.description AS description_1, m0_.enabled AS enabled_2, m0_.provider_name AS provider_name_3, m0_.provider_status AS provider_status_4, m0_.provider_reference AS provider_reference_5, m0_.provider_metadata AS provider_metadata_6, m0_.width AS width_7, m0_.height AS height_8, m0_.length AS length_9, m0_.content_type AS content_type_10, m0_.content_size AS content_size_11, m0_.copyright AS copyright_12, m0_.author_name AS author_name_13, m0_.context AS context_14, m0_.cdn_is_flushable AS cdn_is_flushable_15, m0_.cdn_flush_identifier AS cdn_flush_identifier_16, m0_.cdn_flush_at AS cdn_flush_at_17, m0_.cdn_status AS cdn_status_18, m0_.updated_at AS updated_at_19, m0_.created_at AS created_at_20, m0_.id AS id_21, m0_.category_id AS category_id_22 FROM media__media m0_ LEFT JOIN classification__category c1_ ON m0_.category_id = c1_.id WHERE m0_.context LIKE ? AND c1_.id IN (?) ORDER BY m0_.id ASC
Context: ["%People%",[7]]
`

**Comment by jordisala1991** [comment]
Are you using SonataClassification with SonataMedia?

**Comment by haivala** [comment]
Good that you asked..
Apparently there is now new config for the category_manager.. 

This is my working config for 3.3.1:
`
 sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
         ....
`
I had to add force_disable_category: true for the 3.5.0 to get it working again. This site is already 2 years old and all medias only use the contexts.. maybe there should be check for this? if sonata_media.class.category and sonata_media.category_manager  is not defined... just a quick thought..

**Comment by jordisala1991** [comment]
It could be probably because it was not well configured by default.

SonataClassification (if not disabled or removed) needs all medias to have a category on SonataMedia. AFAIK this applies for SonataMedia > 3.0 atleast.

**Comment by jordisala1991** [comment]
Closing as it is solved. Ping me if it needs to stay opened
