### ISSUE TITLE
Symfony : Sonata Media file preview -not image file

### ISSUE THREAD

**Issue by Mohammadtrabelsi** [sonata-project/SonataMediaBundle#1264]
I need to display a file preview -PDF file- (link to download the file or a link to display it in new tab. I searched a lot without a good solution. this is the fild in configureListFields :

```php
->add('cv', null, array('template' => 'admin:list_image.html.twig'))
```
this is the template twig code :

```twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}
{% block field %}
    <div>
        {% if object.cv != null %}
            <img src="{{ object.cv.path }}">
        {% else %}
            <span>No picture</span>
        {% endif %}
    </div>
{% endblock %}
```

any help please, thanks in advance !

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

**Comment by Mohammadtrabelsi** [comment]
sorry for that !
in any case this is the [solution](https://stackoverflow.com/questions/44561511/symfony-sonata-media-file-preview/44587209#44587209) that i found!
