### ISSUE TITLE
Reduce FileProvider constructor signatur

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataMediaBundle#1303]
The signature of the `FileProvider` is very large, it expects EIGHT parameters. 

Either we should split this class, or we could move some optional parameters to setter methods, e.g. allowed extensions and allowed mime types.

**Comment by greg0ire** [comment]
Or we could use the options resolver component maybe?

**Comment by core23** [comment]
Not sure, if the OptionsResolver is the solution for everything. Especially if we are talking about dependencies / parameters for a class.

**Comment by greg0ire** [comment]
Link for the lazy: https://github.com/sonata-project/SonataMediaBundle/blob/3100b6774d801142b39cab7ca36889def3456650/Provider/FileProvider.php#L43-L53

**Comment by core23** [comment]
The `*Provider` classes have the same problems like the `Admin` classes, they do too much.

**Comment by greg0ire** [comment]
It would indeed only solve 2 params

**Comment by greg0ire** [comment]
The name is a bit vague, so yeah, it probably does too much.

**Comment by VincentLanglet** [comment]
Closing due to lack of interest
