### ISSUE TITLE
Add "getCdn" method to "MediaProviderInterface"

### ISSUE THREAD

**Issue by vyshkant** [sonata-project/SonataMediaBundle#1323]
# The problem

The problem is that `Sonata\MediaBundle\Provider\MediaProviderInterface` doesn't have `getCdn` method, while it's implementation `Sonata\MediaBundle\Provider\BaseProvider` (which is the ancestor of all `SonataMediaBundle`'s providers) does.

This leads to a situation where the method that returns interface `MediaProviderInterface` is used as if it returns class `BaseProvider`.

# Example

For example, `UpdateCdnStatusCommand` contains next line:
```php
$cdn = $this->getMediaPool()->getProvider($media->getProviderName())->getCdn();
```

As we can see, the value returned by `Sonata\MediaBundle\Provider\Pool::getProvider` —
 `MediaProviderInterface` — is used as if it was `BaseProvider`. `MediaProviderInterface` does not have `getCdn` method, `BaseProvider` does.

# Possible solutions

I'm not sure, but I think that `getCdn` method should be added to `MediaProviderInterface`.

**Comment by vyshkant** [comment]
I'll gladly create any PR to solve this issue.

**Comment by greg0ire** [comment]
> I'm not sure, but I think that getCdn method should be added to MediaProviderInterface.

Same as the other issue, a new interface is the way to go. We might merge then in master if it makes sense, but if you want to be BC, you have to do it like this. Please do make a PR, and let me take this as an occasion to thank you again for all the great work you do on Sonata, much appreciated!

**Comment by vyshkant** [comment]
Happy to help!

I think unlike the the other issue, in this case there is no sense to have `MediaProviderInterface` without `getCdn` method (because even now all of its implementations have this method).

So, if I understand correctly and the above assumption is correct, our plan is:

- **for the `master` branch**:  add `getCdn` method to the `MediaProviderInterface`;
- **for the `3.x` branch**: find all usages of `MediaProviderInterface::getCdn` (which in this branch is not yet implemented at the interface level) and check the existence of `getCdn` on `MediaProviderInterface` implementation (and trigger a deprecation error if this method does not exist).

**Comment by greg0ire** [comment]
> find all usages

Looks like there is only one usage where the deprecation is needed: [this one](https://github.com/sonata-project/SonataMediaBundle/blob/c664bbbb428b733e526e54500bd2b668ad883254/src/Command/UpdateCdnStatusCommand.php#L81)

**Comment by OskarStark** [comment]
I would like to hear the opinion of @rande
