### ISSUE TITLE
Math operation with Id throws warning if Id is generated with UUID strategy

### ISSUE THREAD

**Issue by benjaminrau** [sonata-project/SonataMediaBundle#1342]
# The problem
If you use UUID strategy for MediaElement ID property in PHP 7.1 a warning is thrown because a math operation is done with a string value.

The PHP warning:
Warning: A non-numeric value encountered

Version tested: 3.4
Version possible affected: dev-master (affected code didnt change)

# Example
Extend MediaElement with your own one with UUID strategy
```
class MediaElement extends Sonata\MediaBundle\Entity\BaseMedia
{
	/**
	 * @ORM\Id
	 * @ORM\Column(type="guid")
	 * @ORM\GeneratedValue(strategy="UUID")
	 */
	protected $id;
}
```

Use it by changing config.yml
```
sonata_media:
    class:
        media: AppBundle\Entity\MediaElement
```

# Possible solution
Detect if Id is a uuid and use the first two groups for hexadeciaml to decimal conversion. Use the resulting integer for math operation.

Change this code:
https://github.com/sonata-project/SonataMediaBundle/blob/248064b65ea9adac12a33d22d3d49c1910e79e0a/src/Generator/DefaultGenerator.php#L43-L44

To smth like this:
```
$mediaId = $media->getId();
 if (preg_match("/^\{?[a-f\d]{8}-(?:[a-f\d]{4}-){3}[a-f\d]{12}\}?$/i", $mediaId)) {
     $mediaId = (int) hexdec(implode("", array_slice(explode("-", $mediaId), 0, 2)));
}
$rep_first_level = (int) ($mediaId / $this->firstLevel);
$rep_second_level = (int) (($mediaId - ($rep_first_level * $this->firstLevel)) / $this->secondLevel);
```

**Comment by OskarStark** [comment]
Can you please fill the issue template correct and add the used version?

**Comment by benjaminrau** [comment]
@OskarStark i feel sorry that i didnt follow the convensions how to report bugs. could you point me to the issue template? meanwhile i tried to do it like in other issues.

**Comment by bigfoot90** [comment]
Any news on this?

**Comment by Stafox** [comment]
@bigfoot90 I just override default generator service. with the following.
```
use Rhumsaa\Uuid\Uuid;
use Sonata\MediaBundle\Generator\DefaultGenerator;
use Sonata\MediaBundle\Model\MediaInterface;

class UuidGenerator extends DefaultGenerator
{
    public function generatePath(MediaInterface $media)
    {
        $uuid = $media->getId();

        if (!$uuid instanceof Uuid) {
            $uuid = Uuid::fromString($uuid);
        }

        $repFirstLevel = substr($uuid->getClockSequence(), 0, 4);
        $repSecondLevel = substr($uuid->getClockSeqLow(), 0, 2);

        return sprintf('%s/%04s/%02s', $media->getContext(), $repFirstLevel, $repSecondLevel);
    }
}
```

**Comment by bigfoot90** [comment]
not stale

**Comment by core23** [comment]
@bigfoot90 can you provide a PR with a fix?

**Comment by OskarStark** [comment]
One question, if we have a uuid, why can’t we use it as part of the path? I mean can we avoid the hexadecimal grouping stuff? Or are there any benefits I am missing?

**Comment by bigfoot90** [comment]
Found that it just works using `Sonata\MediaBundle\Generator\ODMGenerator`.

For the next MAJOR release the generators should be renamed to a more apropriate names.
In the **meantime** it should be mentioned in the docs that if your domain works with `UUID`s, then `ODMGenerator` should be used even for ORM.

Also found that `ODMGenerator` was not covered by tests, fixed by https://github.com/sonata-project/SonataMediaBundle/pull/1680

**Comment by OskarStark** [comment]
Could you add a PR for with a deprecation and propose a name which fits better? Thanks

**Comment by bigfoot90** [comment]
> Could you add a PR for with a deprecation and propose a name which fits better? Thanks

Sure, I'll make a PR after the merge of the lastest changes on branch `3.x` will be berged into branch `master` and conflicts be solved *(I can make a PR for that too)*.

**Comment by greg0ire** [comment]
The merge will happen automatically tonight (there are no conflicts BTW), but… deprecations should happen on 3.x, that's the whole point of deprecations: helping people migrate in advance.
