### ISSUE TITLE
ClassNotFoundException after following installation instructions, in Symfony 3.4

### ISSUE THREAD

**Issue by spacetraveller** [sonata-project/SonataMediaBundle#1366]
### Environment
Symfony 3.4
PHP 7.1

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.30.0 = 3.30.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.9.0  = 3.9.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  ~ 2.0.1  Cache library
sonata-project/core-bundle               3.8.0  = 3.8.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  = 2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  = 1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.3.0  = 3.3.0  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminB...
sonata-project/easy-extends-bundle       2.3.0  = 2.3.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0  = 1.8.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.4.0  = 3.4.0  Symfony SonataFormatterBundle
sonata-project/media-bundle              3.10.0 = 3.10.0 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.3.0  = 3.3.0  Symfony SonataNotificationBundle

```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.1.2 = v3.1.2 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.2 ~ v4.0.2 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.6.0 = v1.6.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.6.0 = v1.6.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.6.0 = v1.6.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.6.0 = v1.6.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.6.0 = v1.6.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.6.0 = v1.6.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 = v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7 ~ v3.1.6 Symfony SwiftmailerBundle
symfony/symfony            v3.4.2 ~ v4.0.2 The Symfony PHP framework

```

#### PHP version

```
$ php -v
PHP 7.1.11 (cli) (built: Oct 29 2017 17:26:51) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

```

## Subject

Followed instructions on https://sonata-project.org/bundles/media/master/doc/reference/installation.html however, there is an error generated. It appears that Easy Extends may be incorrectly naming the classes for this version of Symfony ?

All the steps through register bundles, routing, configuring doctrine have been performed as in the documentation. Ran php app/console sonata:easy-extends:generate --dest=src SonataMediaBundle

Application\Sonata\MediaBundle\ApplicationSonataMediaBundle() was generated and is referenceable. However, if you browse to the site, this error appears:

(1/1) ClassNotFoundException
Attempted to load class "ApplicationSonataMediaBundle" from namespace "Application\Sonata\MediaBundle".Did you forget a "use" statement for another namespace?
--
in AppKernel.php (line 47)
at AppKernel->registerBundles()in Kernel.php (line 494)
at Kernel->initializeBundles()in Kernel.php (line 134)
at Kernel->boot()in Kernel.php (line 197)
at Kernel->handle(object(Request))in app_dev.php (line 29)

Normally you don't need to add a "use" statement into the AppKernel.php file - the autoloader takes care of that.

## Steps to reproduce

* Install Symfony 3.4
* Install the media bundle and follow instructions on https://sonata-project.org/bundles/media/master/doc/reference/installation.html
* Browse to a page on your website and notice the error message that the ApplicationSonataMediaBundle is not being picked up correctly by AppKernel (assuming autoloader isn't working as it should?)

## Expected results

No error messages and ability to browse normally.

## Actual results

```result

(1/1) ClassNotFoundException
Attempted to load class "ApplicationSonataMediaBundle" from namespace "Application\Sonata\MediaBundle".Did you forget a "use" statement for another namespace?
--
in AppKernel.php (line 47)
at AppKernel->registerBundles()in Kernel.php (line 494)
at Kernel->initializeBundles()in Kernel.php (line 134)
at Kernel->boot()in Kernel.php (line 197)
at Kernel->handle(object(Request))in app_dev.php (line 29)
```

**Comment by kunicmarko20** [comment]
Can you link your `composer.json` autoload? You should have something like this:

```
"autoload": {
    "psr-4": {
        "AppBundle\\": "src/AppBundle",
        "Application\\Sonata\\MediaBundle\\": "src/Application/Sonata/MediaBundle"
     }
}
```

**Comment by spacetraveller** [comment]
Sure. Strangely my composer.json doesn't come with with the second line in the autoload.

`{
    "name": "daniel/cs",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        },
        "files": [
            "vendor/symfony/symfony/src/Symfony/Component/VarDumper/Resources/functions/dump.php"
        ]
    },
    "require": {
        "php": ">=5.5.9",
        "creof/doctrine2-spatial": "^1.2",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-migrations-bundle": "^1.3",
        "doctrine/orm": "^2.5",
        "incenteev/composer-parameter-handler": "^2.0",
        "javiereguiluz/easyadmin-bundle": "^1.17",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^3.0.2",
        "sonata-project/admin-bundle": "^3.28",
        "sonata-project/doctrine-orm-admin-bundle": "^3.2",
        "sonata-project/formatter-bundle": "^3.4",
        "sonata-project/media-bundle": "^3.10",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.*",
        "twig/twig": "^1.0||^2.0"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^2.4",
        "hautelook/alice-bundle": "^1.4",
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "sort-packages": true
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": null
    }
}
`

**Comment by kunicmarko20** [comment]
That is why it is not working, your composer detects only the AppBundle, add that second line and it should work.

**Comment by jordisala1991** [comment]
Thats the problem. This can be closed
