### ISSUE TITLE
Gallery delete medias after change medias position or adding/deleting medias

### ISSUE THREAD

**Issue by amadohin** [sonata-project/SonataMediaBundle#1380]
I don't know why this is happening.

When I try to update medias position in a gallery or if I add/delete a new media, the gallery deletes current medias.

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help

Please use the issue template when reporting bugs

**Comment by kunicmarko20** [comment]
Can this be related https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/789 ?

**Comment by jordisala1991** [comment]
It is, let's continue the discussion there
