### ISSUE TITLE
API controllers are not compatible with NelmioApiDocBundle

### ISSUE THREAD

**Issue by juansss** [sonata-project/SonataMediaBundle#1390]
There is a problem using NelmioApiDocBundle v3.X. (old annotations in SonataMediaBundle Api controllers)

`[Doctrine\Common\Annotations\AnnotationException]                            
  [Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc"   
  in method Sonata\MediaBundle\Controller\Api\GalleryController::getGalleries  
  Action() does not exist, or could not be auto-loaded`

Any suggestions in order to work around this issue? My project is using NelmioApiDocBundle v3.X already.

**Comment by jordisala1991** [comment]
We are not blocking installs of Nelmio 3.x, so this could happen.

The upgrade guide from 2.x to 3.x if anyone is interested: https://github.com/nelmio/NelmioApiDocBundle/blob/master/UPGRADE-3.0.md

Doesn't seem easy to upgrade without dropping 2.x

**Comment by kunicmarko20** [comment]
I do not see a way we could support 2.x and 3.x, if we upgrade to 3.x it would be a bc break, right? Maybe we can do this on next majors

**Comment by juansss** [comment]
@jordisala1991  thanks for the quick response. But you cant upgrade to 3.x if you have this SonataMediaBundle installed.
I don't have any controllers with Api Doc annotations and i still getting this error 

`[Doctrine\Common\Annotations\AnnotationException]                            
  [Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc"   
  in method Sonata\MediaBundle\Controller\Api\GalleryController::getGalleries  
  Action() does not exist, or could not be auto-loaded.  `

**Comment by juansss** [comment]
@kunicmarko20  yes you are right.  Or maybe stop using the bundle for your 2 api controllers? NelmioApiDoc 3.x was released 9 month ago

**Comment by jordisala1991** [comment]
Probably not on your code, but it is on sonata code: https://github.com/sonata-project/SonataMediaBundle/blob/3.x/src/Controller/Api/GalleryController.php#L76

That's why it is good to have a conflict section with an upper limit.
It is not a BC break to drop compatibility for a version of a dependency, unless it have implications on the signatures of our methods.

**Comment by kunicmarko20** [comment]
So, what are our options? Drop nelmio api? Upgrade to 3.x? Add upper limit?

**Comment by jordisala1991** [comment]
IMO add upper limit is the easy thing to do. Then we can think about dropping 2 and implement 3 on stable or on master.

**Comment by kunicmarko20** [comment]
I am more for master, because if anyone is using 2.x and we upgrade on stable we will have this same issue.

**Comment by tomcoonen** [comment]
Any clarity on the solution that will fit best? I guess 4.x will support Nelmio Api 3.x/SwaggerPHP?
Might be able to create a PR as soon we can agree on the fix? :)

**Comment by kunicmarko20** [comment]
probably, 4.x would depend on Nelmio 3.x, PR should be made on master then, cc @jordisala1991 you agree or should we include more people as we would then need to drop 2.x everywhere we have nelmio support

**Comment by tomcoonen** [comment]
@kunicmarko20 @jordisala1991 Any opinions here? :)

**Comment by jordisala1991** [comment]
I guess every package should move to 3.x of nelmio on master. Lets see one PR because probably the rest are similar
