### ISSUE TITLE
The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc" not found

### ISSUE THREAD

**Issue by Webonaute** [sonata-project/SonataMediaBundle#1406]
Usage of nelmio/api-doc-bundle in require-dev make application fatal error if dev stuff is not installed because annotation is use in lot of class. 

```
[stderr] php bin/console cache:clear --env=test
[stdout]
[stdout] // Clearing the cache for the beta environment with debug                      
[stdout] // true                                                                        
[stdout]
[stderr]
[stderr]In AnnotationException.php line 54:
[stderr]                                                                               
[stderr]  [Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc"   
[stderr]  in method Sonata\MediaBundle\Controller\Api\GalleryController::getGalleries  
[stderr]  Action() does not exist, or could not be auto-loaded
```

**Comment by greg0ire** [comment]
Can you try with `-vvv`, so that we get the whole stack trace for this?

**Comment by Webonaute** [comment]
I already fix the issue by including temporary nelmio/api-doc-bundle ^2.0 in my own composer. 
but its really easy to reproduce. 

# `composer install --no-dev`
# `php bin/console cache:clear --env=test`

if you go in GalleryController::getGalleries method, you will find 
`     * @ApiDoc(
     *  resource=true,
     *  output={"class"="Sonata\DatagridBundle\Pager\PagerInterface", "groups"={"sonata_api_read"}}
     * )`

Which is the source of the issue as ApiDoc doesn't exist. --require-dev should not have mandatory package. nelmio/api-doc-bundle need to be dropped from the code OR added into require section to fix permanently the issue.

**Comment by greg0ire** [comment]
Is it though? I'd rather expect it to be ignored in production, that's why I'm asking for a stack trace, I'd like to know why it is analyzed at all.

**Comment by jordisala1991** [comment]
nelmio is not required if you don't use the api controllers.

Are you using something like jms-di-extra-bundle? There are some issues about that already on sonata.

Closing.
