### ISSUE TITLE
[RFC] Multiupload Type

### ISSUE THREAD

**Issue by silasjoisten** [sonata-project/SonataMediaBundle#1422]
Hey there,
i created in my project a good solution for a MultiUploadType in SonataMediaBundle.
i can contribute it but first i want to know if there is any need for?

![multiupload](https://user-images.githubusercontent.com/10114981/39349194-5de1e534-49fa-11e8-95b9-224b0b1a9f6e.gif)

Used libs:
* [dmUploader - jQuery Ajax File Uploader Widget](https://github.com/danielm/uploader)

**Comment by kunicmarko20** [comment]
I am not sure we need/want another js lib, maybe create it as your bundle and we include it docs? Let's see what others think.

**Comment by kunicmarko20** [comment]
But it does look good 😄

**Comment by kunicmarko20** [comment]
cc @sonata-project/contributors

**Comment by jordisala1991** [comment]
Related issue: https://github.com/sonata-project/SonataMediaBundle/issues/535

Will close the other one, since it is from 2014

**Comment by jordisala1991** [comment]
Also related to this: https://github.com/sonata-project/SonataMediaBundle/pull/1105

**Comment by kunicmarko20** [comment]
that one is adding additional js lib again and abandoned, I would rather have it as a separate bundle with like a form type or w/e. Is my thinking wrong about it?

**Comment by jordisala1991** [comment]
Im just linking related things so we dont lose information, but I agree with you, it is probably too much to have it inside the MediaBundle. It would be nice to see it working outside Media and then decide if it is worth to integrate it directly

**Comment by greg0ire** [comment]
Yes, plus we can add it to the `suggest` section just like we did for the workflow bundle

**Comment by silasjoisten** [comment]
Okay i will start writing a seperate bundle.

**Comment by silasjoisten** [comment]
https://github.com/silasjoisten/sonata-multiupload-bundle

it is not done yet some things are mission like:
* Tests
* Travis Setup
* FlintCI Setup

 but anyway please share your thoughts and tell me if i am not on the correct way 😄

**Comment by OskarStark** [comment]
Thank you 🙏
