### ISSUE TITLE
Missing type hints in class FormatterMediaExtension.php

### ISSUE THREAD

**Issue by jmontoyaa** [sonata-project/SonataMediaBundle#1444]
File:

https://github.com/sonata-project/SonataMediaBundle/edit/master/src/Twig/Extension/FormatterMediaExtension.php

Should be compatible with the class BaseProxyExtension.php which is not the case currently:

https://github.com/sonata-project/SonataFormatterBundle/blob/master/src/Extension/BaseProxyExtension.php

I tried to fix it but this issue seems a bit more complex because I have this service,
and it means changing the `sonata.media.formatter.twig' ...

```xml
<service id="sonata.media.formatter.twig" class="Sonata\MediaBundle\Twig\Extension\FormatterMediaExtension" public="true">
    <argument type="service" id="sonata.media.twig.extension"/>
</service>
```

**Comment by OskarStark** [comment]
@jmontoyaa could you provide a PR which fixes the issue?
