### ISSUE TITLE
Gaufrette v0.6

### ISSUE THREAD

**Issue by abysKri** [sonata-project/SonataMediaBundle#1449]
## Feature Request
Can you add gaufrette 0.6 in composer file
Install generate a configuration conflict
Thanks
> Problem 1
>     - sonata-project/media-bundle 3.13.1 requires knplabs/gaufrette ^0.3 || ^0.4 || ^0.5 -> satisfiable by knplabs/gaufrette[v0.3, v0.3.1, v0.4.0, v0.5.0] but these conflict with your requirements or minimum-stability.
>     - sonata-project/media-bundle 3.13.0 requires knplabs/gaufrette ^0.3 || ^0.4 || ^0.5 -> satisfiable by knplabs/gaufrette[v0.3, v0.3.1, v0.4.0, v0.5.0] but these conflict with your requirements or minimum-stability.
>     - Installation request for sonata-project/media-bundle ^3.13 -> satisfiable by sonata-project/media-bundle[3.13.0, 3.13.1].

**Comment by greg0ire** [comment]
It's there already, see 39b1bbbe934fc602d94b8e2d2ff3fc66c904cee9 . The actual issue is we miss a new release. Expect it by tonight.

**Comment by greg0ire** [comment]
https://github.com/sonata-project/SonataMediaBundle/releases/tag/3.14.0
