### ISSUE TITLE
"NEXT_MAJOR: remove default filter" visible in twig template

### ISSUE THREAD

**Issue by jorenvh1** [sonata-project/SonataMediaBundle#1462]
Hi there,

I updated the bundle to 3.15.0 and now when I browse to 'Media' and when I want to upload an image, the text: "NEXT_MAJOR: remove default filter" is visible inside the twig template instead of it being commented...

I'm pretty sure this is not intended?

<img width="730" alt="screen shot 2018-08-21 at 10 46 23" src="https://user-images.githubusercontent.com/14889143/44391186-7a60a480-a52f-11e8-9fe1-6ee17541177b.png">

**Comment by OskarStark** [comment]
Good catch :)

**Comment by jorenvh1** [comment]
I think it might be in other templates too, not sure though

**Comment by OskarStark** [comment]
hmm I searched the MediaBundle and can't find anything:
![screenshot 2018-08-21 10 49 41](https://user-images.githubusercontent.com/995707/44391406-08d52600-a530-11e8-942d-6daac2dbf792.png)

**Comment by kunicmarko20** [comment]
@OskarStark templates are in the AdminBundle

**Comment by OskarStark** [comment]
damn right 👍

**Comment by OskarStark** [comment]
Yes, and fix both tickets via PR, but i can't find it in the admin-bundle, either 🤔

**Comment by jorenvh1** [comment]
I think you're right, I think I messed something up during the composer install... i'm sorry for this none issue!
