### ISSUE TITLE
Controllers Should Not Be Referenced With Single Colon Syntax

### ISSUE THREAD

**Issue by kiler129** [sonata-project/SonataMediaBundle#1472]
## Feature Request
Symfony 4.1 deprecates bundle notation (e.g. `SonataAdminBundle:CRUS:export`) - https://symfony.com/blog/new-in-symfony-4-1-deprecated-the-bundle-notation. The change causes a lot of `E_USER_DEPRECATED`:
![image](https://user-images.githubusercontent.com/1227834/45324657-60a1f400-b514-11e8-8ebd-d4fcb7f00f87.png)

While it doesn't break anything it will be good to fix this by simply replacing `:` with `::` when controllers are references.
This is a similar issue to e.g. https://github.com/sonata-project/SonataAdminBundle/issues/5227

I'm not that famillar with Sonata codebase, but changing it in:
 - `src/Resources/config/routing/media.xml`
 - `src/Resources/config/routing/gallery.xml`

seems to fix the problem.

**Comment by OskarStark** [comment]
Looks good to me, can you provide a PR with your proposal so that we can see if everything is green on Travis?

**Comment by phansys** [comment]
These changes were made at #1603.
Thank you @kiler129.
