### ISSUE TITLE
Composer take 80s and 2Go to read sonata-project/media-bundle json file

### ISSUE THREAD

**Issue by cocolabssas** [sonata-project/SonataMediaBundle#1482]
Hello,

Composer takes a long time (~80s)  and a lot of memory(~2G) to only read sonata-project$media-bundle.json file from cache.

Here is the output of ` composer update --profile -vvv:`

```
...
[453.5MB/19.15s] Reading C:/Users/me/AppData/Local/Composer/repo/https---repo.packagist.org/provider-symfony$messenger.json from cache

[2362.9MB/103.15s] Reading C:/Users/me/AppData/Local/Composer/repo/https---repo.packagist.org/provider-sonata-project$media-bundle.json from cache

[2390.0MB/103.62s] Reading C:/Users/me/AppData/Local/Composer/repo/https---repo.packagist.org/provider-friendsofsymfony$rest-bundle.json from cache
...
```

In the composer.lock there is only one occurence of sonata-project/media-bundle in a conflict section of sonata-admin bundle:

```
...
,{
            "name": "sonata-project/admin-bundle",
            "version": "3.40.2",
            "source": {
                "type": "git",
                "url": "https://github.com/sonata-project/SonataAdminBundle.git",
                "reference": "0994f416bf85de1f83f9d657f9e578dd1eb0ca81"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/sonata-project/SonataAdminBundle/zipball/0994f416bf85de1f83f9d657f9e578dd1eb0ca81",
                "reference": "0994f416bf85de1f83f9d657f9e578dd1eb0ca81",
                "shasum": ""
            },
            "require": {
                "doctrine/common": "^2.7",
                "doctrine/inflector": "^1.1",
                "knplabs/knp-menu-bundle": "^2.2",
                "php": "^5.6 || ^7.0",
                "sonata-project/block-bundle": "^3.11",
                "sonata-project/core-bundle": "^3.9",
                "sonata-project/exporter": "^1.8",
                "symfony/asset": "^2.8 || ^3.2 || ^4.0",
                "symfony/config": "^2.8 || ^3.2 || ^4.0",
                "symfony/console": "^2.8 || ^3.2 || ^4.0",
                "symfony/dependency-injection": "^2.8 || ^3.2 || ^4.0",
                "symfony/event-dispatcher": "^2.8 || ^3.2 || ^4.0",
                "symfony/expression-language": "^2.8 || ^3.2 || ^4.0",
                "symfony/form": "^2.8 || ^3.2 || ^4.0",
                "symfony/framework-bundle": "^2.8 || ^3.2 || ^4.0",
                "symfony/http-foundation": "^2.8 || ^3.2 || ^4.0",
                "symfony/http-kernel": "^2.8 || ^3.2 || ^4.0",
                "symfony/options-resolver": "^2.8 || ^3.2 || ^4.0",
                "symfony/property-access": "^2.8 || ^3.2 || ^4.0",
                "symfony/routing": "^2.8 || ^3.2 || ^4.0",
                "symfony/security-acl": "^2.8 || ^3.0",
                "symfony/security-bundle": "^2.8 || ^3.2 || ^4.0",
                "symfony/security-core": "^2.8 || ^3.2 || ^4.0",
                "symfony/security-csrf": "^2.8 || ^3.2 || ^4.0",
                "symfony/templating": "^2.8 || ^3.2 || ^4.0",
                "symfony/translation": "^2.8 || ^3.2 || ^4.0",
                "symfony/twig-bridge": "^2.8 || ^3.2 || ^4.0",
                "symfony/twig-bundle": "^2.8 || ^3.2 || ^4.0",
                "symfony/validator": "^2.8 || ^3.2 || ^4.0",
                "twig/extensions": "^1.5",
                "twig/twig": "^1.34 || ^2.0"
            },
            "conflict": {
                "jms/di-extra-bundle": "<1.9",
                "sonata-project/media-bundle": "<3.7",
                "sonata-project/user-bundle": "<3.3"
            },
            "require-dev": {
                "jms/di-extra-bundle": "^1.9",
                "jms/translation-bundle": "^1.4",
                "matthiasnoback/symfony-dependency-injection-test": "^1.1",
                "sensio/generator-bundle": "^3.1",
                "sonata-project/intl-bundle": "^2.4",
                "symfony/class-loader": "^2.8 || ^3.2",
                "symfony/filesystem": "^2.8 || ^3.2 || ^4.0",
                "symfony/phpunit-bridge": "^4.0",
                "symfony/yaml": "^2.8 || ^3.2 || ^4.0"
            },
            "suggest": {
                "jms/di-extra-bundle": "Annotations for Admin definition",
                "jms/translation-bundle": "Extract message keys from Admins",
                "sensio/generator-bundle": "Add sonata:admin:generate command",
                "sonata-project/intl-bundle": "Add localized date and number into the list"
            },
            "type": "symfony-bundle",
            "extra": {
                "branch-alias": {
                    "dev-master": "3.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Sonata\\AdminBundle\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Sonata Community",
                    "homepage": "https://github.com/sonata-project/SonataAdminBundle/contributors"
                },
                {
                    "name": "Thomas Rabaix",
                    "email": "thomas.rabaix@sonata-project.org",
                    "homepage": "https://sonata-project.org"
                }
            ],
            "description": "The missing Symfony Admin Generator",
            "homepage": "https://sonata-project.org/bundles/admin",
            "keywords": [
                "Admin Generator",
                "admin",
                "bootstrap",
                "sonata"
            ],
            "time": "2018-10-17T08:36:10+00:00"
        },
...
```
What can be done to not lost this time each time a composer update is done?

### Environment
LAMP
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```
sonata-project/admin-bundle              3.39.0               3.40.2               The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1               3.12.1               Symfony SonataBlockBundle
sonata-project/cache                     2.0.1                2.0.1                Cache library
sonata-project/core-bundle               3.11.2               3.11.2               Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1                2.4.0                Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2                1.1.0                Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.1                3.6.2                Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0                2.5.0                Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.9.1                1.9.1                Lightweight Exporter library
sonata-project/intl-bundle               2.5.0                2.5.0                Symfony SonataIntlBundle

#### Symfony packages

```
$ composer show --latest 'symfony/*'
# Put the result here.
```
symfony/monolog-bundle     v3.3.0  v3.3.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.15 v4.1.6 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.9.0  v1.9.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.9.0  v1.9.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.9.0  v1.9.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.9.0  v1.9.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.9.0  v1.9.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.9.0  v1.9.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.9.0  v1.9.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.2.3  v3.2.3 Symfony SwiftmailerBundle
symfony/symfony            v3.4.15 v4.1.6 The Symfony PHP framework

#### PHP version

```
$ php -v
# Put the result here.
```
PHP 7.1.12 (cli) (built: Dec 18 2017 14:02:37) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

## Subject

Composer take 80s and 2Go to read sonata-project/media-bundle json file

## Steps to reproduce
composer update

## Expected results
Few seconds to read bundle dependencies

## Actual results
80s instead

**Comment by phansys** [comment]
The dependency solving is not a responsibility of this package, but a Composer one.
Whatever, I'm not able to confirm what is reported on this issue. Maybe it was just a problem with the used composer version.
```
composer --version
Composer version 1.8.6 2019-06-11 15:03:05
composer update --profile -vvv | grep "media-bundle"
[162.3MiB/0.90s] Reading /tmp/.composer/cache/repo/https---repo.packagist.org/provider-sonata-project$media-bundle.json from cache
```
I'm closing the issue because the given reasons.
