### ISSUE TITLE
Full filename reference in the database

### ISSUE THREAD

**Issue by jarkt** [sonata-project/SonataMediaBundle#1484]
## Feature Request

In other projects where I used Amazon S3 I've used the same S3 Bucket for production and development.
There was a prefix with environment (prod or dev) and custom name (stage, live or name of the developer).
Developers are restricted to their own folder.
The advantage is that I can copy the production database to the development system without caring about the uploads.
Existing uploads from the production system are referenced from the folder with the respective prefix while new uploads from the development system are seperated in a custom folder. Deletions from the development system that reference a production upload are not performed and it would also not possible because of the user restrictions.

Such a configuration is currently not possible with sonata media bundle, because the filenames are build dynamically from the dataset ID and the configuration. I would need a full reference to the filename with their full path to realize it.

Maybe this could be respected for future releases.

**Comment by cussack** [comment]
I‘m pretty sure you can achieve that with the LiipImagineBundle and a custom cache resolver. Did you give this a try? https://symfony.com/doc/2.0/bundles/LiipImagineBundle/cache-resolvers.html#custom-cache-resolver

**Comment by jarkt** [comment]
I can't imagine how it should help. But I do not work with sonata anymore, so I don't need a solution for that.
