### ISSUE TITLE
Handling PHP 7.3 support and KnpLabs/Gaufrette

### ISSUE THREAD

**Issue by IwfY** [sonata-project/SonataMediaBundle#1509]
Though not explicitely stated through composer requirements, KnpLabs/Gaufrette 0.7 doesn't support PHP 7.3. Version 0.8 supports PHP 7.3 but drops support for every version before PHP 7.1.

So how is supposed to be handled by the Media bundle?

Would it be okay to just allow KnpLabs/Gaufrette ^0.8 or would this mean that support for older PHP version had to be dropped as well?

**Comment by kunicmarko20** [comment]
Just adding `|| ^.08` should be enough. Just compared 0.7 to 0.8 and there are no BC Breaks, rest will be resolved by composer based on your system php version

**Comment by kunicmarko20** [comment]
@IwfY could you provide a PR?

**Comment by IwfY** [comment]
Done.
