### ISSUE TITLE
Upload mp4 file

### ISSUE THREAD

**Issue by uka127** [sonata-project/SonataMediaBundle#1573]
Hi,

I have a problem, because I wanted to upload to the server mp4 file, but not using Youtube, Dailymotion and Vimeo. I would like to upload it like a image or file.

Can someone tell me how can I do it?

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
