### ISSUE TITLE
 Remove id from model classes

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataMediaBundle#1577]
## Feature Request

The id should not be part of the model classes. The outside world shouldn't know anything about the technical details. Depending on the user application, the id could be a string, uuid or an integer.

Classes:
- `Model\Media(Interface)`

**Comment by jordisala1991** [comment]
Even though it would be nice to remove it, it is not an easy-pick. `getId()` is used in a lot of places for all models.

IMO it shouldn't  matter if we define the getter, but it would be nice to be able to use whatever we want. That however requires tackle the uuid thing (already with an issue on the admin bundle https://github.com/sonata-project/SonataAdminBundle/issues/7327 .

Im closing it for now. If you think with my arguments this is still relevant, please reopen.
