### ISSUE TITLE
Can't download dailymotion videos using the complete URL

### ISSUE THREAD

**Issue by dongido001** [sonata-project/SonataMediaBundle#1588]
When I try to add a Dailymotion video using the complete URL (like - https://www.dailymotion.com/video/x32w0hb), I get an error:

<img width="1437" alt="Screenshot 2019-05-02 at 4 24 48 PM" src="https://user-images.githubusercontent.com/18917158/57086924-f46c3e80-6cf6-11e9-981f-d8c05b6396c7.png">

But when I use the video ID instead (x32w0hb), it works:

<img width="1397" alt="Screenshot 2019-05-02 at 4 25 20 PM" src="https://user-images.githubusercontent.com/18917158/57087345-bd4a5d00-6cf7-11e9-9098-b9e3d67bb59e.png">

#### PHP version
7.2

PS: The complete URL works for YouTube and Vimeo

**Comment by core23** [comment]
Can you provide a PR which supports both inputs?

**Comment by dongido001** [comment]
Sure @core23

**Comment by dongido001** [comment]
Closing as this is already fixed in v3.19 by PR #1480. I was using v3.15.

**Comment by BigShanJohn** [comment]
I dont know what is wrong, both the url and the id is not working for me on dailymotion videos only, other files type is uploading
