### ISSUE TITLE
Multiple file uploading in sonata Admin using Sonata Media Bundle step by step or complete example

### ISSUE THREAD

**Issue by khushal7764** [sonata-project/SonataMediaBundle#1599]
hello 
i want to implement multiple file uploading in sonata admin using sonata media bundle and i am fresher in symfony. so , i dont have any idea about it 
so please provide me complete example or step by step implementation
Please help me 
Thanks

**Comment by silasjoisten** [comment]
I made something like that if you want to use it or contribute feel free: https://github.com/silasjoisten/sonata-multiupload-bundle
