### ISSUE TITLE
GalleryItemInterface references Non-Existing Interface

### ISSUE THREAD

**Issue by th-lange** [sonata-project/SonataMediaBundle#1600]
The file:
/src/Model/GalleryMediaCollectionInterface.php

references the interface: 'GalleryItemInterface'. But this interface no longer exists...
```php
namespace Sonata\MediaBundle\Model;

/**
 * This a workaround to maintain BC within SonataMediaBundle v3.
 * NEXT_MAJOR: remove this interface, move all methods into GalleryInterface.
 */
interface GalleryMediaCollectionInterface
{
    public function addGalleryHasMedia(GalleryItemInterface $galleryHasMedia);

    public function removeGalleryHasMedia(GalleryItemInterface $galleryHasMedia);
}

```

**Comment by core23** [comment]
Please fill out the issue template, otherwise we cannot help you

**Comment by th-lange** [comment]
"Cannot" or "will not".

I think:

The file `GalleryMediaCollectionInterface` references `GalleryItemInterface` which no longer exists is pretty obvious.

Nervermind. I will just fork and use that instead...

**Comment by kunicmarko20** [comment]
@th-lange we have an issues template for a reason, it gives us information that we need to help you. Everyone has to fill it, why would you be an exception to everyone else? If you want help, please follow the rules.

**Comment by th-lange** [comment]
https://github.com/sonata-project/SonataMediaBundle/pull/1601

**Comment by th-lange** [comment]
Yeah. I know.

I think this is important in many cases. I totally get it. But I think there are cases in which those are overkill. 

So I just changed it on a fork. And send you a pr. 

Because actually I need the change nowisch... 
So what you do with it and whether you deem the 20 lines of "why" worth the 2 words changes worth it is up to you....
