### ISSUE TITLE
Extract FileProviderInterface from FileProvider

### ISSUE THREAD

**Issue by tominventisbe** [sonata-project/SonataMediaBundle#1638]
## Feature Request

The `FileProvider` currently extends `BaseProvider`, but exposes additional methods in its public API beyond those from `MediaProviderInterface`, such as `getAllowedExtensions` and `getAllowedMimeTypes`, which are not part of any interface.

This hampers decoration as no interface provides these methods. Instead, one must either check for an instance of `FileProvider`, forcing you to extend rather than decorate, or use `method_exists`, which is suboptimal as well.

Would it be possible to extract a `FileProviderInterface` that extends `MediaProviderInterface` and contains these additional methods?

**Comment by core23** [comment]
Can you do this @tominventisbe ?

**Comment by tominventisbe** [comment]
@core23 Done in #1639.
