### ISSUE TITLE
Admin service "sonata.media.admin.media" not found in admin pool

### ISSUE THREAD

**Issue by tonyellow** [sonata-project/SonataMediaBundle#1657]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
sonata-project/admin-bundle              3.56.1 3.56.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.18.2 4.0.0  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/classification-bundle     3.9.2  3.9.2  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.17.2 3.17.2 Symfony SonataCoreBundle (abandoned)
sonata-project/datagrid-bundle           2.5.0  3.0.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.4.0  1.4.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.12.0 3.12.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library
sonata-project/intl-bundle               2.7.0  2.7.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.21.0 3.21.0 Symfony SonataMediaBundle
sonata-project/translation-bundle        2.4.2  2.4.2  SonataTranslationBundle
sonata-project/user-bundle               4.5.1  4.5.1  Symfony SonataUserBundle

#### Symfony packages

```
$ composer show --latest 'symfony/*'
# Put the result here.
symfony/asset                      v4.3.9  v4.3.9  Symfony Asset Component
symfony/cache                      v4.3.9  v4.3.9  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v1.1.7  v2.0.1  Generic abstractions related to caching
symfony/config                     v4.3.9  v4.3.9  Symfony Config Component
symfony/console                    v4.3.9  v4.3.9  Symfony Console Component
symfony/debug                      v4.3.9  v4.3.9  Symfony Debug Component
symfony/dependency-injection       v4.3.9  v4.3.9  Symfony DependencyInjection Component
symfony/doctrine-bridge            v4.3.9  v4.3.9  Symfony Doctrine Bridge
symfony/dotenv                     v4.3.9  v4.3.9  Registers environment variables from a .env file
symfony/event-dispatcher           v4.3.9  v4.3.9  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.7  v2.0.1  Generic abstractions related to dispatching event
symfony/expression-language        v4.3.9  v4.3.9  Symfony ExpressionLanguage Component
symfony/filesystem                 v4.3.9  v4.3.9  Symfony Filesystem Component
symfony/finder                     v4.3.9  v4.3.9  Symfony Finder Component
symfony/flex                       v1.6.0  v1.6.0  Composer plugin for Symfony
symfony/form                       v4.3.9  v4.3.9  Symfony Form Component
symfony/framework-bundle           v4.3.9  v4.3.9  Symfony FrameworkBundle
symfony/http-client                v4.3.9  v4.3.9  Symfony HttpClient component
symfony/http-client-contracts      v1.1.8  v2.0.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.3.9  v4.3.9  Symfony HttpFoundation Component
symfony/http-kernel                v4.3.9  v4.3.9  Symfony HttpKernel Component
symfony/inflector                  v4.3.9  v4.3.9  Symfony Inflector Component
symfony/intl                       v4.3.9  v4.3.9  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle               v1.14.3 v1.14.3 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mercure                    v0.3.0  v0.3.0  Symfony Mercure Component
symfony/mercure-bundle             0.2.3   0.2.3   Symfony MercureBundle
symfony/mime                       v4.3.9  v4.3.9  A library to manipulate MIME messages
symfony/options-resolver           v4.3.9  v4.3.9  Symfony OptionsResolver Component
symfony/polyfill-intl-icu          v1.13.1 v1.13.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.13.1 v1.13.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring          v1.13.1 v1.13.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.13.1 v1.13.1 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.13.1 v1.13.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                    v4.3.9  v4.3.9  Symfony Process Component
symfony/profiler-pack              v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access            v4.3.9  v4.3.9  Symfony PropertyAccess Component
symfony/property-info              v4.3.9  v4.3.9  Symfony Property Info Component
symfony/routing                    v4.3.9  v4.3.9  Symfony Routing Component
symfony/security-acl               v3.0.4  v3.0.4  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.3.9  v4.3.9  Symfony SecurityBundle
symfony/security-core              v4.3.9  v4.3.9  Symfony Security Component - Core Library
symfony/security-csrf              v4.3.9  v4.3.9  Symfony Security Component - CSRF Library
symfony/security-guard             v4.3.9  v4.3.9  Symfony Security Component - Guard
symfony/security-http              v4.3.9  v4.3.9  Symfony Security Component - HTTP Integration
symfony/serializer                 v4.3.9  v4.3.9  Symfony Serializer Component
symfony/service-contracts          v1.1.8  v2.0.1  Generic abstractions related to writing services
symfony/stopwatch                  v4.3.9  v4.3.9  Symfony Stopwatch Component
symfony/swiftmailer-bundle         v3.4.0  v3.4.0  Symfony SwiftmailerBundle
symfony/templating                 v4.3.9  v4.3.9  Symfony Templating Component
symfony/translation                v4.3.9  v4.3.9  Symfony Translation Component
symfony/translation-contracts      v1.1.7  v2.0.1  Generic abstractions related to translation
symfony/twig-bridge                v4.3.9  v4.3.9  Symfony Twig Bridge
symfony/twig-bundle                v4.3.9  v4.3.9  Symfony TwigBundle
symfony/validator                  v4.3.9  v4.3.9  Symfony Validator Component
symfony/var-dumper                 v4.3.9  v4.3.9  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v4.3.9  v4.3.9  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                   v4.3.9  v4.3.9  Symfony WebLink Component
symfony/web-profiler-bundle        v4.3.9  v4.3.9  Symfony WebProfilerBundle
symfony/workflow                   v4.3.9  v4.3.9  Symfony Workflow Component
symfony/yaml                       v4.3.9  v4.3.9  Symfony Yaml Component

## Subject
Im trying to get the media bundle to work but im having a hard time with symfony 4. I'm getting the below error while adding media_widgets.html.twig to twig.yaml. I hope somebody can have a look at it.

An exception has been thrown during the rendering of a template ("Admin service "sonata.media.admin.media" not found in admin pool. Did you mean "sonata.user.admin.group" or one of those: []?") in "@SonataMedia/Form/media_widgets.html.twig".

## Steps to reproduce

add         - '@SonataMedia/Form/media_widgets.html.twig' to twig.yaml

twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'
        - '@SonataMedia/Form/media_widgets.html.twig'

## Expected results
Media upload form

## Actual results
error

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
