### ISSUE TITLE
Remove SonataCoreBundle dependency

### ISSUE THREAD

**Issue by garak** [sonata-project/SonataMediaBundle#1694]
As stated on [its README](https://github.com/sonata-project/SonataCoreBundle/blob/3.x/README.md), SonataCoreBundle is deprecated.
As a consequence, issues in that bundle are ignored (there are also some unpatched vulnerabilities)

This bundle should not rely on SonataCoreBundle anymore

**Comment by core23** [comment]
Can you help to remove the CoreBundle here @garak ?

**Comment by OskarStark** [comment]
> As a consequence, issues in thad bundle are ignored (there are also some unpatched vulnerabilities)

Which one?

**Comment by garak** [comment]
This one https://github.com/sonata-project/SonataCoreBundle/issues/724

**Comment by OskarStark** [comment]
As explained we does not use Version 3 of jQuery

**Comment by phansys** [comment]
@garak, I've updated the title in order to use this issue to track the desired result.

**Comment by wbloszyk** [comment]
@phansys Can u add `[deprecated]` notes in SonataCoreBundle repository description?

**Comment by wbloszyk** [comment]
Can be close. It done in #1744
