### ISSUE TITLE
DateTimes should be type-hinted as DateTimeInterface

### ISSUE THREAD

**Issue by garak** [sonata-project/SonataMediaBundle#1710]
## Feature Request

Currently, properties containing a date (or a datetime) are type-hintend in phpdoc with `DateTime`.
Since Doctrine also allows to map properties with `DateTimeImmutable`, such properties should be type-hinted with `DateTimeInterface`.

See for example https://github.com/sonata-project/SonataMediaBundle/blob/3.x/src/Model/Media.php#L103

**Comment by garak** [comment]
Still valid

**Comment by core23** [comment]
Feel free to provide a PR with a fix

**Comment by jordisala1991** [comment]
Done already
