### ISSUE TITLE
Allow usage of Twig's "truncate" filter from "twig/string-extra"

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataMediaBundle#1725]
## Feature Request
Allow to optionally use Twig's `truncate` filter from "twig/string-extra", which should be the default (and the only) implementation in the next major.
At first sight, there are [only 3 occurrences](https://github.com/search?q=truncate+repo%3Asonata-project%2FSonataMediaBundle+language%3ATwig&type=Code&ref=advsearch&l=Twig) at the current codebase.

The same task was already made for the AdminBundle at sonata-project/SonataAdminBundle#5983.

**Comment by wbloszyk** [comment]
This is done in https://github.com/sonata-project/SonataMediaBundle/pull/1756

Can we close it? @phansys

**Comment by phansys** [comment]
>Can we close it? @phansys

Sure! Closing.
