### ISSUE TITLE
Error when adding a youtube media: "This value should not be null"

### ISSUE THREAD

**Issue by RobMasters** [sonata-project/SonataMediaBundle#173]
I'm just trying to create a new Media through the admin interface, and always get an error at the top of the page saying "An error has occurred during item creation." and then "This value should not be null" as the form error. I'm using a default setup of the media and admin bundles (both at branch origin/2.0).

The form only has a single, required input (File *) and I'm attempting to insert this value to test it:

```
http://www.youtube.com/watch?v=q8h937ynIGc&feature=g-trend
```

This is only happening on my production server, which is an absolute pain as I can't debug through and see what the problem could be. I've verified that the mysql table structure is the same on the production server as it is locally and on my staging server, both of which are working fine. Does anyone know what could be causing this? Thanks.

**Comment by na-ji** [comment]
I've just faced the same problem too. Maybe @RobMasters you have the same production environment as me, a server connected through a proxy. I don't know what to do to configure Sonata Media to use this proxy.

**Comment by na-ji** [comment]
I had the same problem, caused by the fact my server is connected through a proxy. My solution was to configure the proxy. I had to check Sonata Media default config to find out how. :+1:
