### ISSUE TITLE
S3 filesystem should not have require on access key and secret key

### ISSUE THREAD

**Issue by Webonaute** [sonata-project/SonataMediaBundle#1769]
If you deploy on EC2 instance, you might already have permission to access internaly the s3 bucket. Maintaining access key and secret key is not require in that case.

### Environment
SonataMedia with s3 as filesystem

## Expected results
Not providing AWS_KEY and AWS_SECRET should still work on instance having proper IAM permission.

## Actual results

forced to create and maintain AWS_KEY and AWS_SECRET environment variable.
if you dont set accessKey and secretKey, it trigger error.

Replacing `src/DependencyInjection/Configuration.php`
```
 ->scalarNode('accessKey')->isRequired()->end()
 ->scalarNode('secretKey')->isRequired()->end()
```
By: 
```
 ->scalarNode('accessKey')->end()
 ->scalarNode('secretKey')->end()
```
might do the trick

**Comment by phansys** [comment]
I think it's possible to make this change if we warn the user with a useful message in cases where the credentials are not defined or the connection isn't successful.
Do you mind to create a PR @Webonaute?
