### ISSUE TITLE
Refactor `CDNInterface`

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataMediaBundle#1824]
## Feature Request
This RFC proposes to refactor the `CDNInterface` interface (and its implementations) in order to receive instances of `MediaInterface` instead of string paths.
This will allow to remove the methods `BaseProvider::getCdnPath()` and `BaseProvider::flushCdn()`. `MediaProviderInterface` interface should declare the method `getCdn(): CDNInterface`.

As a side note, note that currently, the namespace `Sonata\MediaBundle\CDN\` is completely agnostic from the rest of the project, it doesn't use any class from another namespace present in this package.

**Comment by jordisala1991** [comment]
Do you have time to work on this for 4.0 milestone?

**Comment by phansys** [comment]
I hope this feature or some parts of it can be addressed in the stable branch first.
I'll try to take a look.

**Comment by jordisala1991** [comment]
It will depend on wheter you have time for it in the next 2 weeks. My plan is to release rc1 by start of september.
