### ISSUE TITLE
YouTube media creation has stopped working

### ISSUE THREAD

**Issue by MrAnon-dev** [sonata-project/SonataMediaBundle#1888]
#### Enviroment

Symfony 2.3.42 website

#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              2.3.2  3.79.0 Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.15 3.21.0 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  2.0.1  Cache library
sonata-project/core-bundle               2.3.11 3.20.0 Symfony SonataCoreBundle
Package sonata-project/core-bundle is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/datagrid-bundle           2.2.1  3.2.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.10.1 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 2.3.4  3.24.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  2.4.1  Lightweight Exporter library
sonata-project/formatter-bundle          2.3.3  4.3.0  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2  2.2.0  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.2  2.9.0  Symfony SonataIntlBundle
sonata-project/jquery-bundle             1.10.2 1.10.2 Symfony SonatajQueryBundle
Package sonata-project/jquery-bundle is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/markitup-bundle           2.1.0  2.1.0  Symfony SonataMarkItUpBundle
Package sonata-project/markitup-bundle is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/media-bundle              2.3.1  3.28.0 Symfony SonataMediaBundle
sonata-project/notification-bundle       2.3.4  3.10.0 Symfony SonataNotificationBundle
sonata-project/seo-bundle                1.1.10 2.12.0 Symfony SonataSeoBundle
sonata-project/user-bundle               2.2.4  4.9.0  Symfony SonataUserBundle

```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle      dev-master 2e0a23a dev-master 7ffdefe Integrates Assetic into Symfony2
Package symfony/assetic-bundle is abandoned, you should avoid using it. Use symfony/webpack-encore-pack instead.
symfony/expression-language v2.8.28            v4.4.18            Symfony ExpressionLanguage Component
symfony/monolog-bundle      v2.3.0             v3.6.0             Symfony MonologBundle
symfony/polyfill-apcu       v1.6.0             v1.20.0            Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-mbstring   v1.6.0             v1.20.0            Symfony polyfill for the Mbstring extension
symfony/swiftmailer-bundle  v2.3.12            v3.5.1             Symfony SwiftmailerBundle
symfony/symfony             v2.3.42            v4.4.18            The Symfony PHP framework

```

</p>
</details>

#### PHP version

```
$ php -v

PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

```

## Subject

Hi, I have a website developed with symfony by a third person and I do not have support.

The problem is the creation of youtube videos, suddenly, has stopped working and I can't solve it. Vimeo works fine!

Updating the version of symfony and sonata is not an option for me as I would have to make too many changes to the code and I have never worked with symfony.

I saw this two issues https://github.com/sonata-project/SonataMediaBundle/pull/1847 & https://github.com/sonata-project/SonataMediaBundle/issues/1804 and tried several things but din´t help 

I think it´s not a connectivity problem, but I'm not 100% sure.

![image](https://user-images.githubusercontent.com/65110156/103524244-8427a000-4e7d-11eb-8807-375942aa7f8e.png)

**I appreciate any HELP**, I just need a fix for the youtube problem

## Expected results

Youtube video gets added like before.

## Actual results

/sonata/media/media/create?provider=sonata.media.provider.youtube&context=articulos_video

This value should not be null.
This value should not be empty.

![image](https://user-images.githubusercontent.com/65110156/103523101-a91b1380-4e7b-11eb-8dff-39aee1556acb.png)

![image](https://user-images.githubusercontent.com/65110156/103523456-28104c00-4e7c-11eb-968d-8b807a909fd6.png)

**Comment by VincentLanglet** [comment]
We do not provide any support for such old versions.

**Comment by MrAnon-dev** [comment]
wow, sorry to hear that

although I haven't programmed in a long time, in this case the solution was simple, in case it can be of help to someone

In vendor /sonata-project/media-bundle/Provider/YouTubeProvider.php
I have changed the protocol from http to https in requests to youtube and it's working again

regards

**Comment by VincentLanglet** [comment]
> wow, sorry to hear that

I'm sorry for you but this is an answer you'll get often.
The best way to avoid bug is to keep dependency up to date.
And the more you wait to update dependencies, the harder it is.

In this case, your bug was already solved:
See
https://github.com/sonata-project/SonataMediaBundle/blob/2.x/Provider/YouTubeProvider.php#L240
Vs
https://github.com/sonata-project/SonataMediaBundle/blob/3.x/src/Provider/YouTubeProvider.php#L214
