### ISSUE TITLE
Doctrine event subscriber tag

### ISSUE THREAD

**Issue by Mihailoff** [sonata-project/SonataMediaBundle#189]
1. In Symfony2-beta1 was ```doctrine.common.event_subscriber``` after (2.0+) it became ```doctrine.event_subscriber``` http://enti.ing.puc.cl/cetiuc_s/vendor/symfony/UPDATE.md and http://symfony.com/doc/current/cookbook/doctrine/event_listeners_subscribers.html

  The https://github.com/sonata-project/SonataMediaBundle/blob/2.0/Resources/config/doctrine_orm.xml has right value.

2. Doctrine MongoDB uses ```doctrine.odm.mongodb.<connection>_event_subscriber``` in current state http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html#registering-event-listeners-and-subscribers and ```doctrine_mongodb.odm.event_subscriber``` in master branch (2.1) http://symfony.com/doc/master/bundles/DoctrineMongoDBBundle/index.html#registering-event-listeners-and-subscribers

  Resources/config/doctrine_mongodb.xml must be modified differently in branch 2.0 and master. I will make PR.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active
