### ISSUE TITLE
Sonata media can't valid allowed extensions for image (MediaType) in formMapper

### ISSUE THREAD

**Issue by Sahnounmannaii** [sonata-project/SonataMediaBundle#1918]
#### Sonata packages 

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```
sonata-project/admin-bundle              3.88.0 3.89.1 The missing Symfony A...
sonata-project/block-bundle              3.21.0 4.5.0  Symfony SonataBlockBu...
sonata-project/cache                     2.0.1  2.1.1  Cache library
sonata-project/datagrid-bundle           3.3.0  3.3.0  Symfony SonataDatagri...
sonata-project/doctrine-extensions       1.9.1  1.11.0 Doctrine2 behavioral ...
sonata-project/doctrine-orm-admin-bundle 3.29.0 3.29.0 Integrate Doctrine OR...
sonata-project/exporter                  2.5.0  2.5.1  Lightweight Exporter ...
sonata-project/form-extensions           1.6.0  1.9.0  Symfony form extensions
sonata-project/intl-bundle               2.10.0 2.10.1 Symfony SonataIntlBundle
sonata-project/media-bundle              3.28.0 3.30.0 Symfony SonataMediaBu...
sonata-project/twig-extensions           1.4.1  1.5.1  Sonata twig extensions
sonata-project/user-bundle               4.9.0  4.11.0 Symfony SonataUserBundle

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
# Put the result here.
```
symfony/asset                      v4.4.19 v5.2.3  Manages URL generation and versioning of web assets suc...
symfony/browser-kit                v4.4.19 v5.2.3  Simulates the behavior of a web browser, allowing you t...
symfony/cache                      v4.4.19 v5.2.3  Provides an extended PSR-6, PSR-16 (and tags) implement...
symfony/cache-contracts            v2.2.0  v2.2.0  Generic abstractions related to caching
symfony/config                     v4.4.19 v5.2.3  Helps you find, load, combine, autofill and validate co...
symfony/console                    v4.4.19 v5.2.3  Eases the creation of beautiful and testable command li...
symfony/css-selector               v4.4.19 v5.2.3  Converts CSS selectors to XPath expressions
symfony/debug                      v4.4.19 v4.4.19 Provides tools to ease debugging PHP code
symfony/debug-bundle               v4.4.19 v5.2.3  Provides a tight integration of the Symfony Debug compo...
symfony/dependency-injection       v4.4.19 v5.2.3  Allows you to standardize and centralize the way object...
symfony/deprecation-contracts      v2.2.0  v2.2.0  A generic function and convention to trigger deprecatio...
symfony/doctrine-bridge            v4.4.19 v5.2.3  Provides integration for Doctrine with various Symfony ...
symfony/dom-crawler                v4.4.19 v5.2.3  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v4.4.19 v5.2.3  Registers environment variables from a .env file
symfony/error-handler              v4.4.19 v5.2.3  Provides tools to manage errors and ease debugging PHP ...
symfony/event-dispatcher           v4.4.19 v5.2.3  Provides tools that allow your application components t...
symfony/event-dispatcher-contracts v1.1.9  v2.2.0  Generic abstractions related to dispatching event
symfony/expression-language        v4.4.19 v5.2.3  Provides an engine that can compile and evaluate expres...
symfony/filesystem                 v4.4.19 v5.2.3  Provides basic utilities for the filesystem
symfony/finder                     v4.4.19 v5.2.3  Finds files and directories via an intuitive fluent int...
symfony/flex                       v1.12.1 v1.12.2 Composer plugin for Symfony
symfony/form                       v4.4.19 v5.2.3  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v4.4.19 v5.2.3  Provides a tight integration between Symfony components...
symfony/http-client                v4.4.19 v5.2.3  Provides powerful methods to fetch HTTP resources synch...
symfony/http-client-contracts      v2.3.1  v2.3.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.19 v5.2.3  Defines an object-oriented layer for the HTTP specifica...
symfony/http-kernel                v4.4.19 v5.2.3  Provides a structured process for converting a Request ...
symfony/inflector                  v4.4.19 v5.2.3  Converts words between their singular and plural forms ...
symfony/intl                       v4.4.19 v5.2.3  Provides a PHP replacement layer for the C intl extensi...
symfony/mailer                     v4.4.19 v5.2.3  Helps sending emails
symfony/maker-bundle               v1.29.1 v1.29.1 Symfony Maker helps you create empty commands, controll...
symfony/mime                       v4.4.19 v5.2.3  Allows manipulating MIME messages
symfony/monolog-bridge             v4.4.19 v5.2.3  Provides integration for Monolog with various Symfony c...
symfony/monolog-bundle             v3.6.0  v3.6.0  Symfony MonologBundle
symfony/options-resolver           v4.4.19 v5.2.3  Provides an improved replacement for the array_replace ...
symfony/phpunit-bridge             v5.2.3  v5.2.3  Provides utilities for PHPUnit, especially user depreca...
symfony/polyfill-intl-grapheme     v1.22.0 v1.22.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.22.0 v1.22.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.22.0 v1.22.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf...
symfony/polyfill-intl-normalizer   v1.22.0 v1.22.1 Symfony polyfill for intl's Normalizer class and relate...
symfony/polyfill-mbstring          v1.22.0 v1.22.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.22.0 v1.22.1 Symfony polyfill backporting some PHP 7.2+ features to ...
symfony/polyfill-php73             v1.22.0 v1.22.1 Symfony polyfill backporting some PHP 7.3+ features to ...
symfony/polyfill-php80             v1.22.0 v1.22.1 Symfony polyfill backporting some PHP 8.0+ features to ...
symfony/process                    v4.4.19 v5.2.3  Executes commands in sub-processes
symfony/property-access            v4.4.19 v5.2.3  Provides functions to read and write from/to an object ...
symfony/property-info              v4.4.19 v5.2.3  Extracts information about PHP class' properties using ...
symfony/routing                    v4.4.19 v5.2.3  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.1.1  v3.1.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.19 v5.2.3  Provides a tight integration of the Security component ...
symfony/security-core              v4.4.19 v5.2.3  Symfony Security Component - Core Library
symfony/security-csrf              v4.4.19 v5.2.3  Symfony Security Component - CSRF Library
symfony/security-guard             v4.4.19 v5.2.3  Symfony Security Component - Guard
symfony/security-http              v4.4.19 v5.2.3  Symfony Security Component - HTTP Integration
symfony/serializer                 v4.4.19 v5.2.3  Handles serializing and deserializing data structures, ...
symfony/service-contracts          v2.2.0  v2.2.0  Generic abstractions related to writing services
symfony/stopwatch                  v4.4.19 v5.2.3  Provides a way to profile code
symfony/string                     v5.2.3  v5.2.3  Provides an object-oriented API to strings and deals wi...
symfony/swiftmailer-bundle         v3.5.2  v3.5.2  Symfony SwiftmailerBundle
symfony/templating                 v4.4.19 v5.2.3  Provides all the tools needed to build any kind of temp...
symfony/translation                v4.4.19 v5.2.3  Provides tools to internationalize your application
symfony/translation-contracts      v2.3.0  v2.3.0  Generic abstractions related to translation
symfony/twig-bridge                v4.4.19 v5.2.3  Provides integration for Twig with various Symfony comp...
symfony/twig-bundle                v4.4.19 v5.2.3  Provides a tight integration of Twig into the Symfony f...
symfony/validator                  v4.4.19 v5.2.3  Provides tools to validate values
symfony/var-dumper                 v4.4.19 v5.2.3  Provides mechanisms for walking through any arbitrary P...
symfony/var-exporter               v4.4.19 v5.2.3  Allows exporting any serializable PHP data structure to...
symfony/web-link                   v4.4.19 v5.2.3  Manages links between resources
symfony/web-profiler-bundle        v4.4.19 v5.2.3  Provides a development tool that gives detailed informa...
symfony/web-server-bundle          v4.4.19 v4.4.19 Provides commands for running applications using the PH...
symfony/yaml                       v4.4.19 v5.2.3  Loads and dumps YAML files

</p>
</details>

#### PHP version

```
$ php -v
# Put the result here.
```
PHP 7.4.15 (cli) (built: Feb 14 2021 14:19:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies

## Subject
Sonata media can't valid allowed extensions for image (MediaType) in formMapper

## Steps to reproduce
sonata_media.yml config
    providers:
        image:
            service:    sonata.media.provider.image
            allowed_extensions: ['jpg', 'png', 'jpeg']
            allowed_mime_types: ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']

go to soanta admin
click on company for exemple
click add new company
form of company have an logo thats a mediaType with settings 
->add('logo',  MediaType::class, array(
                    'provider'=>'sonata.media.provider.image',
                    'context'  => 'default',
                    'required' => false,
                ))
when upload an pdf or excel insted of image(png or jpg) 

## Expected results

A falsh message contain for exemple "you must upload an image"

## Actual results
an error (exception) with this message
An image could not be created from the given input

**Comment by jordisala1991** [comment]
It works as expected. You just need to make sure you add a `Valid` constraint to the property. It can be done like this:

```
->add('logo', MediaType::class, [
    'provider' => 'sonata.media.provider.image',
    'context' => 'default',
    'required' => false,
    'constraints' => new \Symfony\Component\Validator\Constraints\Valid(),
])
```
