### ISSUE TITLE
[NEXT_MAJOR] Bump dependencies

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataMediaBundle#1931]
## Feature Request

This is list of dependencies which should be bump:
- [ ] `aws/aws-sdk-php` < 3.0
- [ ] `sonata-projec/block-bundle` < 4.0
- [ ] `sonata-projec/notifiation-bundle` < 4.0
- [ ] `sonata-projec/seo-bundle` < 4.0

**Comment by VincentLanglet** [comment]
Done
