### ISSUE TITLE
[NEXT_MAJOR] Add support for Symfony 5

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataMediaBundle#1932]
## Feature Request

This is list of components which should be (some of it can be done in `3.x`): 
- [ ] `symfony/config`
- [ ] `symfony/console`
- [ ] `symfony/dependency-injection`
- [ ] `symfony/event-dispatcher`
- [ ] `symfony/finder`
- [ ] `symfony/form`
- [ ] `symfony/framework-bundle`
- [ ] `symfony/http-foundation`
- [ ] `symfony/http-kernel`
- [ ] `symfony/routing`
- [ ] `symfony/security-bundle`
- [ ] `symfony/security-core`
- [ ] `symfony/security-csrf`
- [ ] `symfony/templating`
- [ ] `symfony/translation`
- [ ] `symfony/twig-bridge`
- [ ] `symfony/twig-bundle`

**Comment by jordisala1991** [comment]
Done in master, closing.
