### ISSUE TITLE
Drop suport for imagine/imagine < 1.0

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataMediaBundle#1945]
This bundle should be bump for two reasons:
- https://github.com/sonata-project/dev-kit/pull/1430#issuecomment-806276126
- version 1.0 provide many BC-breaks. - [look at changelog](https://github.com/avalanche123/Imagine/blob/1.2.4/CHANGELOG.md#100-alpha1-2018-08-28)

**Comment by VincentLanglet** [comment]
Done
