### ISSUE TITLE
Clean up service definitions

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataMediaBundle#1970]
## Feature Request

Some tasks we could do:
- There are a lot of `public` services that are not needed to be (commands, admins, twig extensions, etc).
- We can get rid of the `alias` attribute in form types.
- Remove unnecessary aliases.
- Remove class parameters (e.g. `sonata.media.resizer.crop.class`).

**Comment by jordisala1991** [comment]
This is fixed on master.
