### ISSUE TITLE
Remove openStack/rackSpace integration

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/SonataMediaBundle#1986]
## Feature Request

When working on this PR: https://github.com/sonata-project/SonataMediaBundle/pull/1983 we noticed that we are defining a lot of options to integrate with openstack/rackspace adapter from gauffrete.

The problem is this adapter is using a really old implementation: https://github.com/rackspace/php-opencloud with a really old dependencies like `guzze/guzzle` ^3.8, and `symfony/dependency-injection` ~2.1

There is a newer version of the openstack integration, but it is not working with gauffrete: https://github.com/php-opencloud/openstack.

IMO we should remove this integration from our code, because we can't guarantee it will work, because we can't test it without forcing really old, deprecated and unmaintained 3rd party dependencies.

This deprecation can be done on 3.x and removal on 4.0.

WDYT @sonata-project/contributors ?

**Comment by VincentLanglet** [comment]
I agree with this removal.

**Comment by jordisala1991** [comment]
Fixed on #2071
