### ISSUE TITLE
Add support for PDF with thumbnails generation

### ISSUE THREAD

**Issue by rande** [sonata-project/SonataMediaBundle#2]
Create a new PDF Provider
http://blog.prashanthellina.com/2008/02/03/create-pdf-thumbnails-using-imagemagick-on-linux/

**Comment by Hoannv** [comment]
+1

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
