### ISSUE TITLE
Item "id" for "" does not exist in edit.html.twig

### ISSUE THREAD

**Issue by thomas2411** [sonata-project/SonataMediaBundle#201]
I have a weird error. I use SonataAdmin and SonataMedia Bundles on 2 sites (with Symfony 2.1 and Sonata master branches). In one of these pages SonataMedia works well.

In the other one I get this error. Config is OK, I can add media in MediaAdmin, I can use sonata_media_type but if I use this:

```php
->add('media', 'sonata_type_model_list', array('required' => false), array( 'link_parameters' => array('context' => 'photo')))
```

Error (of course cache cleared)

![Error](http://db.tt/bOO1D7NX)

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active
