### ISSUE TITLE
Deprecate Pixlr integration?

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/SonataMediaBundle#2107]
## Deprecation Request

Should we deprecate Pixlr integration? I am not even sure if it works or is broken (it is a really old integration and the Pixlr webpage changed a lot).

Does it make sense to have this kind of feature here or should we focus on image upload / download?

**Comment by jordisala1991** [comment]
@phansys or @core23 , do you use this feature?

**Comment by core23** [comment]
IMHO we should remove all fancy / nice to have features and reduce the scope of the bundle. The bundle should only provide core features for media management.
