### ISSUE TITLE
Replace SonataNotificationBundle integration by symfony/messenger

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/SonataMediaBundle#2109]
## Feature Request

I think symfony/messenger is the way to go. Instead of having to maintain our own solution, we could provide integration with Symfony. wdyt @sonata-project/contributors ?

IMO there is no need to directly deprecate SonataNotificationBundle but we could instead stop using it on next major releases, so when everything is done, there would be no dependencies and we can deprecate it without losing anything.

**Comment by wbloszyk** [comment]
IMO at first we should decide what to do with `SonataNotificationBundle`.  I do not using it in my projects and I do not know it very well. But I think we should compare functionality of these two bundles at first. The most important thing for me (IMO) is integrate notification with `AdminBundle`.

Will be awesome to require `symfony/messenger` and suggest `sonata-project/notification-bundle`.
