### ISSUE TITLE
DRAFT: Update documentation

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataMediaBundle#2132]
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
# Put the result here.
```

</p>
</details>

#### PHP version

```
$ php -v
# Put the result here.
```

## Actual results

link: https://docs.sonata-project.org/projects/SonataMediaBundle/en/3.x/reference/creating_a_provider_class/#register-the-class-with-the-service-container
don't need this

```
 - '@sonata.media.http.client'
 - '@sonata.media.metadata.proxy'
```

**Comment by eerison** [comment]
please just consider this issue when I remove the `DRAFT`, I'm trying to use the new BaseProvider and I'm using this issue to save te problems.

**Comment by VincentLanglet** [comment]
> please just consider this issue when I remove the `DRAFT`, I'm trying to use the new BaseProvider and I'm using this issue to save te problems.

Sure, feel free to open a PR with the documentation update needed after.

**Comment by jordisala1991** [comment]
I would like to focus all efforts about docs here: #2106
