### ISSUE TITLE
Unknown "media_thumbnail" function. Did you mean "sonata_thumbnail"?

### ISSUE THREAD

**Issue by wokenlex** [sonata-project/SonataMediaBundle#2174]
#### Sonata packages

<details><summary>show</summary>
<p>

sonata-project/admin-bundle              3.105.3 4.0.1  The missing Symfony Admin Generator
sonata-project/block-bundle              3.23.2  4.7.0  Symfony SonataBlockBundle
sonata-project/cache                     2.2.0   2.2.0  Cache library
sonata-project/doctrine-extensions       1.14.0  1.14.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.35.0  4.0.0  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.8.0   2.8.0  Lightweight Exporter library
sonata-project/form-extensions           1.12.0  1.12.0 Symfony form extensions
sonata-project/intl-bundle               2.10.2  2.10.2 Symfony SonataIntlBundle
sonata-project/media-bundle              3.35.0  3.35.0 Symfony SonataMediaBundle
sonata-project/translation-bundle        2.9.0   2.9.0  SonataTranslationBundle
sonata-project/twig-extensions           1.9.0   1.9.0  Sonata twig extensions

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

symfony/asset                      v4.4.27 v5.3.4  Manages URL generation and versioning of web assets such as CSS stylesheets, Ja...
symfony/browser-kit                v4.4.27 v5.3.4  Simulates the behavior of a web browser, allowing you to make requests, click o...
symfony/cache                      v4.4.31 v5.3.8  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.4.0  v2.4.0  Generic abstractions related to caching
symfony/config                     v4.4.30 v5.3.4  Helps you find, load, combine, autofill and validate configuration values of an...
symfony/console                    v4.4.30 v5.3.7  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v4.4.27 v5.3.4  Converts CSS selectors to XPath expressions
symfony/debug                      v4.4.31 v4.4.31 Provides tools to ease debugging PHP code
symfony/debug-bundle               v4.4.27 v5.3.4  Provides a tight integration of the Symfony Debug component into the Symfony fu...
symfony/dependency-injection       v4.4.31 v5.3.8  Allows you to standardize and centralize the way objects are constructed in you...
symfony/deprecation-contracts      v2.4.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.4.31 v5.3.8  Provides integration for Doctrine with various Symfony components
symfony/dom-crawler                v4.4.30 v5.3.7  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v4.4.29 v5.3.8  Registers environment variables from a .env file
symfony/error-handler              v4.4.30 v5.3.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v4.4.30 v5.3.7  Provides tools that allow your application components to communicate with each ...
symfony/event-dispatcher-contracts v1.1.9  v2.4.0  Generic abstractions related to dispatching event
symfony/expression-language        v4.4.30 v5.3.7  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v4.4.27 v5.3.4  Provides basic utilities for the filesystem
symfony/finder                     v4.4.30 v5.3.7  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.17.1 v1.17.1 Composer plugin for Symfony
symfony/form                       v4.4.31 v5.3.8  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v4.4.31 v5.3.8  Provides a tight integration between Symfony components and the Symfony full-st...
symfony/http-client                v4.4.31 v5.3.8  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.4.0  v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.30 v5.3.7  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v4.4.32 v5.3.9  Provides a structured process for converting a Request into a Response
symfony/inflector                  v4.4.27 v5.3.4  Converts words between their singular and plural forms (English only)
Package symfony/inflector is abandoned, you should avoid using it. Use use `EnglishInflector` from the String component instead instead.
symfony/intl                       v4.4.31 v5.3.8  Provides a PHP replacement layer for the C intl extension that includes additio...
symfony/maker-bundle               v1.34.1 v1.34.1 Symfony Maker helps you create empty commands, controllers, form classes, tests...
symfony/messenger                  v4.4.32 v5.3.9  Helps applications send and receive messages to/from other applications or via ...
symfony/mime                       v4.4.31 v5.3.8  Allows manipulating MIME messages
symfony/monolog-bridge             v4.4.27 v5.3.7  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.7.0  v3.7.0  Symfony MonologBundle
symfony/options-resolver           v4.4.30 v5.3.7  Provides an improved replacement for the array_replace PHP function
symfony/phpunit-bridge             v5.3.8  v5.3.8  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme     v1.23.1 v1.23.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.23.0 v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.23.0 v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.23.0 v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.23.1 v1.23.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.23.1 v1.23.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                    v4.4.30 v5.3.7  Executes commands in sub-processes
symfony/property-access            v4.4.30 v5.3.8  Provides functions to read and write from/to an object or array using a simple ...
symfony/property-info              v4.4.31 v5.3.8  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v4.4.27 v5.3.4  Provides integration for ProxyManager with various Symfony components
symfony/routing                    v4.4.30 v5.3.7  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.2.0  v3.2.0  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.27 v5.3.8  Provides a tight integration of the Security component into the Symfony full-st...
symfony/security-core              v4.4.31 v5.3.8  Symfony Security Component - Core Library
symfony/security-csrf              v4.4.27 v5.3.4  Symfony Security Component - CSRF Library
symfony/security-guard             v4.4.27 v5.3.7  Symfony Security Component - Guard
symfony/security-http              v4.4.30 v5.3.8  Symfony Security Component - HTTP Integration
symfony/serializer                 v4.4.31 v5.3.8  Handles serializing and deserializing data structures, including object graphs,...
symfony/service-contracts          v2.4.0  v2.4.0  Generic abstractions related to writing services
symfony/stopwatch                  v4.4.27 v5.3.4  Provides a way to profile code
symfony/string                     v5.3.7  v5.3.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code poi...
symfony/swiftmailer-bundle         v3.5.2  v3.5.2  Symfony SwiftmailerBundle
symfony/templating                 v4.4.30 v5.3.7  Provides all the tools needed to build any kind of template system
symfony/translation                v4.4.32 v5.3.9  Provides tools to internationalize your application
symfony/translation-contracts      v2.4.0  v2.4.0  Generic abstractions related to translation
symfony/twig-bridge                v4.4.27 v5.3.7  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v4.4.30 v5.3.4  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v4.4.31 v5.3.8  Provides tools to validate values
symfony/var-dumper                 v4.4.31 v5.3.8  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v4.4.31 v5.3.8  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v4.4.27 v5.3.4  Manages links between resources
symfony/web-profiler-bundle        v4.4.31 v5.3.8  Provides a development tool that gives detailed information about the execution...
symfony/webpack-encore-bundle      v1.12.0 v1.12.0 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v4.4.29 v5.3.6  Loads and dumps YAML files

</p>
</details>

#### PHP version

7.4.24

## Subject

After the update to the 3.35.0 media bundle, I got an error Unknown "media_thumbnail" function. Did you mean "sonata_thumbnail"?

I have looked into repo and found what some templates uses the media_thumbnail, but only sonata_thumbnail  is registered as a twigFunction.

## Actual results

Error in vendor/sonata-project/media-bundle/src/Resources/views/Form/media_widgets.html.twig (line 35)

**Comment by jordisala1991** [comment]
Hi @wokenlex , I changed the function recently but probably made a mistake on the naming. Are you open for a PR fixing that?

**Comment by wokenlex** [comment]
Sorry for disappear - yes, your PR fixed it.
