### ISSUE TITLE
Context configuration not works in production

### ISSUE THREAD

**Issue by angelinafox87** [sonata-project/SonataMediaBundle#220]
Hello!

Please, i don't undertand why if only i have one configuration in config.yml works different in dev(app_dev.php) and in prod (app.php)

In dev works ok, only there is a one context and  only i can select image format. In prod the context is 'others' but i deleted it :S, maybe is a bug?

My configuration: 

sonata_media:
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image
            formats:
                default:   { width: 734 , quality: 90}

in sonata admin:
            ->add('gallery', 'sonata_type_model',
                array(
                    'label' => 'Gallery',
                    'sonata_admin' =>true,
                    'required' => false,
                ))
            ->end()

Help me please

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @angelinafox87
