### ISSUE TITLE
Can't set resizer false

### ISSUE THREAD

**Issue by dima-gr** [sonata-project/SonataMediaBundle#2223]
```
providers:
        file:
            service:    sonata.media.provider.file
            resizer:    false
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/rtf', 'text/html', 'text/rtf', 'text/plain']
```
this config was taken here - [https://docs.sonata-project.org/projects/SonataMediaBundle/en/5.x/reference/advanced_configuration/](url)

and it gives an error
```
Symfony\Component\DependencyInjection\Reference::__construct(): Argument #1 ($id) must be of type string, bool given, called in /var/www/html/vendor/sonata-project/media-bundle/src/DependencyInjection/Compiler/AddProviderCompilerPass.php on line 74
```

**Comment by jordisala1991** [comment]
Can you try with null?

**Comment by dima-gr** [comment]
Yes it works, thx. There is one more thing, if you enable integration with liip imagine, then svg not rendered, maybe you don't need to apply the filter for them

**Comment by jordisala1991** [comment]
> Yes it works, thx. There is one more thing, if you enable integration with liip imagine, then svg not rendered, maybe you don't need to apply the filter for them

Can you open a PR to modify the docs for the 4.x branch to change the false for null?

Also I think this bundle do not play well with svg, maybe you want to open another issue to explain your case in detail. We prefer to focus one issue with one problem.
