### ISSUE TITLE
Liip imagine integration and svg

### ISSUE THREAD

**Issue by dima-gr** [sonata-project/SonataMediaBundle#2231]
If you enable integration with liip imagine, svg image downloaded and render in admin list but when you try render image somewhere in twig template then svg not rendered, maybe you don't need to apply the filter for them

**Comment by core23** [comment]
Can you provide a PR with this feature @dima-gr ?

**Comment by dima-gr** [comment]
Ok, but it will be littlebit later

**Comment by VincentLanglet** [comment]
Friendly ping @dima-gr, do you have some time for this feature ?

**Comment by dima-gr** [comment]
I'll try provide a PR in the next week

**Comment by dima-gr** [comment]
I'm create PR, the problem is that the GD driver does not support working with svg, the entry is marked as MediaInterface::STATUS_ERROR, it happens in ImageProvider.php on 283 line

```
        try {
            $image = $this->imagineAdapter->open($binaryContent->getPathname());
        } catch (\RuntimeException $e) {
            $media->setProviderStatus(MediaInterface::STATUS_ERROR);

            return;
        }
```
