### ISSUE TITLE
Weird brackets in SonataMediaBundle/src/Resources/views/MediaAdmin/inner_row_media.html.twig

### ISSUE THREAD

**Issue by cezar77** [sonata-project/SonataMediaBundle#2243]
In the template `SonataMediaBundle/src/Resources/views/MediaAdmin/inner_row_media.html.twig` there seem to be some malformed brackets on lines 18 and 27:

    <a href="{{ admin.generateObjectUrl('edit', object) }) }}" style="float: left; margin-right: 6px;">

    <a href="{{ admin.generateObjectUrl('edit', object }) }}"><strong>{{ object.name }}</strong></a>

It is after `'edit', object`.

**Comment by VincentLanglet** [comment]
Introduced by https://github.com/sonata-project/SonataMediaBundle/commit/af6dc96b377164cdfee8664bc9056ae882d58c25 so it's on both 3.x and 4.x.

Can you provide a PR on 3.x ?

**Comment by jordisala1991** [comment]
Yes, thank you for reporting. Probably while updating the code I introduce it.

Do you mind sending a Pr on the lower branch it happens?

**Comment by jordisala1991** [comment]
Also, where is this template being used @cezar77 ? It might help to add a test to ensure we dont break it again.

**Comment by cezar77** [comment]
The template is used for the list view for Media. The mosaic view works well, when switching to list view - BUM! an error happens.

**Comment by VincentLanglet** [comment]
Solved by https://github.com/sonata-project/SonataMediaBundle/pull/2245

**Comment by jordisala1991** [comment]
Maybe we need to add a test for the normal list view, will try to take a look

**Comment by cezar77** [comment]
For my Symfony projects I run the command:

    symfony console lint:twig templates/

Maybe something similar (in your case `src/Resources/views`) could be run automatically.

**Comment by jordisala1991** [comment]
The problem is running those commands outside a real application. But we can try it with the test kernel.
