### ISSUE TITLE
Extra parentheses

### ISSUE THREAD

**Issue by biperch** [sonata-project/SonataMediaBundle#2244]
https://github.com/sonata-project/SonataMediaBundle/blob/5e163066fb59df14611afa81ef6b5bab52a4cb20/src/Resources/views/MediaAdmin/inner_row_media.html.twig#L18

Extra parentheses in this line

**Comment by core23** [comment]
Can you provide a PR with a fix @biperch ?

**Comment by cezar77** [comment]
I already opened an issue regarding this:
https://github.com/sonata-project/SonataMediaBundle/issues/2243

**Comment by VincentLanglet** [comment]
Solved by https://github.com/sonata-project/SonataMediaBundle/pull/2245
