### ISSUE TITLE
Amazon AES256 not set property

### ISSUE THREAD

**Issue by mpoiriert** [sonata-project/SonataMediaBundle#2294]
The AES256 value is set via **encryption** but the configuration from Amazon is named **ServerSideEncryption**

https://github.com/sonata-project/SonataMediaBundle/blob/dd53b0a6f5c7df3eab29a7393b597a03a2298c9c/src/Metadata/AmazonMetadataBuilder.php#L104

From 
https://docs.aws.amazon.com/AmazonS3/latest/userguide/specifying-s3-encryption.html

$result = $s3->putObject([
    'Bucket'               => $bucket,
    'Key'                  => $keyname,
    'SourceFile'           => $filepath,
    'ServerSideEncryption' => 'AES256',
]);

**Comment by VincentLanglet** [comment]
HI @mpoiriert, can you provide a PR with the fix ? :)
