### ISSUE TITLE
The image extension "JPG" is not one of the allowed

### ISSUE THREAD

**Issue by treehousedevelopers** [sonata-project/SonataMediaBundle#2297]
#### Sonata packages
<details>
<p>
```
sonata-project/media-bundle  3.38.1 
```
</p>
</details>

## Subject
The image extension "JPG" is not one of the allowed ("jpg", "png", "jpeg", "gif").

## Steps to reproduce
Upload file with JPG extension in name.

## Expected results
Restore strtolower() before allowed extensions check. It has been removed in last [commit](https://github.com/sonata-project/SonataMediaBundle/commit/e875289e0325bec8b75910867b6b449ceda00f91#diff-67180f223f1bd847e875cb4b6fc8e2df5bb0dfe73306b9c5a1ccf94075b67c0bL231)

It has been removed also in version 4.x and 5.x.

## Actual results
The image extension "JPG" is not one of the allowed.

**Comment by VincentLanglet** [comment]
Can you provide a PR with the fix @treehousedevelopers ?

**Comment by jerome-fix** [comment]
@VincentLanglet 

Could you create a new tag with this correction?

Thanks

Jérôme.

**Comment by VincentLanglet** [comment]
on it https://github.com/sonata-project/SonataMediaBundle/pull/2302
