### ISSUE TITLE
[5.0] knplabs/gaufrette is going to be deprecated

### ISSUE THREAD

**Issue by dmitryuk** [sonata-project/SonataMediaBundle#2350]
Visit https://github.com/KnpLabs/Gaufrette and see the message 
```
Gaufrette package is deprecated and will not be compatible with PHP 8.2. [You should use Flysystem instead]
```
So SonataMediaBundle v5 have to avoid this dependency

**Comment by VincentLanglet** [comment]
There is already https://github.com/sonata-project/SonataMediaBundle/issues/1985

Closing as it's a duplicate
