### ISSUE TITLE
No support for gif format?

### ISSUE THREAD

**Issue by tworzenieweb** [sonata-project/SonataMediaBundle#237]
Hi,

today i was trying to made some gallery of advertisements for my page. I have installed this bundle as always with Symfony 2.1. I was a little surprised that image validator didn't allow me to send any gif files. Only jpeg files pass. Is there any special config parameter that controls this? 

I have checked provider.xml file for any hints but 

``` xml
 <service id="sonata.media.provider.image" class="%sonata.media.provider.image.class%">
            <tag name="sonata.media.provider" />
            <argument>sonata.media.provider.image</argument>
            <argument />
            <argument />
            <argument />
            <argument type="service" id="sonata.media.thumbnail.format" />
            <argument />
            <argument />
            <argument />

            <call method="setTemplates">
                <argument type="collection">
                    <argument key='helper_thumbnail'>SonataMediaBundle:Provider:thumbnail.html.twig</argument>
                    <argument key='helper_view'>SonataMediaBundle:Provider:view_image.html.twig</argument>
                </argument>
            </call>
        </service>
```

This definition is rather straightforward with image provider constructor

`public function __construct($name, Filesystem $filesystem, CDNInterface $cdn, GeneratorInterface $pathGenerator, ThumbnailInterface $thumbnail, array $allowedExtensions = array(), array $allowedMimeTypes = array(), ImagineInterface $adapter)`

so my question is based on which parameter set of allowed extensions and mime types is fetched?

**Comment by dvapelnik** [comment]
I know that this is old thread but anyway
Can I except all gif-files from re-sizing? For instance, using specific provider with dummy re-sizer only for gif-files
Any examples?
Thanks

**Comment by r-sede** [comment]
> I know that this is old thread but anyway Can I except all gif-files from re-sizing? For instance, using specific provider with dummy re-sizer only for gif-files Any examples? Thanks

still have an issue, anybody ?

**Comment by jordisala1991** [comment]
This issue was created almost 10 years ago. Please open a new issue with your concrete issue, make sure you fill the whole issue template.
