### ISSUE TITLE
Use admin.hasAccess instead of admin.isGranted

### ISSUE THREAD

**Issue by mpoiriert** [sonata-project/SonataMediaBundle#2400]
## Feature Request

In the template the method admin.isGranted is use.

We should change it to admin.hasAccess to match the behaviour of button configuration and controller.

Maybe more a bug than a feature ?

**Comment by VincentLanglet** [comment]
I think @jordisala1991 made similar change in this/another bundle. I need to search the Pr.

Feel free to provide the Pr @mpoiriert :)
