### ISSUE TITLE
Change the default upload directory (from the official recipe) to uploads/ instead of upload/

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataMediaBundle#2408]
## Feature Request

This is a DX feature request: change the default upload directory (in the official recipe) to `uploads/` instead of `upload/`. Why? Even the official documentation uses the uploads folder, i.e. https://symfony.com/doc/current/controller/upload_file.html. 

Recipe link: https://github.com/symfony/recipes-contrib/tree/main/sonata-project/media-bundle/4.0

I can provide a PR in https://github.com/symfony/recipes-contrib but I think It should be approved by official maintainers.

**Comment by VincentLanglet** [comment]
Changing this in the recipe can be done without any BC break, so why not.
Is there other sonata bundle with the same "issue" ; we should be consistent

I let you open the PR (unless @jordisala1991 disagree)

**Comment by gremo** [comment]
@VincentLanglet done: https://github.com/symfony/recipes-contrib/pull/1532
