### ISSUE TITLE
[nice to have] Use Media without Gallery

### ISSUE THREAD

**Issue by tiagojsag** [sonata-project/SonataMediaBundle#242]
Hi,

So this is one of those nice to have things, and AFAIK it's not trivial at all to implement, but I'll post the idea anyway:
I've been using SonataMediaBundle for over a year in several projects, and all the time I end up having to do some voodoo to get rid of Gallery, as I simply don't use it. 

To address this, I use one of two approaches: make my own entity extend Gallery, which is quite simple, but not very flexible;
or copy GalleryHasMedia to MyEntityHasMedia and just leave the Gallery and GalleryHasMedia stuff laying around, extended and not used in app/Application. This allows for much more flexibility, but produce a lot of useless code and two empty useless DB tables.

Would it be possible to somehow address this?

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
