### ISSUE TITLE
MediaBlockService required if formats defined

### ISSUE THREAD

**Issue by mesiarm** [sonata-project/SonataMediaBundle#2435]
Make format key always optional even if formats are defined.
Now it is: `'required' => \count($formatChoices) > 0,`
It is unable to set some of images reference if formats are defined

**Comment by VincentLanglet** [comment]
HI @mesiarm, can you explain why the format key should be optional ?

**Comment by mesiarm** [comment]
> HI @mesiarm, can you explain why the format key should be optional ?

There may be cases, when I want to choose it by programming logic or use full size.

**Comment by VincentLanglet** [comment]
> There may be cases, when I want to choose it by programming logic or use full size.

But I assume the data need to be required for people which doesn't have extra-programming-logic. Changing the field to optional will create an issue for them. 

Does adding an option to `configureSettings` would help you ?

**Comment by mesiarm** [comment]
> > There may be cases, when I want to choose it by programming logic or use full size.
> 
> But I assume the data need to be required for people which doesn't have extra-programming-logic. Changing the field to optional will create an issue for them.
> 
> Does adding an option to `configureSettings` would help you ?

Yes, it would help

**Comment by VincentLanglet** [comment]
PR welcomed then.
