### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Cannot assign null to property Sonata\MediaBundle\Model\Media::$cdnIsFlushable of type bool").

### ISSUE THREAD

**Issue by hongdoan1** [sonata-project/SonataMediaBundle#2451]
i got this error when trying to get the path of $media

    private FileProvider $provider;

    public function __construct( FileProvider $provider)
    {
        $this->provider  = $provider;
    }
`$this->provider->generatePublicUrl($media, $format);`

**Comment by VincentLanglet** [comment]
Hi,

When opening an issue there is a template to fill

### Environment

#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
# Put the result here.
```

</p>
</details>

You can't expect someone to solve/fix your probleme without any information.
Also, when you have an exception, you have a stacktrace with it, which helps to understand which method are called and where the issue come from. Without such information, there is nothing to do.
