### ISSUE TITLE
Formats at choice list of default format during gallery edit are not translated

### ISSUE THREAD

**Issue by piotrminkina** [sonata-project/SonataMediaBundle#250]
Hello

As I wrote in the subject line. On gallery admin list the format is translated. I think instead of `$formats[$name] = $name;` should be `$formats[$name] = $this->trans($name);` on line 51 in [SonataMediaBundle/Admin/GalleryAdmin.php](https://github.com/sonata-project/SonataMediaBundle/blob/master/Admin/GalleryAdmin.php#L51).

Regards
Piotr Minkina

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @piotrminkina
