### ISSUE TITLE
Media Form Type : An image could not be created from the given input

### ISSUE THREAD

**Issue by vwasteels** [sonata-project/SonataMediaBundle#288]
Hello,

I'm using the Media form type, with : 
```'provider' => 'sonata.media.provider.image'```

But if the user try to upload a file that is not supported, let's say a PDF, it shows an error 500 to the user, the Exception thrown is : 

```An image could not be created from the given input , 
in /vendor/imagine/Imagine/lib/Imagine/Gd/Imagine.php at line 131```

Is there a way to add some validation ? It should show a form validation error to the user instead of "server error"

Thanks

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @vwasteels

**Comment by clytemnestra** [comment]
@core23 I am also getting the same error. I wonder if it's something I'm not doing right.

I'm using an extended class

```yaml
sonata_media:
    class:
        media: Application\Sonata\MediaBundle\Entity\Media
```

```php

/**
 * @ORM\Entity()
 * @ORM\Table("media__media")
 */
class Media extends BaseMedia
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;


    /**
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="images")
     * @ORM\JoinColumn(name="user", referencedColumnName="id",nullable=true)
     */
    private $user;
```

**Comment by vwasteels** [comment]
@core23 I abandoned Symfony2 a while ago, sorry

**Comment by 4ssil** [comment]
To help anybody else having the same issue, where validation is not triggered on your Media Entity. You will have to add a constraint to trigger the validation. 

Let's imagine you have a User entity with a photo field in it, which maps to a Media entity. In your validation file (using yaml here) do this:

```
AppBundle\Entity\User:
    properties:
        photo:
           - Valid: ~
```

This will make the errors you're expecting to show up: 
-  Invalid extensions
- Invalid mime type : text/plain

**Comment by OskarStark** [comment]
@clytemnestra does this fix your issue?

**Comment by clytemnestra** [comment]
I'm not using Sonata anymore, unfortunately.

**Comment by OskarStark** [comment]
> I'm not using Sonata anymore, unfortunately.

Anyway, thank you for the feedback 👍
