### ISSUE TITLE
/classes.php line 9997") in "SonataMediaBundle:MediaAdmin:select_provider.html.twig"

### ISSUE THREAD

**Issue by Bensid** [sonata-project/SonataMediaBundle#296]
Hi, I have a problem with adding media. In fact, I get this error : 

An exception has been thrown during the rendering of a template ("Warning: get_class() expects parameter 1 to be object, boolean given in /var/www/Symfony/app/cache/dev/classes.php line 9997") in "SonataMediaBundle:MediaAdmin:select_provider.html.twig". 

in http://localhost/Symfony/web/app_dev.php/admin/sonata/media/media/create

Thank you for your help !

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @Bensid
