### ISSUE TITLE
GalleryAdmin $formats is null

### ISSUE THREAD

**Issue by ornj** [sonata-project/SonataMediaBundle#298]
The GalleryAdmin is being included in the form using `sonata_type_model_list`

```php
$formMapper
    ->add('gallery', 'sonata_type_model_list', array(
        'required'          => false,
    ), array(
        'link_parameters'   => array(
            'context'       => $this->context,
            'provider'      => 'sonata.media.provider.image',
        )
    ))
;
```

When I click the "Add New" button in the Gallery form and the form renders, I can see that the instance of `Sonata\MediaBundle\Provider\Pool` that is passed to GalleryAdmin as an argument contains a variable, `$contexts`. In each context in that array there is key, `formats`. That key is populated with the values defined in my config as you'd expect; however, `$this->pool->getFormatNamesByContext($context)` returns null.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @ornj
