### ISSUE TITLE
Unable to submit form after deleting media

### ISSUE THREAD

**Issue by ornj** [sonata-project/SonataMediaBundle#299]
I'm not 100% this is related to this bundle or SonataAdminBundle but I'm going to open the issue here. 

I have a field in my form something like:

```php
$formMapper
  ->add('video', 'sonata_type_model_list', array(), array(
      'link_parameters'   => array(
        'context'       => 'default',
        'provider'      => 'sonata.media.provider.vimeo',
    )))
;
```

After adding a media object and submitting the form, when I go back and click the delete button on the field, the media object appears to be removed. When I then click the "Update" button to submit the form and update the parent entity I get the following Javascript error"

    An invalid form control with name='s514b2d8117236[video]' is not focusable.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @ornj
