### ISSUE TITLE
Deprecation warning when adding new media via SonataAdminBundle 

### ISSUE THREAD

**Issue by speelgoedkoper** [sonata-project/SonataMediaBundle#307]
Not sure if this is related to the SonataMediaBundle (1bcee87) or the SonataAdminBundle (d271b25).

When the form to add a new file-based media via `http://[projectsite]/admin/sonata/media/media/create?provider=sonata.media.provider.image&context=default` is displayed the Symfony profiler indicates the following warning:

    DEPRECATION - appendNormTransformer() is deprecated since version 2.1 and will be removed in 2.3.  
    Called from FormConfigBuilder::appendNormTransformer() at line 74
    Called from BaseMediaAdmin::configureFormFields() at line 2112
    Called from Admin::defineFormBuilder() at line 2106
    Called from Admin::getFormBuilder() at line 1921
    Called from Admin::buildForm() at line 2156
    Called from Admin::getForm() at line 478
    Called from CRUDController::createAction() at line 73
    Called from MediaAdminController::createAction()

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @speelgoedkoper
