### ISSUE TITLE
sonata_type_model_list + property_path ?

### ISSUE THREAD

**Issue by ibasaw** [sonata-project/SonataMediaBundle#317]
hi
How to do this ?

                ->add('image', 'sonata_type_model_list', array('required' => false, 'label' => 'Image',
                    'property_path' => 'suggestions1.image'),
                        array('link_parameters' => array
                        (
                            'provider' => 'sonata.media.provider.image',
                            'context'  => 'partenaires'
                        )
                ))

it work without property_path, but i need property_path to get the sub property of my object

got this error:

    Item "id" for "" does not exist in SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig at line 60

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @ibasaw
