### ISSUE TITLE
Wrong parameter context while editing gallery

### ISSUE THREAD

**Issue by jockerTDI** [sonata-project/SonataMediaBundle#318]
In object form gallery field is added by
```php
$formMapper->add('gallery', 'sonata_type_model_list', 
                  array('required' => false), 
                  array('link_parameters' => array('context' => 'gallery')))
```
then buttons "List" and "Add new" has context="gallery", but edit link always has context="default"

while editing galleries by url /admin/sonata/media/gallery/list?context=gallery everything is ok

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @jockerTDI
