### ISSUE TITLE
Form redirects after file upload.

### ISSUE THREAD

**Issue by lzakrzewski** [sonata-project/SonataMediaBundle#320]
After upload file (image) the form redirects to media create page.
On demo page http://demo.sonata-project.org/admin/sonata/media/gallery/979/edit?context=default I can see that after image upload dialog box is closing, and redirect after submit form is prevented.

Demo is using ".live()" method. New version of sonata media bundle uses ".on()"
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Resources/views/CRUD/edit_orm_many_association_script.html.twig#l154
- When I will use old doctrine-orm-admin template (.live() instead of .on() ) then its works fine.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @lzakrzewski
