### ISSUE TITLE
SonataMediaBundle. Crop Image

### ISSUE THREAD

**Issue by m4a1fox** [sonata-project/SonataMediaBundle#353]
Sorry for a question but I can't find information about one aspect of SonataMediaBundle. Can Sonata crop image file after I uploaded it? For example, I upload image 500*400 px and I want just crop it to something like 100*300 px with some polygon. How can I do this? Any ideas will be appreciated, thanks.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @m4a1fox
