### ISSUE TITLE
Implementing custom method in MediaAdminController

### ISSUE THREAD

**Issue by mariosanchez** [sonata-project/SonataMediaBundle#365]
I would like to implement a new method in MediaAdminController (src/Application/Sonata/MediaBundle/Controller/MediaAdminController.php).

I want to implement an image cropping script form my users to select an area of an image. 

My idea is to make a custom implementation of a new method to do this, resize the image with the crop info and rewrite the image. I don't know if its the best practice or is better to implement a service. I've no idea how to add my custom routes, I've tried to declare the route through annotations but I'm getting an error like this:

>There is no `_sonata_admin` defined for the controller >`Application\Sonata\MediaBundle\Controller\MediaAdminController` and the current >route `image_resize`

In fact can't find any documentantion about this or anyone who have tried.

Anyone have tried it? Any hint? Any idea?

Thank you :)

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @mariosanchez
