### ISSUE TITLE
Problem with Pagination of List Media Dialog

### ISSUE THREAD

**Issue by Hoannv** [sonata-project/SonataMediaBundle#376]
Hi,

I have problem with pagination in list media dialog as attached figure.

![screenshot from 2013-08-04 18 04 24](https://f.cloud.github.com/assets/1846777/906916/1a04b7a2-fcf6-11e2-9890-89c755f3eafb.png)

I don't find any document for showing pagination in dialog. Can you help me this issue?

Best Regards,
Hoan Nguyen

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @Hoannv
