### ISSUE TITLE
Error uploading non-image file to image provider

### ISSUE THREAD

**Issue by tiagojsag** [sonata-project/SonataMediaBundle#384]
The problem is that, on ImageProvider's doTransform, the imagineAdapter is being used to get size, width and height. This, ofc, fails if the file is not actually an image.

The doTransform is being called before the validate(), where the mime types and file extensions could be validated, so instead of getting a validation error for wrong file type, this throws a 500 error.

My proposed solution would be to wrap the content of ImageProvider's doTransform in a try-catch, similar to what's done in updateMetadata. However, I'd like some feedback from the devs on what's the best solution for this.

This bug can be easily reproducible on http://demo.sonata-project.org/ by trying to upload a txt file to a image type media.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @tiagojsag
