### ISSUE TITLE
sonata_media_type gives defaults that can't be removed

### ISSUE THREAD

**Issue by dTHQb** [sonata-project/SonataMediaBundle#405]
![question](https://f.cloud.github.com/assets/5469144/1198571/acfde73c-24fa-11e3-85f3-ad78a8f3cbe4.png)

How do I lose the "Binary content" line?

'label_render' = false And 'label' = false does not work... I can't find this in the documentation or in existing issues...

**Comment by krewetka** [comment]
This part of text is inserted inside `media_widgets.html.twig file`.

You can copy these file to your extended bundle  and remove unnecessary lines from there.

There are two lined to remove:

`<span type="label">{{ value.providerName|trans({}, 'SonataMediaBundle') }}</span> ~ {{ value.context }}` and

`<span type="label">{{ form.vars['provider']|trans({}, 'SonataMediaBundle') }} ~ {{ form.vars['context']|trans({}, 'SonataMediaBundle') }}</span>`

**Comment by GuraYaroslava** [comment]
@krewetka thank you!
