### ISSUE TITLE
Videos are not currently being displayed [Media Bundle Usage]

### ISSUE THREAD

**Issue by vihuvac** [sonata-project/SonataMediaBundle#410]
### Daily Motion, Youtube, Vimeo

I was including each media video into each post without any problems. After updating my packages in my composer file, this functionality stopped working.

Right now **instead of content**, the post displays this:

```
<% media 2, 'big' %>
```

Did you make any change that affect this functionality?

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @vihuvac
