### ISSUE TITLE
Image name is not updated when editing a media

### ISSUE THREAD

**Issue by MeuhMeuh** [sonata-project/SonataMediaBundle#415]
Hello,

I am using Sonata Media Bundle and its built-in provider sonata.media.provider.image to handle my images.
I have in my entity a simple field "image" that is handled by my entity form type using the widget "sonata_media_type".
Everything works, except that when I am uploading an image with the name "A", that I save my entity, and when I edit it to replace it with an image "B", the image data is replaced but the image name in the metadata is NOT replaced.

Is it a bug, or does it work as expected? And if so, how to "refresh" the media name each time we update it?

Thank you

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @MeuhMeuh
