### ISSUE TITLE
Variable "media_pool" does not exist

### ISSUE THREAD

**Issue by ibasaw** [sonata-project/SonataMediaBundle#429]
Variable "media_pool" does not exist in SonataMediaBundle:MediaAdmin:list.html.twig at line 21

when i try to load the media list after a composer update

**Comment by IonutPerfectWeb** [comment]
for anyone having this problem, be sure that you extend ```Sonata\MediaBundle\Controller\MediaAdminController``` not ```CrudController``` or ```MediaController```.
