### ISSUE TITLE
Add Media in Gallery Media List when adding a Gallery 

### ISSUE THREAD

**Issue by ConneXNL** [sonata-project/SonataMediaBundle#436]
When adding a gallery "/app_dev.php/admin/sonata/media/gallery/create", you have the option to add the medias and create new ones on the fly.

However: 
When you click Add New in the Media list, you get a popup and can select your media type
But after uploading the image, or the youtube file you are being redirected away from the Gallery Create page.

This can't be intended.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @ConneXNL
