### ISSUE TITLE
embedded forms error, sonata_type_model_list, error in JS events handler

### ISSUE THREAD

**Issue by filipc** [sonata-project/SonataMediaBundle#439]
I've discovered that embedded form is not handling correctly JS events (i.e. click).

Example implementation:
```php
 $formMapper
            ->add(
                'coverImage',
                'sonata_type_model_list',
                array('required' => false),
                array(
                    'placeholder' => 'No cover',
                    'provider' => 'sonata.media.provider.image',
                    'link_parameters' => array(
                        'context'  => 'document',
                    )
                )
            )
```
This creates field in form like this:

![1](https://f.cloud.github.com/assets/354073/1591565/3b42c668-52a8-11e3-9223-9f12c9e38ae8.jpg)

Let's call that "Admin A"

On click on "Manage" ("Zarządzaj"), modal shows up with list of media items and related filters (Media selector admin - called "Admin B").
![2](https://f.cloud.github.com/assets/354073/1591587/dc4058a0-52a8-11e3-8404-03cfb851f3ef.jpg)

When I click on ^ icon (to toggle visibility of filters section in modal) contents of media list ("Admin B") disappears, and instead of that contents of modal is replaced with content from below section ("Admin A"). During this operation JS Error appears related to ckeditor conflict with duplicated ID in document and all JS stops working.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @filipc
