### ISSUE TITLE
Symfony2 Sonata Media Bundle Custom Image Croping functionality

### ISSUE THREAD

**Issue by amanvarshney** [sonata-project/SonataMediaBundle#444]
It seems that Sonata Media has only two strategies when it comes to cropping/resizing the uploaded image, Sonata\MediaBundle\Resizer\SimpleResizer and Sonata\MediaBundle\Resizer\SquareResizer. Both these strategies are automatic, meaning that the users don't have a say in how they want the image to be resized/croppped.

I would like to give the user an option to select the portion of the image that is more relevant, kind like the jQuery Image Cropper library used by GenemuFormBundle, but I don't even know where to start. Will I need to create my own Admin class instead of using Sonata\MediaBundle\Admin\BaseMediaAdmin? Has anyone write a bundle that I can use? How do you manage your galleries usually?

![0qdxq](https://f.cloud.github.com/assets/1180539/1674979/ac4fd05e-5d01-11e3-9363-86a1b3c02f05.png)

**Comment by julien-maitan** [comment]
I know it's a bit late, but I wrote this extension a few years ago : https://github.com/julien-maitan/sonata-media-crop.
