### ISSUE TITLE
Generate public URL of media issue

### ISSUE THREAD

**Issue by hoannv** [sonata-project/SonataMediaBundle#452]
Hi,

I get an issue with generating media public URL.

$media->setContext('comment');
$provider = $this->get($media->getProviderName());
$provider->generatePublicUrl($media, 'smallthumbnail');  => <b>'/uploads/media/comment/0001/01/thumb_227_smallthumbnail.png'</b>

This link is wrong. It's missing "context".

The correct one should be '/uploads/media/comment/0001/01/thumb_227_<b>comment_</b>smallthumbnail.png'

pls help me resolve this issue

**Comment by isratmir** [comment]
{% path media.object, 'reference' %}
