### ISSUE TITLE
Incorrect image path when generating from SonataNewsBundle

### ISSUE THREAD

**Issue by ppounder** [sonata-project/SonataMediaBundle#453]
Hi there,

I have a standard install of SonataNewsBundle, with Media and Admin Bundle installed. I'm running Symfony 2.3.8 with Doctrine ORM.

I can't seem to view any of my images in the Admin when looking at my Media. I have correct permissions in my web/mybundlename/uploads/media..... directory

When I add the following into a news item: ```<% media 2, 'big' %>``` the image generates but doesn't display, when I firebug the image and it's path, it's path is /uploads/media/default/0001/01/thumb_2_default_big.png which doesn't display the image. If I add web/mybundlename/ before this the image works.

My config is as per documentation, how can I get the images to show correctly both in admin and the front end?

Regards
Paul

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @ppounder
