### ISSUE TITLE
Blurred images due to Resizer bug?

### ISSUE THREAD

**Issue by xaben** [sonata-project/SonataMediaBundle#480]
While trying to resize a 400x224 image to a 96px width constraint, the resizer creates a 95x53 image instead of the 96x54 expected.

And to make matters worse, the twig helper sets the width attribute, making the image 96px (browser scaled) which is very blurry.

What would be the way to fix this? Create a custom resizer? Fix twig helper to return actual thumbnail size? Revert to own <img> tag with path and no media attributes?

**Comment by xaben** [comment]
The problem is still there, but I found that my solution isn't perfect. Especially if the reference image is of a different size then the media (metadata). If anyone has any ideas how to fix this...

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
