### ISSUE TITLE
sonata_urlsafeid

### ISSUE THREAD

**Issue by emmanuel-tesson** [sonata-project/SonataMediaBundle#491]
Hi 
after the last upgrade of SonataMedia Bundle, ih ave got the error in SonataAdminBundle : 

An exception has been thrown during the rendering of a template ("Parameter "id" for route "admin_sonata_media_media_edit" must match "[^/]++" ("" given) to generate a corresponding URL.") in SonataMediaBundle:MediaAdmin:list_custom.html.twig at line 17.

My Config is Symfony 2.3.10

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @emmanuel-tesson
