### ISSUE TITLE
Cut file extension for files

### ISSUE THREAD

**Issue by Etheriq** [sonata-project/SonataMediaBundle#503]
I tried to save file by FileProvider but in my DB it saved without extension.
My code:
```php
<?php
// ...
$media = new Media();
 $file = new File($fileSrc);

$media->setBinaryContent($file->getRealPath());
$media->setProviderName('sonata.media.provider.file');
$media->setContext('files');
$this->mediaManager->save($media);

```

In DB in provider_reference field I have something like:
```txt
b4bf1f0d7456dd5f26b32a18d4de8607536d40f2.
```

With images I haven't problems.
What I do wrong?
Thanks in advance.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @Etheriq
