### ISSUE TITLE
Problem with sonata.media.manager.media service and doctrine_phpcr db_driver

### ISSUE THREAD

**Issue by lucasgranberg** [sonata-project/SonataMediaBundle#509]
I dont know if this is becouse of changes in #494 but I get 

```
Argument 2 passed to Sonata\\CoreBundle\\Model\\BaseManager::__construct()
must implement interface Doctrine\\Common\\Persistence\\ManagerRegistry,
instance of Sonata\\DoctrinePHPCRAdminBundle\\Model\\ModelManager given
```

when I try to use db_driver: doctrine_phpcr for sonata_media.

If I modify the sonata.media.manager.media like this:

```
<service id="sonata.media.manager.media" class="%sonata.media.manager.media.class%">
            <argument type="service" id="sonata.media.pool" />
            <argument type="service" id="doctrine_phpcr" />
            <argument>%sonata.media.media.class%</argument>
        </service>
```

(using doctrine_phpcr service instead of sonata.admin.manager.doctrine_phpcr)
It get past that problem but then I get

```
The class 'Application\Sonata\MediaBundle\Entity\Gallery' 
was not found in the chain configured namespaces
```

Why is it searching for an entity when I use doctrine_phpcr?

**Comment by kakoma** [comment]
Tried variations of all the suggestions here without much headway(including using the updated documentation https://sonata-project.org/bundles/media/master/doc/reference/installation.html); . 
Might re-attempt this later but for now,switched to doctrine_orm
