### ISSUE TITLE
Multiupload support

### ISSUE THREAD

**Issue by diimpp** [sonata-project/SonataMediaBundle#535]
Hey guys,

Significant feature, but MediaBundle seems to not support it.
There is some talks about it in google groups, was it implemented in some other way? Or patches are welcome? :)

Regards.

**Comment by estebannovo** [comment]
ok, but what I want to do is integrate this functionality to Bundle: [https://blueimp.github.io/jQuery-File-Upload/index.html](https://blueimp.github.io/jQuery-File-Upload/index.html) and such need to modify the edit form to add the corresponding html, which I have not been able, at the moment I'm trying to create a custom field to add the input file + buttons plugins, but without success so far

**Comment by jordisala1991** [comment]
Closing in favor of #1422
