### ISSUE TITLE
Use Media entity in API

### ISSUE THREAD

**Issue by Charlie-Lucas** [sonata-project/SonataMediaBundle#536]
Hello Im new on Sonata, i started a project with sonata media , admin and user bundle.

I explain you my problem:

I created an Entity "My Reference" with a relation ManyToOne with Application\Sonata\MediaBundle\Entity\Media and added other parameter.
Im trying to use api like /api/reference/{id}.{_format} .
I @Expose all my parameter without my relation and it works. 
I enabled the api from sonata media bundle and it works.
but i want use the Media Entity in my Reference Rest Api.
I have an error like : 

"ContextErrorException: Warning: Missing argument 1 for Proxies__CG__\Application\Sonata\MediaBundle\Entity\Media::setBinaryContent(), called in /Applications/MAMP/bin/mamp/fichiers/Sonata/sonata_project/vendor/jms/serializer/src/JMS/Serializer/Metadata/PropertyMetadata.php on line 89 and defined in /Applications/MAMP/bin/mamp/fichiers/Sonata/sonata_project/app/cache/dev/doctrine/orm/Proxies/__CG__ApplicationSonataMediaBundleEntityMedia.php line 216"

i know my code is wrong on my controller but i dont know how use this entity.

**Comment by dziurawy** [comment]
what is the solution? i have same error.

**Comment by Charlie-Lucas** [comment]
It's an old project (my first symfony project), take a look on[My project](https://github.com/Charlie-Lucas/ReferencesEngine) , dev branch maybe you will find your happiness.

**Comment by pauleau** [comment]
Sry for asking this, but I'm stuck trying to use Sonata Media Bundle API Posting. 
Would you give me some explanation about the request you send :s ? 
May I will find things in your code. 

My probleme in stack question if you want : 
https://stackoverflow.com/questions/45903974/api-post-to-sonata-media-bundle-symfony-3
