### ISSUE TITLE
Undeclared method

### ISSUE THREAD

**Issue by diphda** [sonata-project/SonataMediaBundle#551]
Hi
i have updated my app with composer and have a fatal error that seems a bug:

PHP Fatal error:  Class Sonata\MediaBundle\Block\MediaBlockService contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Sonata\BlockBundle\Block\BlockServiceInterface::validateBlock) 

this is my composer:
"require": {
    "php": ">=5.3.3",
    "symfony/symfony": "~2.4",
    "doctrine/orm": "~2.2,>=2.2.3",
    "doctrine/doctrine-bundle": "~1.2",
    "twig/extensions": "~1.0",
    "symfony/assetic-bundle": "~2.3",
    "symfony/swiftmailer-bundle": "~2.3",
    "symfony/monolog-bundle": "~2.4",
    "sensio/distribution-bundle": "~2.3",
    "sensio/framework-extra-bundle": "~3.0",
    "sensio/generator-bundle": "~2.3", 
    "friendsofsymfony/user-bundle": "1.3.*@dev", 
    "doctrine/doctrine-fixtures-bundle": "2.2.*",
    "sonata-project/admin-bundle": "dev-master",
    "sonata-project/doctrine-orm-admin-bundle": "dev-master", 
    "sonata-project/media-bundle": "dev-master",
    "sonata-project/jquery-bundle": "dev-master",
    "sonata-project/core-bundle": "dev-master"
  },

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
