### ISSUE TITLE
Youtube player_parameters width and height

### ISSUE THREAD

**Issue by moonraking** [sonata-project/SonataMediaBundle#556]
Setting width and height in player_parameters has no effect, i.e. the width and height is not overridden.

``` twig
{# /src/MyBundle/Recourse/mytwigfile.twig.html #}
{% media my_media_item, 'big' 
   with {
      'player_parameters': { 'height': '1000px', 'width':'700px' },
   }
%}
```

outputs

``` html
<iframe width="1024px" height="768px" src="\\youtube.com\blahblah" frameborder="0" allowfullscreen=""/>
```

and not

``` html
<iframe width="1000px" height="700px" src="\\youtube.com\blahblah" frameborder="0" allowfullscreen=""/>
```

The problem is with the order of the parameters in the array_merge on line 181 of sonata-project/media-bundle/Provider/YouTubeProvider.php

I think they should be more like this

``` php
....
// sonata-project/media-bundle/Provider/YouTubeProvider.php: Line 181
$player_parameters = array_merge(
    array(
        'width' => $box->getWidth(),
        'height' => $box->getHeight()
    ),
    $default_player_parameters,
    isset($options['player_parameters']) ? $options['player_parameters'] : array()
);
...
```

**Comment by OskarStark** [comment]
is this fixed in the current version?

**Comment by moonraking** [comment]
Hi Oskar,
I don't know. Line 191 still looks in the incorrect order to me, but I could be wrong.

Shane

**Comment by OskarStark** [comment]
thanks, but you dindn't use it right now?

**Comment by moonraking** [comment]
No. I have not tested it recently.

**Comment by ygr1k** [comment]
Hello everyone, this is not a bug.
The width and height values are taken from $box variable, which is formed in the method getBoxHelperProperties.
If you check it, you will understand that the values of the width can be specified like this:

{% media galMedia.media, 'product_gallery' with {'width':'540'} %}
