### ISSUE TITLE
Revision not showed

### ISSUE THREAD

**Issue by Filoz** [sonata-project/SonataMediaBundle#566]
Hi, 
It generate the correct list of revisions (audit enabled), but when I click on "show revision" nothing is showed.
![media revision](https://cloud.githubusercontent.com/assets/5341996/3209847/d367cf8c-ee8f-11e3-8784-c6880ec24f19.png)

Note: also the old version has this problem.
give a look to the demo: http://demo.sonata-project.org/admin/sonata/media/media/1/history?context=default

Bye

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
