### ISSUE TITLE
Imaginebundle 1.x integration

### ISSUE THREAD

**Issue by lucasgranberg** [sonata-project/SonataMediaBundle#573]
Is there any interest in bumping imaginebundle to 1.x? I have got it working without any tests/documentation just for my own purposes but I could do a PR if somebody helped me and gave "green light" that this is a good idea.

**Reasons I want to update:**
- I couldn't get my thumbnails generated correctly with the older versions. Probably something in my code.
- The liipImagineFilterAction for mediacontroller wouldn't be needed anymore. It didn't support my png files it seems.

**What I have done so far**

I started doing something in this issue:
https://github.com/sonata-project/SonataMediaBundle/issues/549

basically what I did was this:

``` php
//Sonata\MediaBundle\Thumbnail\LiipImagineThumbnail
    public function generatePublicUrl(MediaProviderInterface $provider, MediaInterface $media, $format)
    {
        $path = $provider->getReferenceImage($media);
        if ($format == 'reference') {
            return $provider->getCdnPath($path, $media->getCdnIsFlushable());
        } else {
            $path = $this->router->generate('liip_imagine_filter',array(
                'filter' => $format,
                'path'=>$provider->getCdnPath($path, $media->getCdnIsFlushable())
            ));
            return $path;
        }
    }
```

**Problems**
The problem is that the cdn path is forced upon all public urls in the ImageProvider by default as mentioned here: https://github.com/sonata-project/SonataMediaBundle/pull/550. The fix made there was to remove the cdn from the LiipImagineThumbnail class. To get my code to work I had to modify the ImageProvider to just output the path "as is" and not apply the cdn path. This would ofcourse cause a BC when the ImageProvider starts to behave differently.

I am not shure what would happen if the cdn path would be an url as the url would be fed to the imaginefilter.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by wadjeroudi** [comment]
This issue still exists.
Like said by benglass #issuecomment-46196156
The ImageProvider should use the CdnPath only if the format is reference, and lets the thumbnail provider decides what to return.
And the other problem is about the LiipImagineThumbnail class, generatePublicUrl uses the old liip routes.

**Comment by jordisala1991** [comment]
Let's move the liip imagine discussion to a unique issue: #994
