### ISSUE TITLE
Foreign key error when trying to delete media items that are still associated with any gallery

### ISSUE THREAD

**Issue by benglass** [sonata-project/SonataMediaBundle#576]
Using Doctrine ORM. Right now the way the mapping is set up there is no cascade of deletes from the Media to the GalleryHasMedia. This means that if you attempt to delete Media and there are still GalleryHasMedia entities pointing at it you get a foreign key error.

This should be corrected by changing this line to include 'remove' to cascade.

https://github.com/sonata-project/SonataMediaBundle/blob/master/DependencyInjection/SonataMediaExtension.php#L206

If you can confirm we aren't missing something here we will submit a PR.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.
