### ISSUE TITLE
LiipImagineBundle "dev-master" : Unable to generate a URL for the named route "_imagine_default_small" 

### ISSUE THREAD

**Issue by ibasaw** [sonata-project/SonataMediaBundle#578]
i got error with dev master LiipImagineBundle and SonataMediaBundle

An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "_imagine_default_small" as such route does not exist.")

In my router debug got only

```
liip_imagine_filter_runtime                               GET      ANY    ANY                       /media/cache/{filter}/rc/{hash}/{path}
liip_imagine_filter                                       GET      ANY    ANY                       /media/cache/{filter}/{path}
```

**Comment by gonzalovilaseca** [comment]
any news? I'm having same problem.

**Comment by gonzalovilaseca** [comment]
Just found the solution, will do a PR ASAP.

**Comment by gonzalovilaseca** [comment]
check if #720 solves the issue.
