### ISSUE TITLE
[RFC] PHPCR Support

### ISSUE THREAD

**Issue by rande** [sonata-project/SonataMediaBundle#603]
Add PR / Issue related to PHPCR Support.
- [x] https://github.com/sonata-project/SonataMediaBundle/pull/602 : this PR is about making PHPCR work in MediaBundle
- [ ] https://github.com/sonata-project/SonataMediaBundle/pull/582: Waiting for user reply
- [x] https://github.com/sonata-project/SonataMediaBundle/issues/509 << can be closed if #602 is finished
- [x] https://github.com/sonata-project/SonataMediaBundle/pull/537 (done in #796)
- [x] ~~https://github.com/sonata-project/SonataMediaBundle/pull/579~~
- [x] https://github.com/sonata-project/SonataMediaBundle/pull/311 << closed. superceded by #602
- [x] https://github.com/sonata-project/SonataMediaBundle/pull/604

This list try to summarize issues and PR related to the PHPCR support.  @dbu @dantleech  @benglass Can you help me on those ?

**Comment by core23** [comment]
Can we close this @rande ?

**Comment by jordisala1991** [comment]
Closing. There are some PHPCR code here. If this is still an issue feel free to reopen
