### ISSUE TITLE
user uploading picture

### ISSUE THREAD

**Issue by anooxy** [sonata-project/SonataMediaBundle#610]
I'm trying to create a form the user can use to add a profile picture:

    $user = $this->getUser();
        
        $builder = $this->createFormBuilder($user);
        $builder->add('media', 'sonata_media_type', array(
            'provider' => 'sonata.media.provider.image',
            'context' => 'user_picture',
        ))
        ->add('Upload', 'submit');

        $form = $builder->getForm();

        if($request->getMethod() == 'POST')
        {
            $form->handleRequest($request);

            $media = $form->getData();

            $user = $this->getUser();
            $media['media']->setTutor($user);

            $em = $this->getDoctrine()->getManager();
            $em->persist($media['media']);
            $em->flush();
        }

        return $this->render('SkooliUserBundle:Media:index.html.twig', array(
            'form' => $form->createView()
        ));

That code is giving me the following error:

    The form's view data is expected to be an instance of class Application\Sonata\MediaBundle\Entity\Media, but is an instance of class Doctrine\ORM\PersistentCollection. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class Doctrine\ORM\PersistentCollection to an instance of Application\Sonata\MediaBundle\Entity\Media.

My relationship needs to be one-to-many, a single user needs to have several user pictures and or other documents. On Media.orm.xml I got this:

        <many-to-one field="user"
                     target-entity="\XXX\Bundle\UserBundle\Entity\User"
                     inversed-by="media">
            <join-column
                    name="user_id"
                    referenced-column-name="id"
                    />
        </many-to-one>

And on my User.orm.yml:

    media:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            mappedBy: user
            cascade: ["persist"]

I don't understand what is the problem.

**Comment by zneel** [comment]
Hi @anooxy did you solve it? I have exactly the same issue
