### ISSUE TITLE
Error at editing image with Pixlr

### ISSUE THREAD

**Issue by vihuvac** [sonata-project/SonataMediaBundle#621]
Hello guys,

I am currently using CKEditor with SonataFormatterBundle but when I try to edit any image, I get the error like the displayed in the screenshot. Can someone help me with that? I followed the instructions from the [website](http://sonata-project.org/bundles/media/2-2/doc/reference/extra.html#ckeditor-integration).

![Pixlr Error](http://f.cl.ly/items/2R2A1d1H1d3b1H0M0H02/pixlr_edit_error.png%20.png)

Should I add or bear in mind any other additional config for it?

**Comment by core23** [comment]
Issue active? @epci @vihuvac

**Comment by jordisala1991** [comment]
Probably duplicated of #944 . Closing
