### ISSUE TITLE
Generated thumbnails naming

### ISSUE THREAD

**Issue by lologhi** [sonata-project/SonataMediaBundle#626]
Even with a media `name` field in the admin, the generated thumbnails are named following non configurable conventions : 

```
/media/uploads/default/0001/01/thumb_1_default_small.jpeg
/media/uploads/default/0001/01/thumb_1_default_searchlist.jpeg
/media/uploads/default/0001/01/thumb_1_default_tablet.jpeg
/media/uploads/default/0001/01/thumb_1_default_big.jpeg
...
```

As it's not really good for SEO, could we keep the specified filename into the thumbnail name ? Like : 

```
/media/uploads/default/0001/01/this-cat-is-really-cute-thumb_1_default_small.jpeg
/media/uploads/default/0001/01/this-cat-is-really-cute-thumb_1_default_searchlist.jpeg
/media/uploads/default/0001/01/this-cat-is-really-cute-thumb_1_default_tablet.jpeg
/media/uploads/default/0001/01/this-cat-is-really-cute-thumb_1_default_big.jpeg
...
```

I'll have a look to try to find where the thumbnail names are made.

**Comment by nlenkowski** [comment]
Any word on this? I've been having issues where uploaded pdf files receive an sha1 filename, see [my comment](https://github.com/sonata-project/SonataMediaBundle/issues/67#issuecomment-122372019)  on issue #67. It would be great to make file names configurable or able to be sluggified based on the original file name.

**Comment by lologhi** [comment]
I was not able to make my previous PR merged for half a year :sob: , so I haven't tried to work on it.

**Comment by nlenkowski** [comment]
Ooof, half a year! A shame your PR wasn't merged, this feature is quite the oversight for a media management bundle. Is it a code issue or no response from the main contributors?

**Comment by alrick** [comment]
hey!

Is there a way to implement this by extending a class or something?

**Comment by xmon** [comment]
Any news about this functionality?

in my view it is mandatory

**Comment by lologhi** [comment]
Maybe the solution is to summon @rande ? :loudspeaker: :stuck_out_tongue:

**Comment by xmon** [comment]
Perhaps a good idea @rande :smile:

**Comment by 84pixels** [comment]
@rande +1

**Comment by core23** [comment]
You can +1 on a comment without writing a new one @84pixels 
https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments
