### ISSUE TITLE
Error installing MediaBundle

### ISSUE THREAD

**Issue by iraklialaverdashvili** [sonata-project/SonataMediaBundle#632]
Hello, I am a Symfony programmer, and not very newbie. The point is that I need any upload bundle as soon as possible. As I had another Sonata-project bundles in my project, i decided to choose this one. I've spent 3-4 hours of my free time trying install SonataMediaBundle but without any result.

composer require sonata-project/media-bundle

  Problem 1
    - Installation request for sonata-project/media-bundle dev-master -> satisfiable by sonata-project/media-bundle[dev-master].
    - sonata-project/media-bundle dev-master requires sonata-project/classification-bundle ~2.3@dev -> no matching package found.
  Problem 2
    - sonata-project/media-bundle dev-master requires sonata-project/classification-bundle ~2.3@dev -> no matching package found.
    - symfony/framework-standard-edition 2.5.x-dev requires sonata-project/media-bundle dev-master -> satisfiable by sonata-project/media-bundle[dev-master].
    - Installation request for symfony/framework-standard-edition 2.5.x-dev -> satisfiable by symfony/framework-standard-edition[2.5.x-dev].

I had problems installing classification-bundle too.

In "composer.json" of the bundle I found this:

"require": {
"symfony/symfony": "~2.3",
"sonata-project/core-bundle": "~2.2",
"sonata-project/notification-bundle": "~2.2",
"sonata-project/easy-extends-bundle": "~2.1",
"sonata-project/doctrine-extensions": "~1.0",
"sonata-project/classification-bundle": "~2.3@dev",
"knplabs/gaufrette": ">=0.1.4",
"imagine/Imagine": "_@stable",
"kriswallsmith/buzz": "0._",
"friendsofsymfony/rest-bundle": "~1.1",
"jms/serializer-bundle": "~0.11",
"nelmio/api-doc-bundle": "~2.4",
"sonata-project/intl-bundle": "~2.2"
},
"require-dev": {
"sonata-project/doctrine-orm-admin-bundle": "~2.3@dev",
"sonata-project/admin-bundle": "~2.3@dev",
"sonata-project/formatter-bundle": "~2.2@dev",
"sonata-project/core-bundle": "~2.2@dev",
"amazonwebservices/aws-sdk-for-php": "~1.5",
"sonata-project/seo-bundle": "~1.1",
"doctrine/mongodb-odm": "~1.0@dev",
"jackalope/jackalope-doctrine-dbal": "~1.1"
},

----- Also here is a list from packagist.org

Requires
    imagine/imagine: _@stable
    knplabs/gaufrette: >=0.1.4
    kriswallsmith/buzz: 0._
    sonata-project/notification-bundle: ~2.2
    sonata-project/easy-extends-bundle: ~2.1
    sonata-project/doctrine-extensions: ~1.0
    friendsofsymfony/rest-bundle: ~1.1
    nelmio/api-doc-bundle: ~2.4
    jms/serializer-bundle: ~0.11
    symfony/symfony: ~2.3
    sonata-project/core-bundle: ~2.2
    sonata-project/intl-bundle: ~2.2
    sonata-project/classification-bundle: ~2.3@dev

Requires (Dev)
    sonata-project/formatter-bundle: ~2.2@dev
    amazonwebservices/aws-sdk-for-php: ~1.5
    sonata-project/seo-bundle: ~1.1
    doctrine/mongodb-odm: ~1.0@dev
    sonata-project/doctrine-orm-admin-bundle: ~2.3@dev
    sonata-project/admin-bundle: ~2.3@dev
    sonata-project/core-bundle: ~2.2@dev
    jackalope/jackalope-doctrine-dbal: ~1.1

And some of these bundles require other bundles as well. 
Is it normal? 

P.S. SonataAdminBundle and the SonataDoctrineORMAdminBundle which are required in offitial documentation I already have.

Anyone using this bundle, can share his composer.json please?
Or any link of a full installation manual, with dependencies included.

Thanks,

**Comment by SirTadpole** [comment]
Hi ! i have the same trouble with my symfony 2.6 project.

When i'm trying to install sonata-project/doctrine-mongodb-admin-bundle : 

  Problem 1
    - Installation request for sonata-project/doctrine-mongodb-admin-bundle ~2.3 -> satisfiable by sonata-project/doctrine-mongodb-admin-bundle[2.3.0].
    - sonata-project/doctrine-mongodb-admin-bundle 2.3.0 requires doctrine/mongodb-odm-bundle 3.0.*@dev -> no matching package found.
  Problem 2
    - sonata-project/doctrine-mongodb-admin-bundle 2.3.0 requires doctrine/mongodb-odm-bundle 3.0.*@dev -> no matching package found.
    - symfony/framework-standard-edition 2.6.x-dev requires sonata-project/doctrine-mongodb-admin-bundle ~2.3 -> satisfiable by sonata-project/doctrine-mongodb-admin-bundle[2.3.0].
    - Installation request for symfony/framework-standard-edition 2.6.x-dev -> satisfiable by symfony/framework-standard-edition[2.6.x-dev].

**Comment by lucasgranberg** [comment]
Do you have doctrine/mongodb-odm-bundle in your composer? Can you copy your composer.json to this thread?

**Comment by SirTadpole** [comment]
I don't have doctrine/mongodb-odm-bundle in my composer.json, and when i try to add it i got this error : 

**(...)# composer require doctrine/mongodb-odm-bundle**
  Problem 1
    - doctrine/mongodb-odm-bundle v2.2.1 requires doctrine/mongodb-odm >=1.0.0-beta5,<1.1-dev -> no matching package found.
    - doctrine/mongodb-odm-bundle v2.2.0 requires doctrine/mongodb-odm 1.0.0-BETA5 -> no matching package found.
    - Installation request for doctrine/mongodb-odm-bundle ~2.2 -> satisfiable by doctrine/mongodb-odm-bundle[v2.2.0, v2.2.1].

``` yamel
My composer.json file :
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0.12",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "sonata-project/admin-bundle": "~2.3",
        "sonata-project/doctrine-orm-admin-bundle": "~2.3",
        "sonata-project/easy-extends-bundle": "~2.1",
        "sonata-project/user-bundle": "~2.2",
        "sonata-project/media-bundle": "~2.3"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3"
    },
```

**Comment by lucasgranberg** [comment]
never worked with mongodb but I suppose it needs doctrine/mongodb-odm also.
