### ISSUE TITLE
Problem with the new tabsystem in 2.4

### ISSUE THREAD

**Issue by lucasgranberg** [sonata-project/SonataMediaBundle#634]
I have Sonata Admin and Media set to "2.4.*@dev" and I get this error. I tried looking up the problem and I noticed that the request is empty in the [SonataAdminBundle:CrudController](https://github.com/sonata-project/SonataAdminBundle/blob/master/Controller/CRUDController.php#L592).

```

Impossible to access a key ("default") on a boolean variable ("") in
SonataAdminBundle:CRUD:base_edit_form.html.twig at line 56
```
The error comes from [this](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/base_edit_form.html.twig#L56) file becouse the admin.formtabs variable is set to false.

**Comment by skobkin** [comment]
Same problem.

Just installed MediaBundle. Trying to add files to my entity:
Entity:

```php
    /**
     * @var Media
     *
     *
     * @ORM\ManyToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media", cascade={"all"}, fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="media_id")
     */
    private $file;
```

Admin:

```php
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            // ...
            ->add('file', 'sonata_type_model_list', [], [
                'link_parameters' => [
                    'context' => 'client_build',
                    'provider' => 'sonata.media.provider.file',
                ]
            ])
            // ...
        ;
    }
```

When I trying to add new file in the admin dashboard, I get this error.

```
PHP 5.6.8-pl0-gentoo
"symfony/symfony": "2.6.*", [2.6.6]
"sonata-project/core-bundle": "dev-master",
"sonata-project/intl-bundle": "~2.2", [2.2.1]
"sonata-project/admin-bundle": "dev-master",
"sonata-project/doctrine-orm-admin-bundle": "dev-master",
"sonata-project/easy-extends-bundle": "dev-master",
"sonata-project/user-bundle": "dev-master",
"sonata-project/datagrid-bundle": "dev-master",
"sonata-project/classification-bundle": "dev-master",
"sonata-project/media-bundle": "dev-master",
```

**Comment by ronanguilloux** [comment]
Same problem on `symfony/symfony: 2.5.12`

**Comment by webdevilopers** [comment]
Any news on this? I still seem to have this problem with current `dev-master`s.

**Comment by webdevilopers** [comment]
Correcting myself. The error message only appeared when opening the AJAX url in a new tab.
When looking at the console and the HTML Response it was a permission problem with `mkdir`.

So far everything seems to work fine!

**Comment by lucasgranberg** [comment]
Ill close this issue as I don't think its an issue anymore and I can't check it out right now.

**Comment by OskarStark** [comment]
:+1:
