### ISSUE TITLE
Error connect with SonataDoctrineMongoDBAdminBundle

### ISSUE THREAD

**Issue by spolischook** [sonata-project/SonataMediaBundle#642]
We have SonataMediaBundle version 2.2.3 And after update SonataDoctrineMongoDBAdminBundle to version 2.2.*@dev I have error.
MediaBundle inject document manager https://github.com/sonata-project/SonataMediaBundle/blob/2.2/Resources/config/doctrine_mongodb_admin.xml#L45 and in 
https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/2.2/Model/ModelManager.php#L39 ManagerRegistry needed.

**Comment by core23** [comment]
We don't support this branch anymore. Please check this issue against the latest stable / master version.

Feel free to create a new issue following the issue template, if this error ist still present.
