### ISSUE TITLE
[Provider][ErrorElement]Translating violation messages

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataMediaBundle#655]
I need to get translated validation messages (IE for [FileProvider](https://github.com/sonata-project/SonataMediaBundle/blob/01a776d86299e285cf91b34d9e2b6140db9c6e6d/Provider/FileProvider.php#L387)) as in [Symfony constraints](https://github.com/symfony/symfony/blob/842cba1d0cf50b69aee925cce12c57f8b8591e21/src/Symfony/Component/Validator/Constraints/File.php#L49). I was thinking how to achieve this, but I don't know if the only way is to inject the translator component into Provider or in the best case, reuse the Symfony constraints (when exists).
Any clue?
I could do a PR about this feature.
Thanks in advance.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
