### ISSUE TITLE
MediaBlockService returned values

### ISSUE THREAD

**Issue by nicolasricci** [sonata-project/SonataMediaBundle#665]
Hi,
Any reason to return the mediaId instead of the full media object?
https://github.com/sonata-project/SonataMediaBundle/blob/2.3/Block/MediaBlockService.php#L178

It would be more convenient to get the full object to access properties in the block, wouldn't it?

**Comment by core23** [comment]
IMHO we use the mediaId to persist it to the database.

**Comment by nicolasricci** [comment]
@core23 sorry for the rather late time to reply ... I have been confronted to a similar issue in a recent project so I thought I would update my thoughts on this.
My user case is that I want to display the media in a different way according to its `providerName` (a file would for instance be rendered differently than an image).
To do this I would like to override the `block_media.html.twig` with a condition such as 
```
{% if attribute(media, 'providerName') == 'sonata.media.provider.file' %}
    display something
{% else %}
    display something else
{%endif%}
```
However because only the mediaId is returned in the execute method I don't have access to the full Media object.

https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Block/MediaBlockService.php#L149

Hence my initial question from 3 years ago 😄
