### ISSUE TITLE
simpleResizer::getBox() error

### ISSUE THREAD

**Issue by ragusa87** [sonata-project/SonataMediaBundle#667]
I have an error rendering video on SonataAdmin.

> An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 2 passed to Sonata\MediaBundle\Resizer\SimpleResizer::getBox() must be an array, boolean given

I found out that the format `admin_big` should be configurated to avoid this exception.

Using: 
- SonataAdmin dev-master 069e610d4d729608bd8fcb03647529cb252993ef
- SonataMedia dev-master e1cdec9fd9bde05bb4d4c1ea4e1f0e9fff6f1a7c
- Symfony 2.5.5 2aef97bbc95d0c4ae63537cca81bd6d984427d81

See my comment on issue #145 for more informations.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
