### ISSUE TITLE
GalleryHasMediaRepository ambiguous

### ISSUE THREAD

**Issue by calinpristavu** [sonata-project/SonataMediaBundle#670]
Hello,

Composer throws a warning during update:

> Warning: Ambiguous class resolution, "Sonata\MediaBundle\PHPCR\GalleryHasMediaRepository" 
> was found in both "/home/evodev/apps/shared/vendor/sonata-project/media-bundle/
> PHPCR/BaseGalleryRepository.php" and "/home/evodev/apps/shared/vendor/sonata-project/
> media-bundle/PHPCR/BaseGalleryHasMediaRepository.php", the first will be used.

Both classes have the same name and same namespace.

My current relevant setup:

            "name": "sonata-project/media-bundle",
            "version": "2.3.0",
            "source": {
                "type": "git",
                "url": "https://github.com/sonata-project/SonataMediaBundle.git",
                "reference": "1a1e89f5a6daf586969be210ed41e1b38aba7ac2"
            },

Should the namespace / classname be changed?

**Comment by desarrolla2** [comment]
Was fixed here https://github.com/sonata-project/SonataMediaBundle/commit/574d5935068c34646595ed35ae2d7cfb92900718, but not integrated into 2.3.x branch. @rande do you want that i create a PR?

Regards!

**Comment by Th3Mouk** [comment]
+1 @rande

**Comment by libertogimenez** [comment]
+1

**Comment by Th3Mouk** [comment]
@rande you can close it : https://github.com/sonata-project/SonataMediaBundle/commit/cf29ecfa3396c21978210abcecef436b40b04c1d
