### ISSUE TITLE
Use "liip_imagine" instead of "sonata.media.adapter.image.gd"

### ISSUE THREAD

**Issue by nicolas-brousse** [sonata-project/SonataMediaBundle#675]
Hi all,

I have a little question and I haven't found his answer.

You always use `sonata.media.adapter.image.gd` when you need access the liip imagine library.
Why you don't use directly `liip_imagine` to access the configured imagine driver?

Maybe I'm in wrong but if I want to use Imagick I must write all the providers configs to use `sonata.media.adapter.image.imagick`.

**Comment by MM-Psiiirus** [comment]
if i am right the media bundle GD in compibation with the resizer so you could just add a new service with loads the SimpleResiter with an imagick adapter ...would be like this

services.yml
~~~~
services:
    sonata.media.resizer.custom_imagick:
        class: "%sonata.media.resizer.simple.class%"
        arguments: [ "@sonata.media.adapter.image.imagick" , "%sonata.media.resizer.simple.adapter.mode%" , "@sonata.media.metadata.proxy"]
~~~

config.yml
~~~~
sonata_media
    providers:
        image:
            resizer: sonata.media.resizer.custom_imagick

~~~~
