### ISSUE TITLE
Validation depend to AdminBundle 

### ISSUE THREAD

**Issue by Shine-neko** [sonata-project/SonataMediaBundle#680]
Hello, 

I'm not use AdminBundle. So I have an error

```
Attempted to load class "InlineConstraint" from namespace "Symfony\Component\Validator\Constraints\Sonata\AdminBundle\Validator\Constraints".
Did you forget a "use" statement for another namespace?

```

see https://github.com/sonata-project/SonataMediaBundle/blob/master/Resources/config/validation.xml#L13

**Comment by Shine-neko** [comment]
@rande  ?

**Comment by rande** [comment]
Yes, it is an issue.

**Comment by LeoBenoist** [comment]
+1

**Comment by rande** [comment]
@LeoBenoist the current master fix this issue.

**Comment by skobkin** [comment]
Very needed in ~2.3. Can't install dev-master now.

**Comment by wawneeds** [comment]
I agree with @LeoBenoist and @skobkin, please include in 2.3

**Comment by Renrhaf** [comment]
Can you please give us the fix for this issue ? or some explanations ? Thanks :)

**Comment by Floyd25** [comment]
The fix would be, to include Validations from CoreBundle and not from AdminBundle. At least I think so.

**Comment by LeoBenoist** [comment]
Will this be tagged in 2.3 ?

**Comment by ruscon** [comment]
+1 tag ?

**Comment by Renrhaf** [comment]
+1

**Comment by sidz** [comment]
God Damn guys, could you PLEASE merge this damn fix into 2.3 branch!

I use only media bundle, and I don't want to install dev-master because it's require admin bundle, datagrid bundle and etc.

PLEEEEEEEEEEEEEEEEEEEEEEEEEASE!

**Comment by seltzlab** [comment]
+1

**Comment by sidz** [comment]
@seltzlab it's already merged:
https://github.com/sonata-project/SonataMediaBundle/pull/916

**Comment by seltzlab** [comment]
thanks @sidz
