### ISSUE TITLE
Tight coupling with other bundles

### ISSUE THREAD

**Issue by koemeet** [sonata-project/SonataMediaBundle#684]
Hi,

I wanted to use this bundle because it has some nice features out of the box. But I had to step down because of it's tight coupling with other bundles, such as `SonataClassificationBundle`. I am forced to use that for managing classification. But this bundle should only focus on the `Media` part and make integrations optional in my opinion.

For example composer will download 6+ dependencies only for using the media bundle.

If it is not the intention for this bundle to be isolated and loosley coupled than this issue could be closed I guess.

**Comment by phansys** [comment]
I agree with your point @steffenbrem, but for now it seems to be intended to be coupled. See #663.

**Comment by core23** [comment]
Should be fixed with #1086

**Comment by jordisala1991** [comment]
Also in #1201 Closing
