### ISSUE TITLE
Could not remove the "default/0001/01/70d43d74fb22538adbdc981eb6b6e3e4b318dca6.png" key

### ISSUE THREAD

**Issue by balvirsingh** [sonata-project/SonataMediaBundle#685]
Hi,

In my project we are using this bundle for some file uploading functionality, I dont have much knowledge about this, before it was working fine but I am facing this error. When I update new image then it works fine but when update same image with new upload again then this error come. I tried to solve it but unable to find the issue.

please help to resolve this issue.

Could not remove the "default/0001/01/70d43d74fb22538adbdc981eb6b6e3e4b318dca6.png" key.

I saw it gives exception from this file.
/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php

/**
 * Deletes the file matching the specified key
 *
 * @param string $key
 * @throws \RuntimeException when cannot read file
 *
 * @return boolean
 */
public function delete($key)
{
    $this->assertHasFile($key);

    if ($this->adapter->delete($key)) {
        return true;
    }

    throw new \RuntimeException(sprintf('Could not remove the "%s" key.', $key));
}

//In form type file code 

->add('foto', 'sonata_media_type', array(
                 'required' => false,
                 'label' => 'foto',
                 'provider' => 'sonata.media.provider.image',
                 'context'  => 'default',
            ))

![snapshot332](https://cloud.githubusercontent.com/assets/5753046/5557089/e3715062-8d16-11e4-8efc-51cea04de619.png)

**Comment by IonutPerfectWeb** [comment]
@balvirsingh  I had the same error, fixed by doing chmod 0777 -R on upload folder. Hope this helps

**Comment by Soullivaneuh** [comment]
Seems to be a rights issue as @IonutPerfectWeb said. Closing it.
