### ISSUE TITLE
safeurl_id

### ISSUE THREAD

**Issue by remyma** [sonata-project/SonataMediaBundle#689]
I try to use sonata-media with odm but I have this issue while trying to list medias.

An exception has been thrown during the rendering of a template ("Parameter "id" for route "admin_sonata_media_media_edit" must match "[^/]++" ("" given) to generate a corresponding URL.") in SonataMediaBundle:MediaAdmin:inner_row_media.html.twig at line 19.

Everithing works fine with orm.
With odm it fails on sonata_urlsafeid filter.

I saw some related issues:
sonata-project/SonataMediaBundle#495
sonata-project/SonataMediaBundle#491

But they suggets to use doctrine 2.4 and its not workin on my side.

Please help ;-)

**Comment by pstephenson02** [comment]
@remyma Were you ever able to find a solution/workaround for this? I just ran into this problem today...

**Comment by remyma** [comment]
No, I finally switched to orm... Sorry

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
