### ISSUE TITLE
Customs provider error

### ISSUE THREAD

**Issue by TeoGoddet** [sonata-project/SonataMediaBundle#698]
When you try to create a custom provider following the [documentation](http://sonata-project.org/bundles/media/2-2/doc/reference/creating_a_provider_class.html) some abstact methods are not implemented. And this is not how to implements and what are they doind in in the documentation.

"contains 7 abstract methods and must therefore be declared abstract or implement the remaining methods (Sonata\MediaBundle\Provider\BaseProvider::doTransform, Sonata\MediaBundle\Provider\MediaProviderInterface::getReferenceFile, Sonata\MediaBundle\Provider\MediaProviderInterface::generatePublicUrl, ...)"

**Comment by core23** [comment]
Can you update the docs?
