### ISSUE TITLE
Format dropdown in gallery block is initially empty

### ISSUE THREAD

**Issue by blaues0cke** [sonata-project/SonataMediaBundle#713]
The format dropdown is empty when I create a new block. When I try to edit the block after I saved it, everything works fine.

![12_02_2015_4625_616_350](https://cloud.githubusercontent.com/assets/5159398/6172967/a1816126-b2e4-11e4-9e88-18492405eb7e.png)

**Comment by core23** [comment]
Can you please check, if this issue is related to this bundle @blaues0cke 

Maybe this https://github.com/sonata-project/SonataPageBundle/pull/579 will close your issue.

**Comment by jordisala1991** [comment]
Seems related more to page-bundle than to media-bundle.

Also almost 2 years without amswering @core23 question.

Closing for now. If you still having this issue, please ping me to reopen, or post the issue on the page-bundle.
