### ISSUE TITLE
Progressive media image option

### ISSUE THREAD

**Issue by yanict** [sonata-project/SonataMediaBundle#729]
it would be more than interesting to have a "progressive" option on the JPG media images.
is there anyway to implement that ?
thanks

**Comment by erlelila** [comment]
Hi guys,

there are some news on that issue?
How we can save progressive jpeg with sonata media?
Thanks

**Comment by yanict** [comment]
unfortunately I didn't find any solution yet and I have no idea if the Sonata team thinks about developing that feature soon.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
