### ISSUE TITLE
MediaAdminController::render() Problem

### ISSUE THREAD

**Issue by niepi** [sonata-project/SonataMediaBundle#731]
Hi,

I installed the MediaBundle based on the docu but when I open the actions from the Dashboard I get the following Error:

```Runtime Notice: Declaration of Sonata\MediaBundle\Controller\MediaAdminController::render() should be compatible with Sonata\AdminBundle\Controller\CRUDController::render($view, array $parameters = Array, Symfony\Component\HttpFoundation\Response $response = NULL, Symfony\Component\HttpFoundation\Request $request = NULL)```

Do have any idea what the problem could be?

**Comment by lucasgranberg** [comment]
Probably becouse you are rocking sonata admin 2.4 and sonata media 2.3? They moved some stuff over to core for 2.4.

**Comment by niepi** [comment]
thx, that was the problem.

**Comment by malutanpetronel** [comment]
so we should use 
"sonata-project/media-bundle": "dev-master",
instead of 
"sonata-project/media-bundle": "^2.3",
with symf
?

**Comment by dvapelnik** [comment]
Can someone show example part of composer.json with correct configuration usage of "sonata-project/media-bundle" for uploading files into server and selecting files from uploaded with ckeditor?

**Comment by lucasgranberg** [comment]
Have you tried the sonata sandbox?
https://github.com/sonata-project/sandbox
https://github.com/sonata-project/sandbox/blob/2.3/composer.json

**Comment by dvapelnik** [comment]
@lucasgranberg I'm using `"sonata-project/admin-bundle": "dev-master"` and cannot install `"sonata-project/media-bundle": "dev-master"`:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sonata-project/media-bundle dev-master -> satisfiable by sonata-project/media-bundle[dev-master].
    - sonata-project/media-bundle dev-master requires sonata-project/classification-bundle ~2.3 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
With `sonata-admin` `~2.3,<2.4` all good but i have troubles with my stable code

Can I correct install `"sonata-project/media-bundle": "dev-master"`?

**Comment by dvapelnik** [comment]
Solution of my problem is installing dependencies

**Comment by maciejszpyra** [comment]
dvapelnik what exactly did you do?

**Comment by dvapelnik** [comment]
@maciejszpyra I don't remember :cry: 
try to check all dependencies of bundle and manually install they

**Comment by maciejszpyra** [comment]
@dvapelnik It worked! Thank you!

**Comment by dvapelnik** [comment]
@maciejszpyra  np :stuck_out_tongue_winking_eye: can you write more about your solution for other people?

**Comment by kaizokou** [comment]
Same error here 

`Runtime Notice: Declaration of Sonata\MediaBundle\Controller\MediaAdminController::render() should be compatible with Sonata\AdminBundle\Controller\CRUDController::render($view, array $parameters = Array, Symfony\Component\HttpFoundation\Response $response = NULL, Symfony\Component\HttpFoundation\Request $request = NULL)`


in the composer.json

        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "sonata-project/media-bundle": "^2.3"

@maciejszpyra  @dvapelnik @niepi  can you explain how you fixed this ? Thanks.

**Comment by maciejszpyra** [comment]
Try   "sonata-project/media-bundle": "dev-master",

**Comment by kaizokou** [comment]
@maciejszpyra thanks for the answer.
I did change my composer.json with 
`"sonata-project/media-bundle": "dev-master" `

But first I had to change minimum-stability from stable to dev which exploded my PHP memory limit and changed many of my package. Anyway, I tried to see if this solve something, but after executing composer update  I have the following error 

`The service "sonata.media.admin.media" has a dependency on a non-existent service "sonata.classification.manager.category". `

any idea of what happened ? Is this possible to tell composer to dowload the dev version only for sonata-project/media-bundle but not for all my other package ?

**Comment by kaizokou** [comment]
Got the answer about using maximun of stable version package in composer 

 "prefer-stable": true,

But this doesn't solve my problem with sonata bundles.

**Comment by maciejszpyra** [comment]
I don't remember exactly which bundles I installed but try to open sonata-media bundle composer.json and try to  install dependencies yourself with composer. I think it was issue with classification bundle .

**Comment by kaizokou** [comment]
ok so the tricks is  "sensio/generator-bundle"

you need to downgrade it to 2.3 version. 
it's tricky because it's under the require-dev section.
here is a composer.json that is working 




   ```
     "sonata-project/admin-bundle": "^2.3",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "sonata-project/media-bundle": "^2.3"


    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "symfony/phpunit-bridge": "~2.7"
    },
```

**Comment by Avtonom** [comment]
very disappointed that the installation "sonata-project/media-bundle" forces to return to the "sensio/generator-bundle": "~2.3".

Version ~3.0 is already loved by all
