### ISSUE TITLE
Critical: blocks log in screen: Duplicate key-sequence

### ISSUE THREAD

**Issue by scasei** [sonata-project/SonataMediaBundle#732]
An exception has been thrown during the rendering of a template ("[ERROR 1877] Element '{urn:oasis:names:tc:xliff:document:1.2}trans-unit': Duplicate key-sequence ['form.label_category'] in key identity-constraint '{urn:oasis:names:tc:xliff:document:1.2}K_unit_id

File: SonataMediaBundle.de.xliff
Keys: form.label_category, form.label_provider_reference

**Comment by mrjingles** [comment]
Will be fixed with #738.
