### ISSUE TITLE
Conflict between SonataMediaBundle and IvoryOrderedFormBundle

### ISSUE THREAD

**Issue by ruscon** [sonata-project/SonataMediaBundle#744]
Links on other tickets
https://github.com/egeloen/IvoryOrderedFormBundle/issues/11
SonataMediaBundle https://github.com/sonata-project/SonataMediaBundle/issues/734

**Comment by austinh** [comment]
+1 I am having this issue as well.

**Comment by Soullivaneuh** [comment]
Do you have any proposition to solve it?

**Comment by Soullivaneuh** [comment]
@ruscon Did #3714 solved your issue?

**Comment by ruscon** [comment]
Can't check in this time.
