### ISSUE TITLE
API postProviderMediumAction validation errors

### ISSUE THREAD

**Issue by ruscon** [sonata-project/SonataMediaBundle#747]
```
"sonata-project/media-bundle": "~2.3",
"nelmio/api-doc-bundle": "dev-master",
"jms/serializer-bundle": "@dev",
```

![json respnse](https://api.monosnap.com/rpc/file/download?id=6YOPWlkH1TqQWASqHQeucwFGWJTD6l)

![form profile](https://api.monosnap.com/rpc/file/download?id=AJlPfkkfaCVgkMxDUoapiJgVKtt3MO)

**Comment by ruscon** [comment]
ping ?

**Comment by ruscon** [comment]
ping ?

**Comment by ruscon** [comment]
ping...

**Comment by bodnar1212** [comment]
Hello! Help me please. How you resolve this issues??
