### ISSUE TITLE
getMediaBuilder options parameter

### ISSUE THREAD

**Issue by nicolasricci** [sonata-project/SonataMediaBundle#752]
What about adding an options parameter to the getMediaBuilder method (https://github.com/sonata-project/SonataMediaBundle/blob/master/Block/MediaBlockService.php#L143)
My issue was I could not pass a specific context to a custom block so I had to copy the method in my class and add the following code

`$fieldDescription->setOption('link_parameters', array('context' => 'my_context'));`

It would nice if it could be passed as a parameter to the method instead.

**Comment by core23** [comment]
Insteaf of improving this method, we should work on this: https://github.com/sonata-project/SonataBlockBundle/issues/244

**Comment by nicolasricci** [comment]
@core23 ok this makes more sense indeed, closing this one
