### ISSUE TITLE
Mass import without category is broken

### ISSUE THREAD

**Issue by julien-maitan** [sonata-project/SonataMediaBundle#767]
Trying to import multiple medias using sonata:media:add-multiple command lead to a doctrine exception.

```
cat ../test-file.csv| php app/console sonata:media:add-multiple --delimiter=";"
 > 3 - bmp1xxzDY
A managed+dirty entity default can not be scheduled for insertion. : ["sonata.media.provider.file","default","\/tmp\/bmp3lqDyE"]
An exception occurred while executing 'INSERT INTO classification__context (name, enabled, created_at, updated_at, id) VALUES (?, ?, ?, ?, ?)' with params ["default", 1, "2015-05-20 16:32:39", "2015-05-20 16:32:39", "default"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'default' for key 'PRIMARY' : ["sonata.media.provider.file","default","\/tmp\/bmp4TxX7j"]
Done!
```

Here is the content of test-file.csv

```
"providerName";"context";"binaryContent"
"sonata.media.provider.file";"default";"/tmp/bmp1xxzDY"
"sonata.media.provider.file";"default";"/tmp/bmp3lqDyE"
"sonata.media.provider.file";"default";"/tmp/bmp4TxX7j"
```

I issued the same bug trying import different media using the notification bundle and a consumer with doctrine backend. On the first iteration, all is OK, but on the second iteration, the second file produce the error. I've found a workaround for my use case, loading the category related to the media context first, and setting it directly on the media.

"sonata-project/media-bundle",  "version": "dev-master"

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.
