### ISSUE TITLE
Deleting Media-Entity throws RuntimeException

### ISSUE THREAD

**Issue by Floyd25** [sonata-project/SonataMediaBundle#772]
When deleting ONE Doctrine Entity (Type Media), sonata 2.3.1 throws a RuntimeException:

WARNING - rmdir(/srv/apache2/htdocs/uploads/media2/grouplogo/0001/01): Directory not empty
Context: {"type":2,"file":"/srv/apache2/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/Local.php","line":132,"scream":24565} 

CRITICAL - Uncaught PHP Exception RuntimeException: "Could not remove the "grouplogo/0001/01/" key." at /srv/apache2/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php line 172
Context: {"exception":"Object(RuntimeException)"} 

There's something quite strange going on. Instead of only deleting the ONE entity, sonata is trying to delete the whole folder. Of course that's not working because there are other files / entities stored there as well. Question is: Why?

**Comment by Floyd25** [comment]
Found the problem:

I was using the Media-Object that was delivered by Doctrine through a relation.

Failing variant:
$mediaObject = $entity->getMedia();
$doctrineEntityManager->remove($mediaObject);

Working:
$media = $sonataMediaManager->findOne($entity->getMedia()->getId());
$sonataMediamanager->delete($media);


But why?

**Comment by DracoBlue** [comment]
Which type of class is `$mediaObject` and `$sonataMediaManager` (I cannot find findOne-Method on Sonatas MediaManager class in the source code)?

**Comment by jordisala1991** [comment]
Duplicated of #247 

Closing. I am trying to unify discussions, if you think this is not related, please ping me to reopen.
