### ISSUE TITLE
Validation without Sonata AdminBundle unusable in 2.3.x

### ISSUE THREAD

**Issue by Floyd25** [sonata-project/SonataMediaBundle#776]
While the Validation still requires AdminBundle to work in 2.3.x Sonata is complete useless without AdminBundle. I cannot use 2.4.x @ dev in production. Please backport the fix to 2.3.x stable!

**Comment by core23** [comment]
We don't support this branch anymore. Please check this issue against the latest stable / master version.

Feel free to create a new issue following the issue template, if this error ist still present.
