### ISSUE TITLE
Add image icons not redering correctly

### ISSUE THREAD

**Issue by desarrolla2** [sonata-project/SonataMediaBundle#778]
When i try to add new images, the icons will be bad rendered as you can see here

![Image](https://lh4.googleusercontent.com/-5I-G_s3wO-g/VWxm0zQh_SI/AAAAAAAAG24/UuUcRKNwUF8/w256-h94-no/Screenshot%2Bfrom%2B2015-06-01%2B16%253A05%253A26.png)

I found that error is that image url is rendered like this

```html
<img src="/data:image[...]"
```

so the / at begining of src will be the error, then i found this on `Resources\views\MediaAdmin\select_provider.html.twig`

```twig
 {% if provider.providerMetadata.image is null %}
  <i class="{{ provider.providerMetadata.option('class') }}"></i>
{% else %}
  <img src="{{ asset(provider.providerMetadata.image) }}" style="max-height: 20px; max-width: 100px;"/>
  <br />
{% endif %}
```

and i replace by this and working ok

```twig
 {% if provider.providerMetadata.image is null %}
  <i class="{{ provider.providerMetadata.option('class') }}"></i>
{% else %}
  <img src="{{ provider.providerMetadata.image }}" style="max-height: 20px; max-width: 100px;"/>
  <br />
{% endif %}
```

so, i dont know if you want a PR

**Comment by brieuc28** [comment]
I faced the same issue. I was using the sonata core 2.3.1 and changed to 2.3.0, This solved it.  It seems that the 2.3.3 also having the same issue.

**Comment by desarrolla2** [comment]
@rande do you want a PR?

**Comment by ruscon** [comment]
ping ?

**Comment by Hoannv** [comment]
same issue with 2.3.2

**Comment by Soullivaneuh** [comment]
Duplicate #761.
