### ISSUE TITLE
Usage of deprecated factory-service and factory-method configuration in Resources/config/gaufrette.xml

### ISSUE THREAD

**Issue by nicwortel** [sonata-project/SonataMediaBundle#781]
> PHP Deprecated:  Symfony\Component\DependencyInjection\Definition::setFactoryMethod(ObjectStore) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. in /home/nic/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Definition.php on line 137

The offending configuration is in Resources/config/gaufrette.xml on lines 48 - 50:

```
    <service id="sonata.media.adapter.filesystem.opencloud.objectstore" class="OpenCloud\ObjectSource\Service"
             factory-service="sonata.media.adapter.filesystem.opencloud.connection"
             factory-method="ObjectStore">
        <argument/>
        <argument/>
    </service>
```

**Comment by core23** [comment]
Can you provide a PR? @nicwortel
