### ISSUE TITLE
Wrong ContentType/ProviderReference for compressed svg file (2.2.4 version)

### ISSUE THREAD

**Issue by cufo** [sonata-project/SonataMediaBundle#793]
Hi guys, I have some problem with the svg compressed files.

The providerReference some time is  saved in the db as filename.txt or fileName.html file and the  ContentType is saved as text/plain or text/html and not image/svg+xml.
I used the svg validator and the compressed svg file is correct.

The problem is in FileProvider.php,  $media->getBinaryContent()->guessExtension() returns the wrong 
extension.
<i background-color: #eee;>

```php
 protected function doTransform(MediaInterface $media)
{
    $this->fixBinaryContent($media);
    $this->fixFilename($media);

    // this is the name used to store the file
    if (!$media->getProviderReference()) {
        $media->setProviderReference($this->generateReferenceName($media));
    }

    if ($media->getBinaryContent()) {
        $media->setContentType($media->getBinaryContent()->getMimeType());
        $media->setSize($media->getBinaryContent()->getSize());
    }

    $media->setProviderStatus(MediaInterface::STATUS_OK);
}

protected function generateReferenceName(MediaInterface $media)
{
    return sha1($media->getName() . rand(11111, 99999)) . '.' . $media->getBinaryContent()->guessExtension();
}
```

</i>

I'm using sonata 2.2.4 and PHP 5.5.12 

Please let me know.
Thanks!

**Comment by phansys** [comment]
@cufo, I think this issue isn't related to this bundle. Could you please check your file with [```finfo_file()```](http://php.net/manual/en/function.finfo-file.php)?

**Comment by core23** [comment]
Ping @cufo

**Comment by core23** [comment]
Can you please check this against the latest stable release @cufo ?

**Comment by cufo** [comment]
Hi @core23,
unfortunately we are working in a legacy project and we can't upgrade to the latest stable release.
I'll let you know if I have any update on that.

Thanks
