### ISSUE TITLE
SonataAdmin 2.4 compatible Version

### ISSUE THREAD

**Issue by MM-Psiiirus** [sonata-project/SonataMediaBundle#798]
Hiya,
is there already a working build for SoantaAdmin 2.4?
Unfortunately i can't get it to work because of the dependency to the classification Bundle.

```
 "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.7.*",

        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",

        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "sonata-project/user-bundle": "2.2.x-dev",
        "sonata-project/admin-bundle": "dev-master",
        "genemu/form-bundle": "dev-master",
        "sonata-project/media-bundle": "dev-master"

    },
```

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sonata-project/media-bundle dev-master -> satisfiable by sonata-project/media-bundle[dev-master].
    - sonata-project/media-bundle dev-master requires sonata-project/classification-bundle ~2.3 -> no matching package found.
```

**Comment by Soullivaneuh** [comment]
Your issue seems not to be related to sonata-project/admin-bundle but to sonata-project/classification-bundle.

Which version of this bundle do you have?

**Comment by MM-Psiiirus** [comment]
I haven't installed any version of the classification-bundle.
as you can see it cant find any match for 2.3. :-/

**Comment by Soullivaneuh** [comment]
Please add those line to your `composer.json` file:

```json
"minimum-stability": "dev",
"prefer-stable": true,
```

This should solve your issue.

**Comment by MM-Psiiirus** [comment]
Yeah! this worked for me ...unfortunately now i got a full-stack classification-bundles installed which i don't need and actually don't want...is there a way to turn this of and keep the dev version of the MediaBundle?

**Comment by Soullivaneuh** [comment]
This is required for this bundle: https://github.com/sonata-project/SonataMediaBundle/blob/master/composer.json#L25

**Comment by MM-Psiiirus** [comment]
Yeah i know but i've seen an pull-request to remove the dependency which would be very handy because now i got tons of buttons i don't need in my GUI ;-)

**Comment by Soullivaneuh** [comment]
Which PR are you talking about?

**Comment by MM-Psiiirus** [comment]
This on : https://github.com/sonata-project/SonataMediaBundle/pull/794

**Comment by Soullivaneuh** [comment]
Well. As you can see this is under discussion because of BC breaking.

If this cannot be solved, this will be release later on next major release. ;-)

I close this issue as it's resolved.
