### ISSUE TITLE
Post processign images

### ISSUE THREAD

**Issue by chaos-drone** [sonata-project/SonataMediaBundle#813]
What wild be the best way for processing images after saving?

I want to optimize the images for all contexts and formats using the TinyPNG API. I have library for TinyPNG's API but I'm wondering which is the best way to integrate it with the media bundle. I also want to use SonataNotificationBundle to run the optizmization in background. so the user shouldn't wait for the optimization to complete.

The easiest way I found is to extend the image provider and override postPersist and postUpdate methods, where the backend service of the notification bundle can be called.

Anyone think of some better way?

**Comment by rande** [comment]
@chaos-drone there is a thumbnail consumer for the notification bundle. If you want to use specific image processing tools you can also change the default resizer.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
