### ISSUE TITLE
Weird failing test on 2.3 lowest deps

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataMediaBundle#819]
See: https://travis-ci.org/sonata-project/SonataMediaBundle/jobs/72112494#L699

Can't reproduce it on my local.

@rande any idea?

**Comment by phansys** [comment]
@Soullivaneuh, maybe this is related to [PSR-7](http://www.php-fig.org/psr/psr-7/), since a response is represented by a message that implements [MessageInterface](https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php#L171) and there isn't any ```getContent()``` method.

**Comment by phansys** [comment]
BTW, I can't reproduce the issue in my local env, but after some debug I think it has nothing to do with PSR-7 since I didn't found any usage of it.
Buzz has the method well defined: [```MessageInterface::getContent()```](https://github.com/kriswallsmith/Buzz/blob/0c87a2dbb13791d63c61a9735b9bf1d1f79bb81d/lib/Buzz/Message/MessageInterface.php#L59).

**Comment by phansys** [comment]
@Soullivaneuh, I can reproduce the issue locally now, so I'll work on it. When I'll have some news I'll ping you.

**Comment by Soullivaneuh** [comment]
Thanks @phansys. I'll do some searches on my side too.

**Comment by Soullivaneuh** [comment]
What did you make to be able for reproducing?

**Comment by phansys** [comment]
```git checkout 2.3```. I was trying on master before (I though you mean 2.3 just for the symfony reqs).

**Comment by phansys** [comment]
Buzz 0.3 has not MessageInterface: https://github.com/kriswallsmith/Buzz/tree/v0.3/lib/Buzz/Message
```bash
SonataMediaBundle (2.3) $ composer show -i kriswallsmith/buzz
name     : kriswallsmith/buzz
descrip. : Lightweight HTTP client
keywords : http client
versions : * v0.3
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/kriswallsmith/Buzz.git 0b72b0215e9ecb8e0d754ba392b6c1872a832b7c
dist     : [zip] https://api.github.com/repos/kriswallsmith/Buzz/zipball/0b72b0215e9ecb8e0d754ba392b6c1872a832b7c 0b72b0215e9ecb8e0d754ba392b6c1872a832b7c
names    : kriswallsmith/buzz

autoload
psr-0
Buzz => lib/

requires
php >=5.3.0
```

**Comment by phansys** [comment]
Should we bump the version constraint to ```kriswallsmith/buzz: ~0.6``` or update the tests accordingly to the corresponding class?

**Comment by Soullivaneuh** [comment]
@phansys could you provide a PR with the corrected `composer.json`?

**Comment by Soullivaneuh** [comment]
Bumping version looks better.

Do not work neither with `0.4` and `0.5`?

**Comment by phansys** [comment]
No at all, MessageInterface was introduced at [0.6](https://github.com/kriswallsmith/Buzz/commit/9430f7702bc886af45a882be938d13604772a76c).

**Comment by Soullivaneuh** [comment]
Let's go for version bumping so.

**Comment by phansys** [comment]
Note that if we replace the mocks for ```Buzz\Message\MessageInterface``` with ```Buzz\Message\AbstractMessage```, the issue is gone since ```AbstractMessage``` is present in all resolved versions.

**Comment by Soullivaneuh** [comment]
Feel free to make the best proposition. ;-)
