### ISSUE TITLE
"sonata-project/classification-bundle": "~2.3", broken dependency

### ISSUE THREAD

**Issue by gabrielAnglada** [sonata-project/SonataMediaBundle#824]
In https://github.com/sonata-project/SonataClassificationBundle

Cannot find the tag 2.3 which is being refrenced from composer.json in master branch

**Comment by Soullivaneuh** [comment]
You need to change requirement stability: https://github.com/sonata-project/SonataMediaBundle/commit/f2d3918c4ca8f909c87a02db47f3380786d3d4fe#commitcomment-11835048
