### ISSUE TITLE
sonata-project/classification-bundle dependency broken in master

### ISSUE THREAD

**Issue by gabrielAnglada** [sonata-project/SonataMediaBundle#825]
sonata-project/classification-bundle dependency is pointing to 2.3 which esists on packagist but not in github. See https://packagist.org/packages/sonata-project/classification-bundle#dev-master and https://github.com/sonata-project/SonataClassificationBundle

**Comment by Soullivaneuh** [comment]
I already answered here: https://github.com/sonata-project/SonataMediaBundle/issues/824#issuecomment-128345186

Please don't open new issue.

If you didn't understand, just answer on the same issue.
