### ISSUE TITLE
[DX] would like to rename the GalleryHasMedia object

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataMediaBundle#828]
to ```GalleryMediaItem``` ... an GalleryItem which holds the reference to the Media.

What do you think?

another reason for me is, that this name is **countable** -> GalleryMediaItems -> many items, where every item contains one Media

vs.

GalleryHasMedias..... 

If you like it, i will provide a PR.

I know this is a BC break.

best Oskar

**Comment by OskarStark** [comment]
![bildschirmfoto 2015-08-13 um 17 51 57](https://cloud.githubusercontent.com/assets/995707/9254479/085d1a28-41e4-11e5-8069-ed6da062326f.png)

**Comment by DracoBlue** [comment]
I would appreciate this naming to be more consistent, too! ;)

There would be some work to do in my POV:

* `Gallery#setGalleryHasMedias` should be `Gallery#setMediaItems`
* also `GalleryHasMediaInterface ` should be renamed to `GalleryMediaItemInterface `
* and so on

Any reasons for the GalleryHasObject name in first place @rande ?

**Comment by OskarStark** [comment]
ping @rande

**Comment by Soullivaneuh** [comment]
I let @rande decide for this.

> I know this is a BC break.

Yeah, but you can handle BC with class deprecation and extend. ;-)

**Comment by OskarStark** [comment]
@DracoBlue please see #948, thank you :+1:

**Comment by OskarStark** [comment]
@vworldat please check #948 please

**Comment by OskarStark** [comment]
Closed via #948
