### ISSUE TITLE
The helper “sonata_media” is not defined

### ISSUE THREAD

**Issue by burakcakirel** [sonata-project/SonataMediaBundle#833]
I'm using PHP as template engine. When I use the following code in my template:
`<?php echo $view['sonata_media']->thumbnail($media, 'small') ?>`
> The helper "sonata_media" is not defined.

Am I doing wrong something ?

Here is my config.yml file:
https://gist.github.com/burakcakirel/1ce7884f8132ebaf44cd

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
