### ISSUE TITLE
some finetuning for the media widget

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataMediaBundle#838]
shall i provide a PR?

look at "Typ" and "Kontext"

old:
![bildschirmfoto 2015-08-28 um 14 54 05](https://cloud.githubusercontent.com/assets/995707/9546630/b2706702-4d94-11e5-9b0e-7591f0910118.png)

new:
![bildschirmfoto 2015-08-28 um 14 54 07](https://cloud.githubusercontent.com/assets/995707/9546633/b60347fe-4d94-11e5-86ab-fbd04fceaaed.png)

ping @Soullivaneuh @rande

**Comment by rande** [comment]
look better for me, just the delete action with look weird

**Comment by OskarStark** [comment]
yeah i'm working on it and the delete checkbox is not translated by default, but lets do this in another PR

one more idea:
![bildschirmfoto 2015-08-28 um 15 39 31](https://cloud.githubusercontent.com/assets/995707/9547477/0351f388-4d9b-11e5-810a-82f505cc6a75.png)

@rande

**Comment by OskarStark** [comment]
@rande i'm wondering why the binary content is required all the time...

it's also required, when there is an linked binary already.
any idea?

i fixxed this by implementing this method in the IMageProvider:
```php
    /**
     * {@inheritdoc}
     */
    public function buildMediaType(FormBuilder $formBuilder)
    {
        $formBuilder->add('binaryContent', 'file', array(
            'required' => false
        ));

        if ($formBuilder->getOption('context') == 'api') {
            $formBuilder->add('contentType');
        }
    }
```

and i added the required option to this field.

if you say this is correct, i can provide a PR

**Comment by stiffroy** [comment]
@OskarStark 
Thanks for pointing out the solution with 'required' false. I was playing around a bit with it. And my conclusion is, you don't need to touch the media bundle. You can just update your form builder in the admin code something like
```php
->add('o2oRelation', 'sonata_media_type', array(
     'provider' => 'sonata.media.provider.image',
     'context'  => 'default',
     'required' => false, // using it here
))
```
What do you think?

**Comment by OskarStark** [comment]
no @stiffroy in my use case the media IS required!

But when i edit my entity, and it already has a media, then the form to upload a new one IS NOT required!!

if i use your suggestion, then nothing is required... :(

**Comment by stiffroy** [comment]
@OskarStark 
With your solution too, I can create a new object without an image (somehow it does not need an image it seems). The field is NOT nullable. If I check the database (using your solution), the value of the field is `NULL`. The field name in the form has a `*` beside it implying that it is a required field but it actually doesn't work as `required`.
What happens when you are trying to create an object with your solution and don't select an image?
May be I am doing something different but not sure what exactly.

**Comment by OskarStark** [comment]
nullable in my case does not work, i use Assert\NotBlank(), can you please try this?

**Comment by stiffroy** [comment]
Hi @OskarStark ,

I tried your solution and it is working fine. In my case, the field is not an `required` field. But still I will use solution as it looks more logical to me.
(Y)

**Comment by OskarStark** [comment]
@stiffroy sorry i didn't understand your laste sentence

**Comment by stiffroy** [comment]
@OskarStark I just missed the `yours` :P

**Comment by OskarStark** [comment]
so shall i provide a PR @Soullivaneuh @rande ?
