### ISSUE TITLE
API postProviderMediumAction validation errors

### ISSUE THREAD

**Issue by bodnar1212** [sonata-project/SonataMediaBundle#843]
http://joxi.ru/YmEn49bFRwol26 Help me please. From 'multipart/form-data' cannot read data fields

**Comment by binhle410** [comment]
you have to create relevant post field ;)

**Comment by bodnar1212** [comment]
Describe the details, please. How read this request https://sonata-project.org/bundles/media/master/doc/reference/api.html? I use default media api method and has this errors.

**Comment by pauleau** [comment]
Oh man! I have the same issue and get out of this for days. Do you finally make it works ? 

I'll very very appreciate a reply from you. Thank you.
