### ISSUE TITLE
Api MediaBundle putMediumAction response body is empty

### ISSUE THREAD

**Issue by bodnar1212** [sonata-project/SonataMediaBundle#847]
How resolve this issue? http://joxi.ru/zANDKabFMkkwm9 If send with POST validation is ok, current row in db was updated, but was created still new row with same image

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
