### ISSUE TITLE
php app/console sonata:easy-extends:generate SonataMediaBundle

### ISSUE THREAD

**Issue by rexchou** [sonata-project/SonataMediaBundle#851]
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                                              
  There is no extension able to load the configuration for "news" (in /var/www/html/CQWUXI/app/config/sonata/sonata_media.yml). Looked for namespace "news", found "fram  
  ework", "security", "twig", "monolog", "swiftmailer", "assetic", "doctrine", "sensio_framework_extra", "sonata_core", "sonata_block", "knp_menu", "sonata_doctrine_orm  
  _admin", "sonata_admin", "fos_user", "sonata_user", "sonata_easy_extends", "sonata_mark_it_up", "ivory_ck_editor", "sonata_news", "sonata_media", "sonata_intl", "sona  
  ta_formatter", "knp_markdown", "application_sonata_news", "sonata_classification", "application_sonata_media", "debug", "web_profiler", "sensio_distribution"

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
