### ISSUE TITLE
Use forms built by custom providers as standalone forms

### ISSUE THREAD

**Issue by liquorvicar** [sonata-project/SonataMediaBundle#854]
Is there a(n easy) way to use the forms build by a custom provider in a standalone context?

I'm thinking something like:
```
$form = $customProvider->buildCreateForm(...);
$form->bindValues($inputArray);
etc
```

Or am I barking up the wrong tree? Or even the wrong forest ;-)

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
