### ISSUE TITLE
Length of either side cannot be 0 or negative, current size is x

### ISSUE THREAD

**Issue by linkito87** [sonata-project/SonataMediaBundle#855]
Hi.

I have an issue in 2.4@dev-master version that I haven't in the 2.3.3 version.

This is my code:

``` php
if (false === $request->files->has('photo')) {
      $binary = base64_decode(str_replace(' ', '+', $request->request->get('photo')));
}
 $tmpFile = tempnam('/tmp', 'media-');

file_put_contents($tmpFile, $binary);

$media = new Media();
$media->setBinaryContent($tmpFile);
$media->setContext('default');
$media->setProviderName('sonata.media.provider.image');

/** @var MediaManager $mediaManager */
$mediaManager = $this->get('sonata.media.manager.media');
$mediaManager->save($media);
```

In the save method, this throw this error:

"Length of either side cannot be 0 or negative, current size is x"
vendor/imagine/imagine/lib/Imagine/Image/Box.php at line 42

``` php
public function __construct($width, $height)
{
    if ($height < 1 || $width < 1) {
        throw new InvalidArgumentException(sprintf('Length of either side cannot be 0 or negative, current size is %sx%s', $width, $height));
    }
    $this->width  = (int) $width;
```

Anyone can give me a solution? 

Thanks!

**Comment by NadirZenith** [comment]
Hi. I'm downloading some images with file_get_contents($url) and had the same error while saving too.

But i can save if my $tmpfile have an extension. this is my code hope it helps:
```php
$ext = pathinfo($url, PATHINFO_EXTENSION);
$temp_path = rtrim(sys_get_temp_dir(), '/') . '/' . uniqid() . '.' . $ext;
$fileContent = file_get_contents($url);
file_put_contents($temp_path, $fileContent);
...
$media->setBinaryContent($fileContent);
...
$mediaManager->save($media);
```

**Comment by tristanbes** [comment]
If you are working with `UploadedFile` instance (when you have a file inside your Symfony forms):
Works for Sonata Media Bundle >= v3

```php
                   $mediaManager = $this->container->get('sonata.media.manager.media');

                    $media = new Media();
                    $media->setContext('avatar');
                    $media->setCategory($this->get('sonata.classification.manager.category')->getRootCategory());
                    $media->setProviderName('sonata.media.provider.image');

                    $ext = $form['tempLogo']->getData()->getClientOriginalExtension();
                    $tempPath = rtrim(sys_get_temp_dir(), '/') . '/' . uniqid() . '.' . $ext;
                    $fileContent = file_get_contents($form['tempLogo']->getData()->getPathName());
                    file_put_contents($tempPath, $fileContent);

                    $media->setBinaryContent($tempPath);
                    $mediaManager->save($media);

                    $team->setLogo($media);
```

**Comment by ldiaz** [comment]
Thanks @tristanbes I'm using media-bundle": "^3.3" in my composer and the same issue appears, Your solution fixes the problem, but I would suggest that a better approach is to only **rename** the temporal file **to reduce memory use** (I'm using images > 16Mbytes, so many users processing images quickly leaves the server without memory ). 


`$filePath = $form['tempLogo']->getData()->getPathName();`
`$extension = getMyFileExtensionSomehow($form['tempLogo']); //I'm extracting from the original name`
`$tempPath =  $filePath.'.'.$extension;`
`rename($filePath,$tempPath);`

`$media->setBinaryContent($tempPath);`

**Comment by lcavero** [comment]
@tristanbes solution doesn't works on my, I need to manually specify media's with and height.

`

    $media_sizes = getimagesize($tempPath);

    $media->setWidth($media_sizes[0]);

    $media->setHeight($media_sizes[1]);
`
