### ISSUE TITLE
Proper config for sonata.media.manager.gallery

### ISSUE THREAD

**Issue by renooo** [sonata-project/SonataMediaBundle#858]
Hi everyone,

There is a config problem for the service **sonata.media.manager.gallery** (at least when you decide _not_ to use **easy-extends**) with **doctrine_mongodb** and **doctrine_phpcr** .

Here :

https://github.com/sonata-project/SonataMediaBundle/blob/master/Resources/config/doctrine_mongodb.xml#L21

        <service id="sonata.media.manager.gallery" class="%sonata.media.manager.gallery.class%">
            <argument>%sonata.media.media.class%</argument>
            <argument type="service" id="doctrine_mongodb" />
        </service>

and here :

https://github.com/sonata-project/SonataMediaBundle/blob/master/Resources/config/doctrine_phpcr.xml#L19

        <service id="sonata.media.manager.gallery" class="%sonata.media.manager.gallery.class%">
            <argument>%sonata.media.manager.gallery.class%</argument>
            <argument type="service" id="doctrine_phpcr" />
        </service>

The config should look like this :

https://github.com/sonata-project/SonataMediaBundle/blob/master/Resources/config/doctrine_orm.xml#L19

        <service id="sonata.media.manager.gallery" class="%sonata.media.manager.gallery.class%">
            <argument>%sonata.media.gallery.class%</argument>
            <argument type="service" id="doctrine" />
        </service>

Meanwhile, here is a workaround to make it work  :

https://gist.github.com/renooo/66d7e4d2b39f50cbd55a

**Comment by OskarStark** [comment]
can you please provide a PR for this?

**Comment by renooo** [comment]
Here you are :-) https://github.com/sonata-project/SonataMediaBundle/pull/859 !

**Comment by renooo** [comment]
Sorry for the delay ... here is the PR on the right branch : 
https://github.com/sonata-project/SonataMediaBundle/pull/865

**Comment by OskarStark** [comment]
Merged via 0787f30e670cb65067f6a1e8b55919569ad7e809
