### ISSUE TITLE
PERIODICALLY Error: zend_mm_heap corrupted

### ISSUE THREAD

**Issue by Avtonom** [sonata-project/SonataMediaBundle#866]
Hello! There is a problem I have not decided yet.
**Description**: PERIODICALLY when adding a file through the API, the server crashes with the error in /var/log/httpd/error_log: zend_mm_heap corrupted.
This happens sometimes, then itself begins to work normally. Ie file is normally loaded, then it ceases to be loaded. Although at this time the other can be loaded normally.

I use API /api/providers/sonata.media.provider.file/media

The provider of the file system: sonata.media.filesystem.ftp

Development environment: no matter dev / prod

----------------------
здравствуйте! Есть проблема которую я ещё не решил.
Описание: ПЕРИОДИЧЕСКИ при добавлении файла через API, сервер падает с ошибкой в /var/log/httpd/error_log: zend_mm_heap corrupted.
Такое происходит иногда, потом само начинает работать нормально. Т.е. файл нормально грузиться, потом он же перестает грузиться. Хотя в это время другой может загружаться нормально.

Использую API /api/providers/sonata.media.provider.file/медиа

Провайдер файловой системы: sonata.media.filesystem.ftp

Окружение разработки: без разницы дев / прод

-----

Composer:

 - sonata-project/media-bundle: "2.3.x-dev"
 - knplabs/gaufrette: >=0.1.4

apache+mod_php:

 - httpd-2.2.15-47.el6.centos.x86_64
 - httpd-itk-2.2.22-7.el6.x86_64
 - php55w-5.5.30-2.w6.x86_64

Other:

 - zend.enable_gc = Off 
 - opcache.fast_shutdown = Off
 - USE_ZEND_ALLOC = 0 

---------------

Stackoverflow: http://stackoverflow.com/questions/33395215/periodically-error-zend-mm-heap-corrupted

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
