### ISSUE TITLE
The annotation "@ApiDoc" in method Sonata\MediaBundle\Controller\Api\GalleryController::getGalleriesAction() was never imported.

### ISSUE THREAD

**Issue by cacahouete78** [sonata-project/SonataMediaBundle#876]
The annotation "@ApiDoc" in method 
`Sonata\MediaBundle\Controller\Api\GalleryController::getGalleriesAction()` was never imported.

**Comment by OskarStark** [comment]
can you please provide a PR?

**Comment by DevMaster112** [comment]
Can confirm this issue. Got the same problem. Therefore i can't do a 'cap deploy' with capistrano with capifony.

This is the exception that popups in capistrano with capifony:
> Generating autoload files
> post-autoload-dump: ComponentInstaller\Installer::postAutoloadDump
> Compiling component files
> post-update-cmd: Incenteev\ParameterHandler\ScriptHandler::buildParameters
> Updating the "app/config/parameters.yml" file
> post-update-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> post-update-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
> [Doctrine\Common\Annotations\AnnotationException]
> [Semantical Error] The annotation "@ApiDoc" in method Sonata\MediaBundle\Controller\Api\GalleryController::getGalleriesAction() was never imported. Did you maybe forget to add a "use" statement for this annotation?
> Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception
> [RuntimeException]
> An error occurred when executing the "'cache:clear --no-warmup'" command.

**Comment by DevMaster112** [comment]
Quick solution / workaround to keep your symfony project working:

in your composer.json edit following:
``` json
"require": {
     "sonata-project/media-bundle": "dev-master#1cc799eda0fa7dc0fb01045cb36747e89b4bffcf"
 }
```
This commited dev master (See https://github.com/sonata-project/SonataMediaBundle/commits/master) by @Soullivaneuh is working at least.

Waiting till this bug is fixed.

**Comment by DevMaster112** [comment]
After this commit (#9327923) the error is still occuring.

**Comment by OskarStark** [comment]
can you provide a link what do you mean?
my PR isn't merged yet

**Comment by DevMaster112** [comment]
Ah my fault. i only saw that you added the referenced. But it isn't merged yet as you said.
Waiting for merging.

**Comment by OskarStark** [comment]
i merged this, try again

**Comment by DevMaster112** [comment]
The error is passed. But now another error occurs:
```
[Doctrine\Common\Annotations\AnnotationException]
[Semantical Error] The class "FOS\RestBundle\View\View" is not annotated with @Annotation. Are you sure this class can be used as annotation? If so, then you need to add @Annotation to the _class_ doc comment of "FOS\RestBundle\View\View". If it is indeed no annotation, then you need to add @IgnoreAnnotation("View") to the _class_ doc comment of method Sonata\MediaBundle\Controller\Api\MediaController::getMediaAction().
```

Dont know if its a problem of FOSUserBundle or SonataMediaBundle.

**Comment by OskarStark** [comment]
please try to fix this and then provide a PR or the Solution here to me

**Comment by DevMaster112** [comment]
The solution for MediaBundle will be this (said in error text):
_then you need to add @IgnoreAnnotation("View") to the class doc comment of method Sonata\MediaBundle\Controller\Api\MediaController::getMediaAction()_

If this doesn't help, i will start an issue at FOSUserBundle.

**Comment by cacahouete78** [comment]
to fix it, I add / replace some "use" in "Sonata\MediaBundle\Controller\Api\MediaController.php":

use FOS\RestBundle\Controller\Annotations\QueryParam;
use FOS\RestBundle\Controller\Annotations\Route;
use FOS\RestBundle\Controller\Annotations\View;
// use FOS\RestBundle\View\View;

**Comment by OskarStark** [comment]
ping @core23 can you please check this out?

**Comment by OskarStark** [comment]
Fixxed by #879
