### ISSUE TITLE
Media Widget: Unlink isn'n translated

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataMediaBundle#888]
When using the ``sonata_media_type``, the Unlink checkbox isn't translated. 

```php
                ->add('media', 'sonata_media_type', array(
                    'provider' => 'sonata.media.provider.image',
                    'context'  => 'partner',
                    'required' => false,
                ))
```
Somehow the wrong translation_domain is used

![bildschirmfoto 2015-11-13 um 00 38 18](https://cloud.githubusercontent.com/assets/3440437/11134662/e11d62a8-899e-11e5-88ac-57a603b8fff0.PNG)

**Comment by OskarStark** [comment]
this should be translated via the ``SonataMediaBundle`` translation_domain, if you provide a PR
