### ISSUE TITLE
Use SonataMediaBundle without "Full Stack Sonata"

### ISSUE THREAD

**Issue by JHGitty** [sonata-project/SonataMediaBundle#892]
I like to use the SonataMediaBundle to extend our application.

I want to extend our application to add images and files to our entities and use some upload functions. Nothing more.

I don't want to use the complete Sonata system:
I don't need "Admin", "SEO" or any other Sonata bundles.

But these bundles are not just suggested over composer, they are included in `require-dev`.
https://github.com/sonata-project/SonataMediaBundle/blob/master/composer.json#L34-L44

Is it possible to move some bundles to `suggest`?

**Comment by core23** [comment]
IMO they are included in ``require-dev`` to use them in travis build, nothing more. You can use the MediaBundle without these packages if you want. By default no ``require-dev``package should be loaded when you load them via composer.

**Comment by jordisala1991** [comment]
As @core23 said, require-dev bundles are not loaded when you install this bundle as a composer dependency. Closing
