### ISSUE TITLE
Sonata Media Image Upload Path

### ISSUE THREAD

**Issue by Siddharth22** [sonata-project/SonataMediaBundle#894]
I am using Sonata Media Bundle for image upload and this is working great.But I want some customization on image generate path.

Like :- When I upload image through Sonata Media Bundle then It's give me image path :-
http://example.com/web/uploads/media/Abc_pla/0001/01/thumb_9_Abc_pla_small.jpeg

But I want path like this :- http://example.com/web/uploads/media/thumb_9_Abc_pla_small.jpeg

How I can do this ?

Thanks !

**Comment by ferdinandfly** [comment]
You can override the Sonata\MediaBundle\Generator\DefaultGenerator
to give you a file path you want. But , attention, if you put all your file in one folder, indexing time will be very long.
