### ISSUE TITLE
Is this bundle compatible with aws/aws-sdk-php?

### ISSUE THREAD

**Issue by ricoli** [sonata-project/SonataMediaBundle#895]
Firstly, I'm using the latest stable version of this bundle (2.3.3). I've tried to use aws/aws-sdk-php latest stable version (3.10.1), for s3 usage, as it seems amazonwebservices/aws-sdk-for-php has been abandoned. This page in the docs does say it it should be used (https://sonata-project.org/bundles/media/master/doc/reference/amazon_s3.html). I get this when requiring it on composer: ```PHP Fatal error:  Class 'AmazonS3' not found in app/cache/dev/appDevDebugProjectContainer.php on line 11049```. I also tried requiring version 2.8.24 of aws/aws-sdk-php, and had the same error. Everything works fine when requiring the abandoned package, hence this question.

UPDATE: just realised that the documentation is for master, and there isn't documentation for 2.3... https://github.com/sonata-project/SonataMediaBundle/pull/640 should add support for aws/aws-sdk-php
Any chance that 2.4 will be tagged soon? @rande :)

**Comment by core23** [comment]
Yes since #897
