### ISSUE TITLE
wrong XLIFF file formatting making sf failing

### ISSUE THREAD

**Issue by yanict** [sonata-project/SonataMediaBundle#901]
please fix... issue is line 499

*/vendor/sonata-project/medi
  a-bundle/Resources/translations/SonataMediaBundle.en.xliff": Premature end of data in tag
  xliff line 2*

**<target>Left/target>**

**Comment by OskarStark** [comment]
Applied in ed8c1b878f028d40b6b00171f4f37bd560cdd1d6

**Comment by OskarStark** [comment]
ping @Soullivaneuh @rande should we lint the xml files?
