### ISSUE TITLE
Guzzle vs. Buzz

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataMediaBundle#910]
Is there a reason why we use both HTTP clients?

Guzzle:
https://github.com/sonata-project/SonataMediaBundle/blob/72355b98389f2d9d60f6c16a70964962f6f7482c/Metadata/AmazonMetadataBuilder.php#L16

Buzz:
https://github.com/sonata-project/SonataMediaBundle/blob/25d4a66d0ec25140f474b243879e98d067928647/Provider/BaseVideoProvider.php#L14
https://github.com/sonata-project/SonataMediaBundle/blob/25d4a66d0ec25140f474b243879e98d067928647/Provider/BaseVideoProvider.php#L14

IMO we should use Guzzle as it has far more [features](https://groups.drupal.org/node/233173) and a larger user base.

**Comment by OskarStark** [comment]
:+1:  for Guzzle, can you provide a PR?

**Comment by Soullivaneuh** [comment]
Would not be even better to abstract this thing and allow user to choose which one to use?

See for example: https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/HttpClient/HttpClientInterface.php

**Comment by OskarStark** [comment]
I dont like to abstract everything, but we should minimize the number of
dependencies IMO

Am Montag, 30. November 2015 schrieb Sullivan SENECHAL :
