### ISSUE TITLE
Add Gallery only of ImageProvider Media

### ISSUE THREAD

**Issue by clytemnestra** [sonata-project/SonataMediaBundle#929]
I'm using SonataMediaBundle and want to add a Gallery of Images to an entity, let's say Ad. Each Ad has a Gallery that can have multiple Media. I've been following [this](http://stackoverflow.com/questions/28921077/symfony-sonata-media-bundle-add-images-videos-to-a-user) other answer, too and it has been pretty useful.

I did it already, I can add Galleries to my Entity and add all sort of Media to that Gallery, but what I want is in backend to skip the Provider selection for when a Media is added to the Gallery, and to automatically select the ImageProvider, so that I can create an image-only Gallery.

``` php
    class Ad
    {
        /**
         * @var int
         *
         * @ORM\Column(name="id", type="integer")
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="AUTO")
         */
        private $id;

        /**
         * @var string
         *
         * @ORM\Column(name="title", type="string", length=255,nullable=true)
         */
        private $adTitle;

        /**
         * @GalleryHasMoreThanNineMedia
         * @ORM\OneToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Gallery",mappedBy="ad",cascade={"persist"})
         * @ORM\JoinColumn(name="gallery", referencedColumnName="id",nullable=true)
         */
        private $gallery;
    }
```

And in Ad sonata admin class:

``` php
     protected function configureFormFields(FormMapper $formMapper)
        {
            $formMapper
                ->add('adTitle')   
                ->add('gallery', 'sonata_type_model_list', array(
                    'cascade_validation' => true,
                    'required' => false,
                ), array(
                        'edit' => 'inline',
                        'inline' => 'table',
                        'sortable' => 'position',
                        'link_parameters' => array('provider' => 'sonata.media.provider.image'),
                        'admin_code' => 'sonata.media.admin.gallery',
                    )
                );
        }
```

Somehow I need to pass the `link_parameters` not to the Gallery form, but to each GalleryHasMedia being created, so that each of the new Media is an image of ImageProvider and gets the validation of that provider(the extensions,MIME Type, thumbnail etc.)

So this is how the form looks like

[![enter image description here](http://i.stack.imgur.com/7MEwY.png)](http://i.stack.imgur.com/7MEwY.png)

Which opens this modal window where I can add GalleryHasMedia to a Gallery.

[![enter image description here](http://i.stack.imgur.com/FB7rF.png)](http://i.stack.imgur.com/FB7rF.png)

What I want is upon adding the Media, this modal to choose the provider to not appear, but instead select ImageProvider automatically. Is it possible to pass `link_parameters' => array('provider' => 'sonata.media.provider.youtube')` inside a nested form value in the admin class? 

[![enter image description here](http://i.stack.imgur.com/VNiAG.png)](http://i.stack.imgur.com/VNiAG.png)

Is it possible? Do I have to modify it in my Admin class or overwrite some other form/class?

**Comment by Adraesh** [comment]
Related question from my side.

Trying to restrict the context and the provider of this generated block field using link_parameters but without success. When I click on List or Add of this field I still see all the context in the List view and all the providers in the Add view.

`/**
 * {@inheritdoc}
 */
public function buildEditForm(FormMapper $formMapper, BlockInterface $block)
{
    $formMapper->add('settings', 'sonata_type_immutable_array', array(
        'keys' => array(
            array('title', TextType::class, array(
                'required' => true,
                'label' => 'Titre',
            )),
            array($this->getMediaBuilder($formMapper), null, array()),
        ),
    ));
}

/**
 * @param FormMapper $formMapper
 *
 * @return FormBuilder
 */
protected function getMediaBuilder(FormMapper $formMapper)
{
    // simulate an association ...
    $fieldDescription = $this->getMediaAdmin()->getModelManager()->getNewFieldDescriptionInstance($this->mediaAdmin->getClass(), 'media', array(
        'translation_domain' => 'SonataMediaBundle',
    ));
    $fieldDescription->setAssociationAdmin($this->getMediaAdmin());
    $fieldDescription->setAdmin($formMapper->getAdmin());
    $fieldDescription->setOption('edit', 'list');
    $fieldDescription->setAssociationMapping(array(
        'fieldName' => 'media',
        'type' => ClassMetadataInfo::MANY_TO_ONE,
    ));

    return $formMapper->create('video', 'sonata_type_model_list',
        array(
            'sonata_field_description' => $fieldDescription,
            'class' => $this->getMediaAdmin()->getClass(),
            'model_manager' => $this->getMediaAdmin()->getModelManager(),
            'label' => 'form.label_media',
        ),
        array(
            'link_parameters' => array(
                'provider' => 'sonata.media.provider.vimeo',
                'context' => 'page_videos', 
                'hide_context' => true,
            ),
        )
    );`

**Comment by patrickmaynard** [comment]
Did this ever get resolved? I'm trying to do something very similar. See 

https://stackoverflow.com/questions/49049667/how-to-limit-sonatamediabundle-gallery-to-a-single-provider

**Comment by jorenvh1** [comment]
Having the same issue, can anyone tell me how they solved it?

**Comment by jelteliekens** [comment]
After playing around for a while I managed to get it to work by adding the code below to the fieldDescription. Please don't ask my why.. 😅 

```php
        $fieldDescription->setOption('link_parameters', array(
            'provider' => 'sonata.media.provider.image',
            'context' => 'explore',
            'hide_context' => true,
        ));
```
