### ISSUE TITLE
pixlr extension for edit images not found

### ISSUE THREAD

**Issue by estebannovo** [sonata-project/SonataMediaBundle#944]
I configure the pixlr extension but this extension not found.
when I try to edit the following error jumps
![2016-02-06_1930](https://cloud.githubusercontent.com/assets/3704157/12869792/3a1f899c-cd08-11e5-9962-62080e991b2c.png)

**Comment by estebannovo** [comment]
any idea?

**Comment by OskarStark** [comment]
did you fixed it @estebannovo ?

**Comment by estebannovo** [comment]
No, I could not, I do not know how to get an API key, there is no documentation on the site pixlr.com

**Comment by OskarStark** [comment]
you are right:
![bildschirmfoto 2016-02-18 um 08 40 49](https://cloud.githubusercontent.com/assets/995707/13136618/5dc5ab6c-d61b-11e5-8a1b-78b5241e3929.png)

URL: https://support.pixlr.com/hc/en-us/articles/209350978-The-Pixlr-API-embedding-Pixlr-web-applications-in-your-own-site

**Comment by estebannovo** [comment]
ok, thanks

**Comment by estebannovo** [comment]
Oskar, What you closed but had no solution for me is still open until we find a solution.

**Comment by OskarStark** [comment]
ok, fine for me, but a solution would be a new implementation i think, feel free to create a PR

**Comment by sferrol** [comment]
I resolved that with the next configuration:
Otherwise, pixlr can't access to the image

sonata_media:
    cdn:
        server:
          #path: /uploads/media                                                  # pixlr can't access to the image
            path: http://www.yourdomine.com/uploads/media

**Comment by OskarStark** [comment]
@sferrol could you fix the docs?

**Comment by sferrol** [comment]
what docs?
With this configuration i can edit the images using pixlr
My sonata config is:
"sonata-project/admin-bundle": "^3.23",
        "sonata-project/classification-bundle": "^3.5",
        "sonata-project/doctrine-orm-admin-bundle": "^3.2",
        "sonata-project/easy-extends-bundle": "^2.3",
        "sonata-project/media-bundle": "^3.10",

**Comment by onEXHovia** [comment]
I recently encountered the same problem. Following docs https://apps.pixlr.com/developer/api/ query parameter `image` must be url, but now https://github.com/sonata-project/SonataMediaBundle/blob/3.x/src/Extra/Pixlr.php#L121. After replacing with full url, image loading was successful.

**Comment by OskarStark** [comment]
Could you provide a PR?
