### ISSUE TITLE
Symfony 3 problem with xsd schema validation

### ISSUE THREAD

**Issue by siciarek** [sonata-project/SonataMediaBundle#950]
Resources/config/gaufrette.xml does not validate against symfony service schema vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/schema/dic/services/services-1.0.xsd in XmlUtils::loadFile 

[InvalidArgumentException]                                                                                                                                           
  [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'factory-class': The attribute 'factory-class' is not allowed. (in /home/jsiciare  
  k/Workspace/baseapp/ - line 16, column 0)                                                                                                                            
  [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'factory-method': The attribute 'factory-method' is not allowed. (in /home/jsicia  
  rek/Workspace/baseapp/ - line 16, column 0)                                                                                                                          
  [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'factory-service': The attribute 'factory-service' is not allowed. (in /home/jsic  
  iarek/Workspace/baseapp/ - line 50, column 0)                                                                                                                        
  [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'factory-method': The attribute 'factory-method' is not allowed. (in /home/jsicia  
  rek/Workspace/baseapp/ - line 50, column 0)

**Comment by siciarek** [comment]
Could I get more info?

**Comment by OskarStark** [comment]
could we get more info? which versions? which file?

**Comment by siciarek** [comment]
I migrate my project to Symfony 3.
I use
"sonata-project/media-bundle": "dev-master",
the only one branch which supports Symfony 3.0
After updating all the dependencies
I try to run:

bin/console cache:clear

And the error occurs:

[ERROR 1866] Element '{http://symfony.com/schema/dic/services}service',
attribute 'factory-method': The attribute 'factory-method' is not allowed.

New Symfony 3 service schema does not have attributes (factory-method,
factory-class) for "service" entity

<xsd:complexType name="service">
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="file" type="xsd:string" minOccurs="0"
maxOccurs="1" />
      <xsd:element name="argument" type="argument" minOccurs="0"
maxOccurs="unbounded" />
      <xsd:element name="configurator" type="callable" minOccurs="0"
maxOccurs="1" />
      <xsd:element name="factory" type="callable" minOccurs="0"
maxOccurs="1" />
      <xsd:element name="deprecated" type="xsd:string" minOccurs="0"
maxOccurs="1" />
      <xsd:element name="call" type="call" minOccurs="0"
maxOccurs="unbounded" />
      <xsd:element name="tag" type="tag" minOccurs="0"
maxOccurs="unbounded" />
      <xsd:element name="property" type="property" minOccurs="0"
maxOccurs="unbounded" />
      <xsd:element name="autowiring-type" type="xsd:string" minOccurs="0"
maxOccurs="unbounded" />
    </xsd:choice>
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="class" type="xsd:string" />
    <xsd:attribute name="shared" type="boolean" />
    <xsd:attribute name="public" type="boolean" />
    <xsd:attribute name="synthetic" type="boolean" />
    <xsd:attribute name="lazy" type="boolean" />
    <xsd:attribute name="abstract" type="boolean" />
    <xsd:attribute name="alias" type="xsd:string" />
    <xsd:attribute name="parent" type="xsd:string" />
    <xsd:attribute name="decorates" type="xsd:string" />
    <xsd:attribute name="decoration-inner-name" type="xsd:string" />
    <xsd:attribute name="decoration-priority" type="xsd:integer" />
    <xsd:attribute name="autowire" type="boolean" />
  </xsd:complexType>

I see that schema published online
http://symfony.com/schema/dic/services/services-1.0.xsd has those attributes

but above url is changed iside XmlFileLoader::validateSchema

    public function validateSchema(\DOMDocument $dom)
    {
        $schemaLocations = array('http://symfony.com/schema/dic/services'
=> str_replace('\\', '/', __DIR__.'/schema/dic/services/services-1.0.xsd'));

**Comment by siciarek** [comment]
The problem is caused by Resources/config/gaufrette.xml
