### ISSUE TITLE
sonata:media:clean-uploads command raises an ORMException

### ISSUE THREAD

**Issue by rschumacher** [sonata-project/SonataMediaBundle#954]
When executing `sonata:media:clean-uploads` in project using Doctrine ORM, a `Doctrine\ORM\ORMException` is raised: 

```
Command/CleanMediaCommand.php, in function mediaExists():
Line 131 +                'providers'         => $this->getProviders(),
```

Replacing 'providers' by 'providerName' avoids raising the exception, however I am not at all sure whether this will really lead to the expected behavior of the command.

**Comment by winterstefan** [comment]
Any news for this issue?

I'm running into the same problem (v3.5.0) with the missing property ```providers```. 
Replacing it with ```providerName``` _(or simply removing the provider check)_ fixed it for me, too.
