### ISSUE TITLE
New Custom Form Field Type to ingegrate Jquery Multiple Upload

### ISSUE THREAD

**Issue by estebannovo** [sonata-project/SonataMediaBundle#956]
I'm looking for ways to add functionality: https://github.com/blueimp/jQuery-File-Upload but I have not found a way.

By doing several tests have attempted think the right way is to create a Custom Form Field Type that in the form of 'create' logic is integrated, the issue is that I could do and I appreciate if anyone can help me, because it does not it is to copy and paste the code only.

This is going to add a new provier

thanks

**Comment by estebannovo** [comment]
any idea?

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataMediaBundle/issues/535

**Comment by estebannovo** [comment]
I have advanced with the development / integration but now when I post via Ajax image by sending the same data as when done after a single image does not save the image.

`POST:
Array
(
    [provider] => sonata.media.provider.multipleupload
    [context] => default
    [uniqid] => s56ba54cb0c31e
    [s56ba54cb0c31e] => Array
        (
            [_token] => 5dJC2eQ-mvLvR-rRVoEQybK0snrPmH_TkYDkbkDOYQU
        )	
)

$_FILES
Array
(
    [s56ba54cb0c31e] => Array
        (
            [name] => Array
                (
                    [binaryContent] => Array
                        (
                            [0] => il_570xN.865400784_8ewx.jpg
                        )

                )

            [type] => Array
                (
                    [binaryContent] => Array
                        (
                            [0] => image/jpeg
                        )

                )

            [tmp_name] => Array
                (
                    [binaryContent] => Array
                        (
                            [0] => /tmp/phpq8gOpw
                        )

                )

            [error] => Array
                (
                    [binaryContent] => Array
                        (
                            [0] => 0
                        )

                )

            [size] => Array
                (
                    [binaryContent] => Array
                        (
                            [0] => 167110
                        )

                )

        )

)`

I'm a bit lost because the first problem I have is that the Jquery Multiple Upload plugin uses multiple fields and sends me the content as an array of images but in the Provider that I extended (FileProvier) does not provide arrays nor I found where you can change to data generated correctly from the controller side or Form.


One thing is try to call the function: `$media->getBinaryContent () [0] ...` by passing the index [0] with this error does not give ajax request but the image is not saved although I see that reaches well information.

Another issue that I have work / analyze how to modify the response is to send a JSON with info for plugins.


![2016-03-04_1221](https://cloud.githubusercontent.com/assets/3704157/13531148/c731dcd0-e203-11e5-850a-f4d14b103f68.png)


I appreciate your help

**Comment by jordisala1991** [comment]
Let's only use one issue for the same thing: #711
