### ISSUE TITLE
The integration with LiipImagineBundle is broken

### ISSUE THREAD

**Issue by pcabreus** [sonata-project/SonataMediaBundle#962]
The integration with the LiipImagineBundle do not work in any version. The LiipImagineBundle has other method that is not supported by this bundle in the Thumbnail and the Controller, the path is created wrong, the route _imagine_<format> don't exit. Please some help.

**Comment by stiffroy** [comment]
May be you can look into #908 and #984 (not yet solved)

**Comment by jordisala1991** [comment]
Let's move the liip imagine discussion to a unique issue: #994
