### ISSUE TITLE
Youtube black bars

### ISSUE THREAD

**Issue by 84pixels** [sonata-project/SonataMediaBundle#965]
Hello,

How to eliminating the black bars that appear on the top and bottom of the Youtube thumbnail ?

Can i use http://img.youtube.com/vi/<insert-youtube-video-id-here>/mqdefault.jpg ?

Thanks for your help!

**Comment by jordisala1991** [comment]
Closing, please provide more information if you want me to reopen. Fill the issue template would be nice too.

I tried to search for references on the thumbnail, but I cant find any for youtube videos, I dont think we are using one. I think we are just using the iframe and AFAIK you cant change what image shows the iframe before playing the video
