### ISSUE TITLE
No context filter after overriding mediaAdmin

### ISSUE THREAD

**Issue by ferriss** [sonata-project/SonataMediaBundle#968]
I have extended the mediaAdmin, now the context filter is gone.

The page shows but the profiler shows an error: This form should not contain extra fields.
Symfony\Component\Validator\ConstraintViolation
Object(Symfony\Component\Form\Form) = [
  context => [
    type => null, 
    value => default
  ], 
  category => [
    type => null, 
    value => 42
  ]
]
in sonata_media.yml:
parameters:
    sonata.media.admin.media.class: AppBundle\Admin\MediaAdmin

in the services.yml:
tla.admin.media:
        class: %sonata.media.admin.media.class%
        arguments:
            - ~
            - AppBundle\Entity\Media\Media
            - AppBundle:MediaAdmin
            - @sonata.media.pool
            - @sonata.classification.manager.category
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Media}

**Comment by ferriss** [comment]
Did not set the calls in the new service def but it still does not show the context and filter options, cache was cleared...

tla.admin.media:
        class: %sonata.media.admin.media.class%
        arguments:
            - ~
            - AppBundle\Entity\Media\Media
            - %sonata.media.admin.media.class%
            - @sonata.media.pool
            - @sonata.classification.manager.category
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Media}
        calls:
            - [ setModelManager, ["@sonata.media.admin.media.manager"]]
            - [ setTranslationDomain, [%sonata.media.admin.media.translation_domain%]]
            - [ setTemplates, [{inner_list_row, SonataMediaBundle:MediaAdmin:inner_row_media.html.twig, outer_list_rows_mosaic: SonataAdminBundle:CRUD:base_list_flat_field.html.twig, list: SonataMediaBundle:MediaAdmin:list.html.twig, edit: SonataMediaBundle:MediaAdmin:edit.html.twig}]]

**Comment by jordisala1991** [comment]
The third argument should be the controller, and you are passing the admin media class.

This is probably a mistake on the configuration, not a problem on our side.

Closing. If you still having this issue, please ping me to reopen with more information.
