### ISSUE TITLE
"admin_sonata_media_media_create" as such route does not exist.

### ISSUE THREAD

**Issue by saravanakumargn** [sonata-project/SonataMediaBundle#972]
Getting following Error when i tried to load the page /admin/dashboard. With out media bundle i can able to get the admin dashboard page. But when i enable media bundle i am getting error.

An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_sonata_media_media_create" as such route does not exist.") in SonataAdminBundle:Block:block_admin_list.html.twig at line

composer.json
"sonata-project/admin-bundle": "2.4.x-dev",
"sonata-project/doctrine-orm-admin-bundle": "2.4.x-dev",
"sonata-project/classification-bundle": "2.3.x-dev",
"knplabs/gaufrette": "~0.1.6"
"sonata-project/media-bundle": "2.4.x-dev"

**Comment by saravanakumargn** [comment]
Solved by adding the following route additionally with documented one

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

**Comment by Godfatherlolz** [comment]
@saravanakumargn  This does not change anything at least in my case this erros still persists.

**Comment by kratekk** [comment]
@Godfatherlolz Hey, did you find the solution?

**Comment by hacktic** [comment]
try:

**Comment by hacktic** [comment]
I followed the 2.3 Doc (instead of 3*) and got it working.
Its "admin" instead of "admin_area"

admin:
resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
prefix: /admin

_sonata_admin:
resource: .
type: sonata_admin
prefix: /admin
