### ISSUE TITLE
LiipImagineBundle implementation issues

### ISSUE THREAD

**Issue by andythorne** [sonata-project/SonataMediaBundle#984]
I've been investigating updating the LiipImagineBundle integration for master and have ran into multiple issues not covered by some of the outstanding PRs (#720, #518) that attempted to fix it. I'm making this issue to discuss the issue points so we can come to a solution.
- `Route _imagine_default_small not found` type errors as the route has been renamed in Liip 1.0.0
- When using the `ImageProvider`, setting a CDN breaks the Liip routes, as it modifies the image generation path (e.g. with a server path, the URL will be `/uploads/media/app.php/uploads/media/default/0001/01/image.jpeg`). When using liip, we should skip all CDN path modification.
- Video and file thumbnails never generated on Media entity creation as [`LiipImagineThumbnail::generate`](https://github.com/sonata-project/SonataMediaBundle/blob/master/Thumbnail/LiipImagineThumbnail.php#L70) always returns false, resulting in broken images when using the `sonata_media_type` form type.
- The [`MediaController::liipImagineFilterAction`](https://github.com/sonata-project/SonataMediaBundle/blob/master/Controller/MediaController.php#L110) action uses the provider to fetch the image content and store it in a temporary file, then uses imagine to generate the filter and redirect path. Given that the latter part of that implementation (should be) identical to Liip's [`ImagineController::filterAction`](https://github.com/liip/LiipImagineBundle/blob/master/Controller/ImagineController.php#L77), I propose, to get rid of duplicate code, we should either:
  - Break out this method into it's own class and extend `ImagineController`, or
  - Call `$this->get('liip_imagine.controller')->filterAction(...)`

I'll submit a PR soon to get started.

**Comment by stiffroy** [comment]
Any more info of progress?

**Comment by jordisala1991** [comment]
Let's move the liip imagine discussion to a unique issue: #994
