### ISSUE TITLE
unable to edit sonata media field in fornt end

### ISSUE THREAD

**Issue by womenDev** [sonata-project/SonataMediaBundle#985]
Hello, I added a picture in sonata User , when i try to update profile user , all user fields change but  media file  doesnt work .
Any idea about editing sonata media field in frontEnd please ? 

Thank you in advance.
Best regards,

**Comment by jordisala1991** [comment]
Not enough information to help you, sorry.

Closing. If you still have this issue, ping me to reopen but provide more info
