### ISSUE TITLE
Usage without sonata admin ?

### ISSUE THREAD

**Issue by Padam87** [sonata-project/SonataMediaBundle#991]
php app\console cache:warmup

**Fatal error: Class 'Sonata\AdminBundle\Controller\CRUDController' not found in .....\vendor\sonata-project\media-bundle\Controller\GalleryAdminController.php on line 19**

To fix it I have to add the admin bundle to the dependencies, which is far from ideal. Any suggestions?

**Comment by greg0ire** [comment]
Wow. Does anyone know why the admin bundle isn't required ? It is referenced in `GalleryAdminController`, apparently.

**Comment by core23** [comment]
It is an optional dependency and should work without the ``SonataAdminBundle``, see: https://github.com/sonata-project/SonataMediaBundle/blob/master/DependencyInjection/SonataMediaExtension.php#L86

**Comment by greg0ire** [comment]
Indeed, I just saw that in the doc.

**Comment by greg0ire** [comment]
@Padam87 , can you use `app/console -vvv cache:warmup` and give us a full stack trace ?

**Comment by Padam87** [comment]
It is only an issue when warming the cache after a clear. Unfortunately the -vvv option wasn't really helpful.

Fatal error: Class 'Sonata\AdminBundle\Controller\CRUDController' not found in .....\vendor\sonata-project\media-bundle\Controller\GalleryAdminController.php on line 19

                                                                                            
  [Symfony\Component\Debug\Exception\ClassNotFoundException]                                
  Attempted to load class "CRUDController" from namespace "Sonata\AdminBundle\Controller".  
  Did you forget a "use" statement for another namespace?                                   
                                                                                            

Exception trace:
 () at ....\vendor\sonata-project\media-bundle\Controller\GalleryAdminController.php:19

**Comment by Padam87** [comment]
Maybe I'm wrong, but this seems like a class loader problem?

**Comment by greg0ire** [comment]
Well if you don't have the admin bundle, it will not load, so yeah…

**Comment by greg0ire** [comment]
How does warmup find this class ? Is there any route pointing to it?

**Comment by greg0ire** [comment]
@Padam87 : have you had a look at the routes (`debug:router` ? )

**Comment by Padam87** [comment]
Yep, routing is not the problem. It is caused by the DiExtra bundle.

https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/HttpKernel/ControllerInjectorsWarmer.php#L46

Can be fixed by adding the file to the blacklist.

```yml
jms_di_extra:
    cache_warmer:
        controller_file_blacklist:
            - %kernel.root_dir%/../vendor/sonata-project/media-bundle/Controller/GalleryAdminController.php
```

**Comment by greg0ire** [comment]
Would you do us a big favor and document that ?

**Comment by Padam87** [comment]
Yep, I will add it to the troubleshooting section.
