### ISSUE TITLE
Liip Imagine Bundle 1.5.x

### ISSUE THREAD

**Issue by stiffroy** [sonata-project/SonataMediaBundle#994]
I was wondering if anyone has recently been successful to integrate the LiipImagineBundle with the media bundle? I tried all the means possible but it seems like I failed in something or the other every time. I think the documentation is also too old. Can anyone who has been successful in integrating the bundle please give some hints for successfully making the bundle work? Thanks in advance.

**Comment by enekochan** [comment]
Same problem here, not able to integrate LiipImagineBundle 1.* with SonataMediaBundle 3.x-dev. I end up with errors like this:

```
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "_imagine_business_images_big" as such route does not exist.").
```

Just the same as in #842 #984 for example

**Comment by idhard** [comment]
i think this pull request try to solve this issue :  https://github.com/sonata-project/SonataMediaBundle/pull/1242 , i have installed it locally and at least im not getting an exception , still i have to check why the url generated is not the same as before . Hope it helps

**Comment by stiffroy** [comment]
Thank you very much. I will try it in the weekend if I get time.

**Comment by jordisala1991** [comment]
If you tested that PR, could you report on the PR if everything is working? 

That way it will make easier for us to know if everything is working or not. Thanks :)

**Comment by idhard** [comment]
finally i decided to make a rollback of the changes in my environment . I had noticed that is adding some BC on the way the image urls path are generated , i will try to report it in more detailed way.
i don't remember well but i think it added an extra level in the path like "media/RESOLVE/IMAGE_STYLE/..." and before was "media/IMAGE_STYLE" need to confirm you.

**Comment by jordisala1991** [comment]
When you have a report, could you post in on the PR instead of this issue?
