### ISSUE TITLE
Detect memory limits

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataMediaBundle#995]
Sometimes when you upload huge files, you could get the following expection:

```
Allowed memory size of 268435456 bytes exhausted (tried to allocate 23884 bytes
) in <b>/www/htdocs/***/vendor/imagine/imagine/lib/Imagine/Gd/Image.php</b> on line <b>553</b>
```

Maybe we could find a way to detect how much memory would be used for that operation and throw an exception instead.

**Comment by greg0ire** [comment]
The idea is good, but I can't think of an easy way to guess that (otherwise there probably would be something to deal with that built-in imagine, right?). Not sure it's the responsibility of this bundle either.

**Comment by core23** [comment]
Maybe we can reduce some limits with a client side image resizing?

**Comment by greg0ire** [comment]
> Maybe we can reduce some limits with a client side image resizing?

Won't that mean we have even less control on whether it works or not? Might work on a recent machine, might not work. Plus, it might be a big change, right?

**Comment by core23** [comment]
Some month's ago I had found a jQuery library that will resize image via the new canvas element, but don't know the name :(

What I remembered, that it has a fallback with a normal upload.

**Comment by greg0ire** [comment]
A fallback system could be great

**Comment by core23** [comment]
https://github.com/sonata-project/SonataMediaBundle/pull/1107 will partial solve this
